zulip/zulip-flutter

lib/model/content.dart, lib/widgets/content.dart
Replaces #2, which was closed when I deleted/recreated my GitHub fork.
=> content: Handle image emoji

lib/widgets/message_list.dart
And write up some findings about how safe-area handling works in Flutter.
=> msglist: Pad left and right insets

lib/api/route/messages.dart, lib/api/route/messages.g.dart, lib/model/store.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/dialog.dart, lib/widgets/message_list.dart
The first several commits are sent separately in #8.
-----
Add a prototype compose box
- that can compose a stream message but not a PM
- that sends to stream ID 7, which on CZO is "test here"
- that's missing the native iOS text-input UI features, like
scanning text with the camera (we want to write a thin wrapper
around UITextField and UITextView for that).
- that doesn't have autocomplete
- that doesn't have quote-and-reply, attach-a-file, etc.
- that doesn't send typing notifications
- (etc.; this is a prototype :-) )
=> compose: Prototype compose box, using Material `TextField` widget

lib/widgets/content.dart, lib/widgets/message_list.dart
As discussed on CZO:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20lightbox/near/1512718
=> content [nfc]: Store `message` on MessageContent widget

README.md, pubspec.lock, pubspec.yaml
In particular this gets us the new scroll curve for Android that fixes several issues with scrolling:
https://github.com/flutter/flutter/pull/120420
Also drop the upper bound on Flutter versions from the pubspec.yaml, as it turns out it's ignored.
See #15.
=> deps: Switch to getting Flutter from the main channel

.mailmap
In particular, copying the comments from that repo's .mailmap file as of current main (commit zulip/zulip-mobile@deab4ad4b).
=> git: Add .mailmap file, copying comments from zulip/zulip-mobile

lib/model/store.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/store.dart
Another step toward #13 . This sets up an appropriate home (the `GlobalStore`) for data like the list of accounts, and which one is the active account (the one we should immediately show on launching the app), to live.
=> Reorganize data-managing widgets to accommodate global data

lib/api/core.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/store.dart, test/api/fake_api.dart, test/api/model/events_checks.dart, test/api/model/events_test.dart, test/api/model/model_checks.dart, test/api/route/messages_test.dart, test/api/route/route_checks.dart, test/example_data.dart
This is motivated just now by #21 by way of a couple of steps of yak-shaving (while #21 is itself yak-shaving for #13 which is for #11.) But it's also something we'll clearly want in any case.
For #21, we'll want some logic where the `GlobalStore` keeps around a collection of `PerAccountStore`s, and when asked can pull out an existing one or load up a new one as needed. Because the loading is async (it involves talking to the server to fetch initial data; in the future it might start by reading a local snapshot from a database, but that'll also be async), the logic to prevent two concurrent calls from redundantly both doing the work is a bit more than trivial. I wrote up that logic and then figured it should have a test.
But the test shouldn't go try to talk to an actual Zulip server. So …
=> Make API logic testable, and start testing some

lib/model/store.dart, lib/widgets/app.dart, lib/widgets/store.dart
Another step toward #21 and #13.
=> Simplify API of data-managing widgets a bit, and document

lib/model/store.dart, lib/widgets/app.dart, lib/widgets/store.dart, test/api/fake_api.dart, test/example_data.dart, test/model/store_test.dart
This is stacked atop #26.
As part of #21, we'll want to be able to freely instantiate a `PerAccountStoreWidget` whenever we want to mark some subtree as being for a particular account, and have that cheaply just refer to the already-loaded data for that account. This PR does that by having a `GlobalStore` maintain a `PerAccountStore` for each account, which `PerAccountStoreWidget` asks it for when it's first mounted in the element tree.
Because the logic in `GlobalStore` to maintain that, and in particular to avoid redundant requests if several `PerAccountStoreWidget`s ask about the same account at the beginning, is a bit complex, we want tests for it. To make those possible, we split both `GlobalStore` and `PerAccountStore` into a base class (which keeps the name) and a subclass that …
=> store: Have GlobalStore manage one PerAccountStore per account

lib/widgets/app.dart, lib/widgets/page.dart, lib/widgets/store.dart, pubspec.lock
Fixes: #21
---
For combining this with #29, the diff looks like:
```diff
diff --git a/lib/widgets/content.dart b/lib/widgets/content.dart
index e970e4760..9998ab8d8 100644
--- a/lib/widgets/content.dart
+++ b/lib/widgets/content.dart
@@ -196,3 +196,4 @@ class MessageImage extends StatelessWidget {
onTap: () {
-        Navigator.of(context).push(getLightboxRoute(message: message, src: resolvedSrc));
+        Navigator.of(context).push(getLightboxRoute(
+            context: context, message: message, src: resolvedSrc));
},
diff --git a/lib/widgets/lightbox.dart b/lib/widgets/lightbox.dart
index bddbf6f38..c2d790591 100644
--- a/lib/widgets/lightbox.dart
+++ b/lib/widgets/lightbox.dart
@@ -7,2 +7,3 @@ import '../api/model/model.dart';
import 'content.dart';
+import 'page.dart';
import …
```
=> store: Move PerAccountStoreWidget down into individual routes

lib/api/core.dart, lib/widgets/content.dart, lib/widgets/message_list.dart, test/widgets/content_test.dart
Keeping the user's API key out of these URLs makes it easier to
avoid leaking the API key, e.g. to the clipboard with a future "copy
image link" feature.
=> msglist: Use HTTP header instead of URL query param to auth image requests

lib/api/route/account.dart, lib/api/route/account.g.dart, lib/model/store.dart, lib/widgets/app.dart, lib/widgets/login.dart, lib/widgets/store.dart
There's plenty more to do to improve the UX of this, and I've
filed several follow-up issues.  Most critically, we'll need
to store the resulting credentials on the device (#34), so you don't
have to repeat the login each time you start the app.
But this is enough that it becomes possible to log in at an
account of your choice, making the flow testable end to end.
In particular this makes a useful bootstrapping step toward
the task of storing data locally (#13): with this, there's now some
useful data we could store.
Fixes: #11
=> login: Add a basic login flow

ios/Podfile.lock, ios/Runner/Info.plist, lib/api/core.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/route/messages.dart, lib/api/route/messages.g.dart, lib/model/store.dart, lib/widgets/compose_box.dart, pubspec.lock, pubspec.yaml, test/api/fake_api.dart, test/example_data.dart
=> compose: Prototype upload-file UI

ios/Podfile.lock, ios/Runner/Info.plist, lib/widgets/compose_box.dart, lib/widgets/dialog.dart, pubspec.lock, pubspec.yaml
Marking as draft while we think through how to get the right photo/video-picker UI on Android (details at https://github.com/zulip/zulip-flutter/issues/56#issuecomment-1513993031 ) but the code is reviewable in the meantime, and people can try out the new features. 🙂
Fixes: #61
Fixes: #56
=> compose: Prototype upload-from-library and upload-from-camera

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/store.dart, test/api/model/model_test.dart, test/example_data.dart
Seeing the convenient line `flutter: initial fetch time: …` in the logs, I decided to do some trials before and after these commits. 🙂 First after, then I went back and did before (i.e. `main` 915216760c78f6624f9cd46568dad525fc9664ab).
```
After:
3790ms
2842ms
2774ms
2781ms
2735ms
2851ms
2954ms
2926ms
2888ms
2998ms
Before:
2798ms
2551ms
2916ms
3017ms
2832ms
3032ms
2281ms
3400ms
2868ms
2387ms
```
=> store: Add PerAccountStore.users data structure, as Map<int, User>

lib/model/autocomplete.dart, test/example_data.dart, test/model/autocomplete_test.dart
This is atop my current revision of #84. It excludes much of the work we did in the office together, which I still have in a draft branch (and which I have an open question about: [czo](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20autocomplete.20computations/near/1559416))—but this seems like a self-contained piece of logic that we'll need, and that we'll want to get right.
Related: #49
=> autocomplete: Add and test MentionAutocompleteQuery

pubspec.lock, pubspec.yaml
deps: Upgrade package:checks, returning to published releases
There's now a new published version, so we can switch to that.
This effectively reverts e2d592dd0 / #50.
---
deps: Upgrade packages to latest
Done with `flutter pub upgrade --major-versions`.
This updates two constraints in our pubspec.yaml:
https://pub.dev/packages/device_info_plus/changelog
https://pub.dev/packages/share_plus/changelog
The breaking changes that caused the major-version bumps are the
same in both packages, and only mean dropping support for old
versions of iOS, Android, and the Android Gradle Plugin.
These don't affect us.
---
I also directly pushed a few minutes ago a couple of dependency-related commits:
2ba4e713d lint: Directly ignore use_build_context_synchronously, where needed
5a59640ed deps: Upgrade …
=> deps: Upgrade all packages

lib/widgets/input.dart, lib/widgets/login.dart, test/widgets/login_test.dart
This leaves plenty more to do for #35, but this should be pretty helpful for people filling out the realm-URL input.
This PR align this UI with zulip-mobile in several ways toward #35:
- We give feedback when the input doesn't look right:
- when it's empty
- when URL parsing fails
- when a scheme is given other than `http` or `https`
- when the text looks like an email address
- We accept a URL with the leading `https://` left implicit
- We show a progress spinner for the server-settings request
- We show an error dialog when the server-settings request fails
- We use "your-org.zulipchat.com" as hint text in the input component, like in zulip-mobile
It also aligns with zulip-mobile in a few smaller ways that are nice, but maybe don't fall under #35 
- The software keyboard says "go" …
=> login: Be a bit more helpful in realm-url-input UI

lib/widgets/login.dart
(Leaving a TODO to actually do form validation that the username is
an email address, when appropriate.)
Fixes-partly: #35
=> login: Explicitly handle both values of requireEmailFormatUsernames, mostly

lib/api/core.dart, lib/api/route/account.dart, lib/api/route/events.dart, lib/api/route/messages.dart, lib/api/route/realm.dart, lib/api/route/users.dart, lib/model/store.dart, lib/widgets/login.dart, test/api/fake_api.dart, test/api/route/messages_test.dart
(Stacked atop #93.)
This helps set us up for #37: we're going to add significant new logic for interpreting the HTTP response from an API call, in order to throw appropriate exceptions, and in order to do that we'll want just one place for that logic to have to go.
As a bonus, this also simplifies the code, with a net negative diffstat, and makes the core API layer more testable.
=> api: Centralize interpreting HTTP response in one place

lib/widgets/sticky_header.dart
This was introduced recently upstream, deprecating the old mixin SlottedMultiChildRenderObjectWidgetMixin.
This change follows up on 2f0f4692f (from #103), which handled the mandatory part of the same upstream API change.
=> sticky_header [nfc]: Use new SlottedMultiChildRenderObjectWidget base class

lib/api/core.dart, test/api/core_test.dart, test/api/fake_api.dart, test/api/route/messages_test.dart, test/stdlib_checks.dart, test/widgets/login_test.dart
The main ingredient here is that we have FakeHttpClient log the last `http.Request` object it was passed, and we add some `package:checks` extensions so that tests can conveniently inspect that request.
We also fix a small bug in `ApiConnection.postFileFromStream`, which writing these tests uncovered: it was doubling the slash at the start of the URL path.
This makes another step toward #37.
=> api: Write tests for ApiConnection.get, post, postFileFromStream

lib/api/core.dart, lib/api/exception.dart, lib/api/route/account.dart, lib/api/route/events.dart, lib/api/route/messages.dart, lib/api/route/realm.dart, lib/api/route/users.dart, lib/widgets/login.dart, test/api/core_test.dart, test/api/exception_checks.dart, test/api/fake_api.dart, test/api/route/messages_test.dart, test/stdlib_checks.dart
This follows up on the test infrastructure in #112 and the refactorings in #96.
These exceptions are quite a lot like the ones we have in zulip-mobile, defined in `src/api/apiErrors.js` there.  The main differences are:
* Each exception has a `routeName` property, to identify what route was involved.  This is information that can be quite helpful in debugging; and while it should typically be possible to work it out from looking at the stack, it's nicer to be explicit.
* The exception types are named like FooException, whereas they're FooError in zulip-mobile.  This is just to conform to Dart convention, where there's an Exception type and an Error type, and these are definitely Exception and not Error because they don't necessarily represent any bug in the program.
* We include JSON data …
=> api: Throw a structured exception when a request fails

lib/model/autocomplete.dart, lib/model/store.dart, pubspec.lock, pubspec.yaml, test/example_data.dart, test/model/autocomplete_checks.dart, test/model/autocomplete_test.dart, test/model/test_store.dart
Thanks @gnprice for demonstrating tests for this tricky async logic (and also guiding its implementation)! I've added some more tests in this revision:
```dart
test('MentionAutocompleteView yield between batches of 1000', () async {
```
```dart
test('MentionAutocompleteView new query during computation replaces old', () async {
```
```dart
test('MentionAutocompleteView mutating store.users while in progress causes retry', () async {
```
and kept the "DEV DEMO" commit from my earlier draft in case that's convenient for more manual testing. (Marking as a draft just because of that commit.)
=> autocomplete: Add and test MentionAutocompleteView

lib/api/core.dart, lib/api/model/events.dart, lib/api/model/initial_snapshot.dart, lib/api/model/model.dart, lib/api/route/events.dart, lib/api/route/messages.dart, lib/model/content.dart, lib/model/message_list.dart, lib/model/store.dart, lib/widgets/action_sheet.dart, lib/widgets/compose_box.dart, lib/widgets/content.dart, lib/widgets/dialog.dart, lib/widgets/draggable_scrollable_modal_bottom_sheet.dart, lib/widgets/lightbox.dart, lib/widgets/message_list.dart, lib/widgets/sticky_header.dart, lib/widgets/store.dart, test/api/model/events_test.dart, test/api/route/messages_test.dart, test/model/store_test.dart
Prompted by being about to modify some of the code that's densest with the old patterns, for #72.
---
fmt [nfc]: Fix basic formatting from early-prototype code
There's a set of formatting patterns we've pretty well settled into at this point.  But there's still some swathes of code that don't adhere to them -- mainly from the early prototype period, when we were just figuring out how to write Dart and how we wanted the code to look.
So, here's a quick sweep through our code to apply our current patterns more uniformly.
The major one is indentation: we use 2-space indents throughout, rather than 4-space.  This diff therefore looks a lot smaller with `git diff -b`.
The other one packaged into this same commit is how we close widgets: like `)));` at the end of the innermost child, rather …
=> [nfc] Fix formatting from early-prototype code

lib/widgets/compose_box.dart
Looks like I forgot to get this one in #98, oops.
=> compose: Add `tooltip` to send button

ios/Podfile.lock, lib/widgets/about_zulip.dart, lib/widgets/app.dart, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Runner/Info.plist, pubspec.lock, pubspec.yaml
(EDITED following https://github.com/zulip/zulip-flutter/pull/101#pullrequestreview-1442671917 . Notably, this revision doesn't address #100.)
-----
From this new page, the user can tap a button to show [LicensePage],
so resolving #99.
Fixes: #99
=> accounts ui: Offer Flutter's [LicensePage], to acknowledge software used by the app

lib/model/database.g.dart, pubspec.lock, pubspec.yaml
Commit messages:
---
lint: Update database.g.dart to suppress unnecessary_cast too
This happens automatically if you rerun build_runner.  Seems like
its omission was basically a mismerge between 901a99eb8, when it
was merged early from #84:
https://github.com/zulip/zulip-flutter/pull/84#issuecomment-153384586
and 780b09283 / #22, which added this file.
Chalk it up as another occasion where #60 would have helped keep
things clean.
---
deps: Upgrade drift, drift_dev, sqlparser
The upgrade to drift_dev 2.8.x seems to be required in order to
work with the upgrade to analyzer 5.12.0 that we took in 861a92911.
The others are in turn required for that.
This makes another occasion where having CI, #60, would have helped
keep things clean for us.
---
deps: Upgrade watcher
With a recent Dart SDK …
=> deps: Upgrade all; fix build_runner

lib/api/model/narrow.dart, lib/api/route/messages.dart, lib/model/message_list.dart, lib/model/narrow.dart, lib/model/store.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart, test/api/route/messages_test.dart
(Stacked atop #137.)
This PR extends the API bindings for getMessages and sendMessage so that they cover the API more completely. In particular this means:
* getMessages accepts a general narrow, rather than hardcoding the all-messages narrow.
* sendMessage accepts an arbitrary conversation, rather than only stream conversations and hardcoded to `#test here` (and limited to chat.zulip.org).
This takes us toward:
* #72
Still to do for that issue, and present in a draft branch:
* adding streams data from the server
* adapting the compose box by narrow
* adapting the message-list app bar by narrow
* making recipient headers touchable to navigate to different narrows
* adding PmNarrow as another Narrow subclass
=> api: Get and send messages from arbitrary places, not hard-coded

lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/store.dart, test/example_data.dart
=> Add streams to PerAccountStore

lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart
This is enough that the app starts to be usable for more real-world use cases! Yesterday when I was on the go and had a real, non-test message I wanted to send, I had a draft of this branch already on my phone, and realized that it meant I could use zulip-flutter to send the message instead of zulip-mobile, so I did. That also marked the first time I'd logged into the Flutter app with my main account (rather than test accounts).
(Specifically, if what you want to do is send a message in some stream you've recently gotten a message in, you can do it: go to "All messages", find a message to that stream, tap the stream part of the header to get to the stream narrow, then use the compose box. With #144 that will work with the topic narrow too, with #142 it'll broaden to DMs, and of course …
=> Add stream and topic narrows

ios/Podfile.lock
=> deps: Fix issues in Podfile.lock

lib/api/model/model.dart, lib/api/model/model.g.dart, lib/api/model/narrow.dart, lib/api/route/messages.dart, lib/model/narrow.dart, lib/widgets/message_list.dart, test/api/route/messages_test.dart
There was only one occurrence in the UI, in [DmRecipientHeader].
The remaining few places we refer to the old names are in the context of the server API.  We have issue #146 open to start using the new names there where possible.
Fixes: #145
=> Say "DM"/"direct message" instead of "PM"/"private message", in UI and code

pubspec.lock, pubspec.yaml
deps: Upgrade Flutter to latest main, 3.11.0-18.0.pre.81
And update Flutter's supporting libraries to match,
namely matcher, test, test_api, and test_core.
---
deps: Upgrade packages within constraints (flutter pub upgrade)
There are currently no upgrades that `--major-versions` would add
beyond these.
---
deps: Bump json_annotation lower bound to latest, 4.8.1
Otherwise we get the following warning when running build_runner
(wrapped here for readability):
[WARNING] json_serializable on lib/api/route/users.dart:
The version constraint "^4.8.0" on json_annotation
allows versions before 4.8.1 which is not allowed.
I believe that warning was introduced with the json_serializable
upgrade from 6.6.2 to 6.7.0 in f28dd0bfc / #137.
=> deps: Upgrade all; fix warning from json_serializable

macos/Podfile.lock
Like #148, I think, but for `macos/Podfile.lock` instead of `ios/Podfile.lock`. I probably should have done this as part of #148; ah, well. 🙂
=> deps: Fix issues in Podfile.lock, this time in macos/

lib/api/core.dart, lib/api/model/narrow.dart, lib/api/route/account.dart, lib/api/route/messages.dart, lib/api/route/realm.dart, lib/model/store.dart, lib/widgets/login.dart, test/api/fake_api.dart, test/api/route/messages_test.dart, test/example_data.dart
Fixes: #146 
---
In #146 I listed these two spots where we'd want to use this capability once we added it, and mentioned that there might be others. On scanning through a grep for `TODO.server`, though, these are the only such places that I find.
=> api: Carry zulipFeatureLevel on ApiConnection, and use it for sending "direct" and "dm"

lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/narrow.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart, test/api/model/model_test.dart, test/example_data.dart, test/model/narrow_checks.dart, test/model/narrow_test.dart
This implements #142. Along the way, we also make the list of recipients of a DM somewhat cleaner to deal with, in particular by sorting it canonically up front; and we add a bit more testing infrastructure.
Fixes: #142
=> Add DM narrows; clean up DM recipients some more in API

lib/main.dart, lib/model/binding.dart, lib/model/store.dart, lib/widgets/store.dart, test/model/binding.dart, test/model/store_checks.dart, test/model/store_test.dart, test/model/test_store.dart, test/widgets/content_test.dart, test/widgets/store_test.dart
This implements #30 with an architecture modeled on Flutter's own "binding" concept, along the lines anticipated in the issue's description.
Along the way we add tests for GlobalStoreWidget and PerAccountStoreWidget, including a test for the slightly tricky — and important for a smooth UX — "zero-frame loading" optimization that PerAccountStoreWidget has. Then we add the tests we've wanted for RealmContentNetworkImage, a widget that consumes data from PerAccountStoreWidget, demonstrating that such code is now testable and completing #30.
The setup code required in individual tests still feels a bit unwieldy, and I think it's likely we'll either tweak it in the future or add convenience abstractions on top of it. But the time for that is after we have a few more examples — at this point we …
=> Add DataBinding; start testing code that uses PerAccountStoreWidget

lib/api/model/narrow.dart, lib/api/route/messages.dart, lib/api/route/messages.g.dart, test/api/route/messages_test.dart
We can use this to get raw Markdown content for quote-and-reply
(#116) and for the "Share" option on a message. For those, we only
care about the raw Markdown content and so could just as well have
used the `raw_content` field on the get-single-message response, for
servers pre-120. But...
We can also use this for #73, "Handle Zulip-internal links by
navigation", to follow /near/<id> links through topic/stream moves
(see implementation in zulip-mobile). For that, we'll need more than
just the message's raw Markdown.
Fixes: #140
=> api: Add getMessageCompat helper, for servers with and without FL 120

lib/model/autocomplete.dart, lib/model/narrow.dart, lib/widgets/compose_box.dart, test/model/autocomplete_checks.dart, test/model/autocomplete_test.dart
=> Add compose box for topic and DM narrows

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/model/store.dart, test/model/test_store.dart
Also, add `addStream` / `addStreams` helpers to `PerAccountStoreTestExtension`. We'll use those soon, to write tests for message-link creation for quote-and-reply.
Fixes: #181
Related: #182
=> store: Update `streams` and `subscriptions` on stream-create/delete events

lib/model/compose.dart, test/model/compose_test.dart
For the corresponding logic used in the web app and zulip-mobile, see web/shared/src/fenced_code.ts.
I believe the logic here differs from that in just this way: it follows the CommonMark spec more closely by disqualifying backtick-fence lines where the "info string" has a backtick, since that's not allowed:
> If the info string comes after a backtick fence, it may not
> contain any backtick characters. (The reason for this restriction
> is that otherwise some inline code would be incorrectly
> interpreted as the beginning of a fenced code block.)
Regarding the new file lib/model/compose.dart, we do have existing code that could reasonably move here, but it's pretty simple. It's the code that gives the upload-file Markdown; see
registerUploadStart and registerUploadEnd in …
=> model: Add wrapWithBacktickFence, to use with quote-and-reply

lib/model/compose.dart, test/example_data.dart, test/model/compose_test.dart
We'll use this for quote-and-reply #116.
This revision sits atop my current revision of #179, which is another quote-and-reply subtask.
=> compose: Add `narrowLink` helper, to write links to Narrows

lib/model/content.dart, lib/widgets/content.dart, test/model/content_checks.dart, test/model/content_test.dart
This lays all the foundations we need in order to write tests for our content-parsing code, and then does so for all the existing code.
We'll want such tests for #71, which will add a new form of complication to that code. We'll also want it as we implement more features in the content parsing in general.
To get helpful debugging output when tests fail, we use the Diagnosticable class from Flutter to produce readable printouts of the content nodes:
https://api.flutter.dev/flutter/foundation/Diagnosticable-mixin.html
https://api.flutter.dev/flutter/foundation/Diagnosticable/debugFillProperties.html
=> Test content parsing; use Diagnosticable; write docs for ContentNode etc.

lib/model/content.dart, test/model/content_checks.dart
I merged #205, and then a half-hour later saw a nicer way to do it. Better output on failure, and also less boilerplate code to write and update.
Happily none of the test cases change at all ­— only the infrastructure under them.
Before (if I artificially break one of the tests):
```
00:01 +16 -1: parse two plain-text paragraphs [E]                               
Expected: a ZulipContent that:
is a ZulipContent
has nodes that:
is deeply equal to (A value that:
is a BlockContentNode
is a ParagraphNode
has wasImplicit that:
equals <false>
has nodes that:
is deeply equal to (A value that:
is a InlineContentNode
equals <TextNode
"hello">),
A value that:
is a BlockContentNode
is a ParagraphNode
has wasImplicit that:
equals <false>
has nodes that:
is deeply equal to (A value that:
is a …
```
=> content test: Compare parse trees via Diagnosticable

lib/model/content.dart, test/model/content_checks.dart, test/model/content_test.dart
The interesting parts of this are about tracking on each block inline container (notably each `ParagraphNode`) the set of link nodes found in its subtree. We'll need that information for #71, for reasons explained there.
Computing it involves adding a bit of complexity (that we were pretty much bound to eventually need for one reason or another), making the content-parser a stateful object.
This PR doesn't yet go on to have the widgets actually consume this information. I have a draft branch for that (corresponding to part of #204), but want to write some tests for it.
=> Record links when parsing content

lib/widgets/content.dart
This is another segment of my draft branch #204, toward #71.
I think these refactors stand on their own, but in particular they will be helpful for (a) creating a stateful widget to hold gesture recognizers for links in a given BlockInlineContainerNode, and (b) threading those recognizers down through building the inline spans for that node's subtree.
=> Refactor content widgets toward touchable links

lib/api/model/model.dart, lib/model/compose.dart, lib/model/narrow.dart, lib/widgets/action_sheet.dart, lib/widgets/compose_box.dart, lib/widgets/dialog.dart, lib/widgets/message_list.dart, test/api/fake_api.dart, test/example_data.dart, test/flutter_checks.dart, test/model/compose_test.dart, test/model/narrow_test.dart, test/widgets/action_sheet_test.dart, test/widgets/compose_box_checks.dart, test/widgets/compose_box_test.dart, test/widgets/dialog_checks.dart
=> action_sheet: Add "Quote and reply" button 🎉

lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/model/narrow.dart, lib/model/recent_dm_conversations.dart, lib/model/store.dart, pubspec.lock, pubspec.yaml, test/example_data.dart, test/model/recent_dm_conversations_checks.dart, test/model/recent_dm_conversations_test.dart, test/model/store_test.dart, test/widgets/action_sheet_test.dart, test/widgets/content_test.dart, test/widgets/store_test.dart
Toward #119, the list of recent DM conversations.
Inspired by how we do this in zulip-mobile, including in the tests.
=> store: Add RecentDmConversationsView view-model

ios/Podfile.lock, lib/main.dart, lib/model/binding.dart, lib/model/content.dart, lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/store.dart, lib/widgets/text.dart, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Podfile.lock, pubspec.lock, pubspec.yaml, test/model/binding.dart, test/model/test_store.dart, test/widgets/action_sheet_test.dart, test/widgets/content_test.dart, test/widgets/store_test.dart
Fixes #71.
Stacked atop #203.
This is a draft. The branch needs some cleanup, but more fundamentally:
* I want to write some tests for this code, because the content parsing in particular gains some complexity of a kind it didn't need before. That turns out to be a bit of a yak shave.
* The way I handle making the links respond both to a tap (to follow the link) and a long-press (to copy the URL) feels like a bit of a hack. I may make some further attempts to clean it up, and should probably also find or start an upstream Flutter discussion of how to do this (i.e. how to have a `TextSpan` respond to two different gestures). I might end up separating the long-press into a separate PR from the main functionality of tapping to follow the link.
But from a user perspective, this version …
=> Touchable links in messages

.vscode/settings.json
The details here are largely borrowed from the Flutter repo, and in particular the subtleties most recently added there:
https://github.com/flutter/flutter/pull/122758
This config does the job in my testing.
Note that it doesn't affect any of the things the editor does to simply augment your typing: adding indentation when you hit enter, adding a close-paren when you type an open-parent, and so on. Those are perfectly fine -- most of all because they only affect the code you actually intended to edit, but also because they generally get things right -- and continue operating as usual.
Fixes: #229
=> vscode: Disable reformatting whole swaths of code

lib/model/autocomplete.dart, lib/model/compose.dart, lib/widgets/autocomplete.dart, lib/widgets/compose_box.dart, test/model/compose_test.dart, test/widgets/autocomplete_test.dart
(edited)
I'll follow up with specific issues this doesn't yet address, but here's a 1.0 of the @-mention autocomplete feature! 🎉
Fixes: #49
Fixes: #129
=> @-mention autocomplete UI

test/widgets/action_sheet_test.dart
=> tests: Adapt to change in [MenuItemButton.onPressed] logic that broke tests

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
Introducing a scroll-to-bottom button in the `MessageList` component that shows up only if the user is not at the bottom of the list. Clicking on that button triggers a scroll to the bottom.
- My initial version wrapped the MessageList with another component that controlled scrolling, but I was able to fix the re-rendering issue while putting integrating the functionality right in the component. A benefit of having wrapper component may be to reuse the scroll-to-bottom feature but I don't believe that is used in any other context (the list of streams or users do not have this).
- I did not add a test case yet, I would prefer to wait for a greenlight on the implemented component as the test case would need some knowledge of implementation to trigger and check results
=> msglist: add scroll-to-bottom button to MessageList

lib/widgets/app.dart
The ink effect is already provided when you pass onTap to ListTile; see example:
https://api.flutter.dev/flutter/material/ListTile-class.html#material.ListTile.8
Tested on my iPhone.
=> choose-account [nfc]: Remove redundant InkWell

lib/model/binding.dart, lib/widgets/action_sheet.dart, lib/widgets/clipboard.dart, test/flutter_checks.dart, test/model/binding.dart, test/test_clipboard.dart, test/widgets/action_sheet_test.dart, test/widgets/clipboard_test.dart
This leaves some TODOs in the tests, for testing code that calls into a Flutter plugin. Greg is working on a good way to do that; see https://github.com/zulip/zulip-flutter/pull/204#discussion_r1253664445.
Empirically, the relevant calls here return Futures that never resolve, which will be fine until we want to stub out the native-code functionality.
Fixes: #132
=> Add "Copy to clipboard" button to message action sheet

lib/model/autocomplete.dart, lib/widgets/autocomplete.dart, lib/widgets/message_list.dart, lib/widgets/store.dart, test/flutter_checks.dart, test/widgets/store_test.dart
I'm hoping this helper might be useful for reducing duplicated code, but I'm not certain it's the best pattern and I'd be interested in feedback. 🙂 If it seems good, I plan to use it in the recent DM conversations widget, for #119, soon.
=> store [nfc]: Add and use PerAccountStoreAwareStateMixin

lib/api/model/events.dart, lib/api/model/model.dart, lib/model/message_list.dart, lib/model/store.dart, test/api/model/model_checks.dart, test/example_data.dart, test/model/message_list_test.dart
This propagates the `UpdateMessageEvent` to the `MessageListView`, allowing you to see changes to your messages in real time.
Putting this up as a draft, since I have a few questions - leaving my comments inline.
=> Handle UpdateMessageEvent in MessageListView (#118)

lib/api/model/model.dart, lib/api/model/model.g.dart, lib/widgets/message_list.dart, test/example_data.dart, test/test_images.dart, test/widgets/content_checks.dart, test/widgets/content_test.dart, test/widgets/message_list_test.dart
Now, as demonstrated in the new test, if the author of a message
changes their avatar, we'll see the update in the message list as
soon as we get the event.
While we're at it, comment out the property on [Message] to guide
future consumers to [User].
Related: #135
=> msglist: Use [User.avatarUrl] instead of [Message.avatarUrl]

lib/widgets/content.dart, lib/widgets/lightbox.dart, lib/widgets/message_list.dart, test/widgets/content_test.dart
Helpful anyway, I think, but this came up when thinking about avatar URLs, for #119.
=> urls [nfc]: Pass around `Uri` objects more (cut out some unneeded re-stringification)

test/widgets/content_checks.dart
This was accidentally clobbered in the merge of #247; see
https://github.com/zulip/zulip-flutter/pull/247#issuecomment-1664710827
=> test: Fix wrong type in RealmContentNetworkImageChecks

test/example_data.dart, test/model/message_list_test.dart
This makes a number of small improvements to the tests for our recently-added handling of `update_message` events editing messages (in #238), as discussed at https://github.com/zulip/zulip-flutter/pull/256#pullrequestreview-1563589723 .
=> Clean up and tighten UpdateMessageEvent tests

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/message_list.dart, lib/model/store.dart, test/api/model/model_checks.dart, test/example_data.dart, test/model/message_list_test.dart
=> Add `Reaction` class; uncomment `Message.reactions` and update on events

test/model/message_list_test.dart
This is part of #78. That issue will involve substantial refactoring on MessageListView, which makes it a good time to have tests in place.
The final commit here adds tests for all the exposed methods of MessageListView that lack them, namely `fetch`, `maybeAddMessage`, and `reassemble`. That was in fact the origin of this PR — I wrote those tests a few weeks ago as part of my draft branch for #78. (Which I've now picked back up to bring toward merge, after having held off for a while because its changes in `lib/` conflicted with other PRs and I wanted to handle the conflicts myself rather than pushing them to those PRs' authors to deal with.) The 11 preceding commits convert all the existing tests in this file to work the same way as those new tests.
In particular the first 9 of these 12 …
=> msglist test: Backfill tests for rest of model; overhaul test setup

test/api/model/events_test.dart, test/api/model/model_checks.dart, test/api/route/messages_test.dart, test/stdlib_checks.dart
As discussed at https://github.com/zulip/zulip-flutter/pull/256#discussion_r1286466765 .
=> test: Write a generic jsonEquals check and deepToJson function

lib/model/algorithms.dart, lib/model/message_list.dart, lib/widgets/message_list.dart, test/model/algorithms_test.dart, test/model/message_list_test.dart, test/widgets/message_list_test.dart
Fixes: #78
Most of the changes here are in MessageListView, making use of the tests added in #260. We also make some tweaks to the message-list widget tests, before the main commit.
=> Fetch older messages on scrolling up in message list

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/model/store.dart, test/api/model/events_test.dart, test/example_data.dart
As mentioned in the last two commits:
f662a0176 api: Add user_settings/update events, with a test for exhaustiveness
815a34730 api: Add UserSettings.twentyFourHourTime
I'm not sure about the system I've set up for type-checking the `user_settings/update` event at the edge, and verifying that all settings in the initial snapshot get updated with that event. I'd be curious to hear thoughts on that. 🙂
Related: #121
=> model: Start tracking a few `user_settings`, including `display_emoji_reaction_users`

lib/widgets/about_zulip.dart, lib/widgets/app.dart, lib/widgets/login.dart, lib/widgets/message_list.dart, lib/widgets/page.dart, lib/widgets/recent_dm_conversations.dart, test/widgets/message_list_checks.dart, test/widgets/page_checks.dart, test/widgets/recent_dm_conversations_test.dart
As discussed when we added this first test of this kind: https://github.com/zulip/zulip-flutter/pull/249#discussion_r1289230559
=> nav [nfc]: Make navigation more cleanly testable, with WidgetRoute

lib/model/binding.dart, lib/widgets/content.dart, test/model/binding.dart, test/widgets/action_sheet_test.dart, test/widgets/autocomplete_test.dart, test/widgets/clipboard_test.dart, test/widgets/content_test.dart, test/widgets/message_list_test.dart, test/widgets/recent_dm_conversations_test.dart, test/widgets/store_test.dart
We use this a lot in our tests, and its name is kind of uncomfortably
long for that.  Make it shorter.
In particular if in a test one wants the test binding object for
Flutter itself (the TestWidgetsFlutterBinding), that's spelled
`tester.binding` (where `tester` is the argument passed to the
`testWidgets` callback).  So this makes our own test binding object
be comparably accessible, as `testBinding`.
---
These cleanups originated in my draft branch for notifications, #122 / #123. There's still significant work for me to do before that branch is ready, but these seem independently helpful as we write more tests that use the global store or Flutter plugins.
=> test [nfc]: Add shorter name "testBinding" for TestZulipBinding.instance

lib/api/core.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/api/route/messages.dart, test/api/core_test.dart, test/api/route/messages_test.dart, test/example_data.dart, test/model/message_list_test.dart
=> api: Add add-reaction and remove-reaction routes

lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, test/example_data.dart
Our own data structure in PerAccountStore will be constructed from this value, and it will probably have quite a different shape; for example, we're likely to want to collapse the distinction between 1:1 and group DMs.
But now we're validating this part of the /register response and making it available to feed into those new internal data structures.
Related: #253
=> api: Add unreadMsgs in initial snapshot

lib/model/code_block.dart, lib/model/content.dart, lib/widgets/code_block.dart, lib/widgets/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
Implements the syntax highlighting for the code blocks by adapting the css styles from the [zulip web frontend](https://github.com/zulip/zulip/blob/cbde01e9e3e5e9016f36c7b48df258a3399e4818/web/styles/pygments.css) to flutter's `TextStyle`.
While parsing the HTML nodes we store the `text` along with the `className` in `CodeSpanNode`.
Both of them are strings, but `className` can probably be changed to dart enums with their conversion functions (string <-> enum), so that app doesn't unnecessarily store the short strings hogging the memory.
In the widgets we do pattern matching over the `className` to match the specific `TextStyle`. Then we use it to generate the `TextSpan`s for the RichText widget.
There is also an assumption that a span node will only have a single class associated with …
=> content: Implement syntax hightlighting for code blocks

lib/widgets/message_list.dart, test/example_data.dart, test/widgets/message_list_test.dart
=> Show dates in recipient headers, and DM interlocutors' names

test/widgets/message_list_test.dart
Since adding this test, we've repeatedly seen it break upon changes that affect how tall the messages are:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20double-fetch.20glitch.20gone.3F/near/1631114
e.g. in #245 as I was about to merge it just now.
In particular, the length of this pump for the fling-scroll has needed adjustments.  Automate that by just finding out empirically how far is far enough to trigger the fetch, and proceeding from there.
=> msglist test: Make double-fetch-glitch test robust to layout changes

assets/Noto_Color_Emoji/LICENSE, lib/licenses.dart, lib/model/content.dart, lib/widgets/app.dart, lib/widgets/content.dart, lib/widgets/message_list.dart, pubspec.yaml, test/model/content_test.dart, test/widgets/content_test.dart
Fixes: #58 
Implement parsing of the unicode emojis encoded in `<span class="emoji emoji-*">` elements and then generating direct `TextSpan`s that contains the unicode codepoint for emoji and falling back to displaying `emoji_name` in case the parsing had failed.
This PR also vendors the "Noto Color Emoji" font in COLRv1 format (4.53 MB) [that was downloaded from it's latest release](https://github.com/googlefonts/noto-emoji/releases/tag/v2.038).
As mentioned in #58 there are many alternative ways to handle the displaying of emojis. AFAIK using a font is the most efficient way to render emojis in Flutter (even for icons it prefers fonts). Using a font also provides us a way to render the emojis that are in the message content & other strings (topic/stream name). Especially on older …
=> content: implement support for unicode emojis in messages

lib/widgets/message_list.dart, lib/widgets/sticky_header.dart, test/widgets/message_list_test.dart, test/widgets/sticky_header_test.dart
In particular this gives us two features we'll want in the Zulip
message list when we go to make recipient headers appear only
where needed (#174):
* An item's header now gets built (and laid out and painted) only if
the item is actually the one at the relevant edge of the viewport
such that the stickiness comes into play.  This lets us attach a
sticky header to every message, even when it shares a recipient
header with the message that comes before it.
* An item can now (optionally) allow the header's stickiness at the
edge of the viewport to take precedence over the header's
confinement within the item's own bounds.  We'll use this to let
the header stay pinned when scrolling between items that share a
recipient header.
=> sticky_header: Rewrite sticky headers completely; write tests

lib/widgets/app.dart
It's strange that iOS really doesn't seem to know what to do with 'sans-serif' here. Nor "SF Pro", "SF-Pro", nor any obvious variation on that, even though it's supposedly the system font:
https://developer.apple.com/fonts/
But a GitHub comment popped up a few hours ago (linked in the added code), and that's the first thing I've found that seems to work, as a clear pointer to the default system font. Shrug.
Later, we'll want to use Sorce Sans 3 for almost all the text in the app. But we'll want to take more care with that than I have bandwidth for right now (around it being a variable-weight font); see discussion:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20text.20all.20weird/near/1633648
Fixes: #289
=> ui: For boring, non-emoji font, use one that iOS recognizes

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/narrow.dart, test/api/model/events_test.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/model/message_list_test.dart, test/model/narrow_test.dart, test/stdlib_checks.dart
This contains commits cherry-picked from other PRs:
From my f59da2ace5201d4139a682c64f7428bd80c2ef46 / #286:
```
test [nfc]: When deepToJson returns Map, don't lose its string-keyed type
```
From @sirpengi's 00bc224853fce8c9eef61ed3ccc479c02ab1d4ba / #287 (thanks @sirpengi!):
```
model: Add DmNarrow.withUser helper
```
Related: #253
=> model: Use enum for Message.flags[]

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/store.dart, lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/profile.dart, test/api/model/model_test.dart, test/example_data.dart, test/widgets/profile_page_checks.dart, test/widgets/profile_test.dart
Added profile screen with user information and custom profile fields, linked from sender name and avatar in message list.
Support in initial_snapshot and models for the related `RealmDefaultExternalAccounts` and `CustomUserProfileFields` also added, as event handling for `custom_profile_fields`.
User presence (#196) and user status (#197) are not yet displayed or tracked here.
Fixes: #195
=> profile: Implement profile screen for users

lib/api/model/model.dart, lib/api/model/model.g.dart, lib/api/model/reaction.dart, lib/api/model/reaction.g.dart, lib/model/message_list.dart, test/api/model/events_test.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/api/model/reaction_test.dart, test/example_data.dart, test/model/message_list_test.dart
I thought I'd check in with my progress toward keeping an efficient data structure to support the list of reaction buttons on a message in the message list. 🙂
As discussed [in chat](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20view-model.20for.20aggregated.20reactions/near/1624769), this goes directly on `Message` instances.
In this revision, the data structure retains a raw, "unaggregated" list, like the list it gets from the server. That doesn't have to stay, since it takes up space, but it does make it efficient to count reactions for `UserSettings.displayEmojiReactionUsers`, and it supports a nice and efficient `Reactions.toJson` in case the app starts requiring that.
There are TODOs in the tests, but I'll get to those. 🙂
Related: #121
=> model: Add `Reactions` data structure, for efficient access in UI

lib/model/message_list.dart, lib/widgets/message_list.dart, test/model/message_list_test.dart, test/widgets/message_list_test.dart
Fixes: #174 
Screenshot with recipients changing:
Screenshot with the date changing:
=> msglist: Share recipient headers across messages

lib/model/message_list.dart, lib/widgets/message_list.dart, test/model/message_list_test.dart, test/widgets/message_list_test.dart
=> msglist: Show sender only when needed

analysis_options.yaml
Docs:
https://dart.dev/tools/linter-rules/no_literal_bool_comparisons
---
I noticed this from https://github.com/zulip/zulip-flutter/pull/305#discussion_r1336338055 .
It's possible we should make a pass of enabling a swath of the same rules that are applied in the Flutter repo. But it looks like so far this is only the second one that's come up that we want to enable (that wasn't already through the `include` we got from the `flutter create` template); so as long as those are few and far between, that's probably not worth it.
=> lint: Enable no_literal_bool_comparisons

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/model/message_list.dart, lib/model/store.dart, test/api/model/events_test.dart, test/example_data.dart, test/model/message_list_test.dart, test/stdlib_checks.dart
We'll need to handle these events in the upcoming unread-messages model, for #253.
This PR also includes a draft commit:
```
wip msglist: Handle update_message_flags events in model
```
That would be helpful toward #79, but I'm really unsure about the efficiency of using `_findMessageWithId` (binary search) in this hot codepath. (The most common call will be for messages getting marked as read on scroll.) If that turns out to be OK, I can give that commit the tests it needs, and unmark as draft.
=> api: Add update_message_flags events

assets/l10n/app_en.arb, lib/api/core.dart, lib/api/exception.dart, lib/model/localizations.dart, lib/widgets/action_sheet.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/dialog.dart, lib/widgets/lightbox.dart, lib/widgets/login.dart, lib/widgets/message_list.dart, test/api/core_test.dart, test/widgets/action_sheet_test.dart, test/widgets/autocomplete_test.dart, test/widgets/clipboard_test.dart, test/widgets/content_test.dart
I've gone through the code and found any hard-coded strings or other `TODO(i18n)` markers and wired them up to the localization framework.
For some more complicated translations that didn't have inherit access to a `BuildContext` (exception messages, or certain widget labels and tooltips) I opted for a pattern of attaching methods that take the `ZulipLocalizations` object so they could perform the translation when needed.
=> Localization sweep

build.yaml, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.g.dart, lib/api/model/reaction.g.dart, lib/api/route/account.g.dart, lib/api/route/events.g.dart, lib/api/route/messages.g.dart, lib/api/route/realm.g.dart, lib/api/route/users.g.dart, lib/model/compose.dart, lib/model/database.g.dart, lib/model/internal_link.dart, lib/model/internal_link.g.dart, lib/model/narrow.dart, lib/model/store.dart, lib/widgets/content.dart, test/example_data.dart, test/model/compose_test.dart, test/model/internal_link_test.dart, test/model/narrow_test.dart
Adds support to recognize internal UI links, such as links to other streams or topics.
=> Handle Zulip internal links

lib/widgets/content.dart, test/widgets/content_test.dart
This PR is built on top of #305 
Intercepts link navigation to run through `parseInternalLink` (from #305)  and redirects internal links to their respected narrows.
Fixes: #73
=> Integrate internal links in message contents

lib/api/model/events.dart, lib/api/model/model.dart, lib/api/model/narrow.dart
Calling just `int.parse(s)`, without a `radix:` argument, invokes a special behavior where `int.parse` not only accepts decimal strings like "42", but also hexadecimal strings like "0x2a".
That's a bit unexpected.  In any case it's definitely not something we want when interpreting any part of the Zulip API.
Fix the one place we had this in our own code.  There remain two places it appears in the code generated by `json_serializable`; mark those with TODO comments.  It'd be nice to fix those too, but realistically this quirk is unlikely to ever cause a problem, so it's not worth a lot of effort to resolve.
(Note that this doesn't affect the bulk of places we have an int in the API types, because most of those are handled by jsonDecode before the `json_serializable`-generated code ever …
=> api: Fix usage of int.parse that implicitly accepts hexadecimal

lib/api/model/events.dart, lib/api/model/initial_snapshot.dart, lib/model/algorithms.dart, lib/model/narrow.dart, lib/model/store.dart, lib/model/unreads.dart, test/api/model/events_test.dart, test/api/model/initial_snapshot_test.dart, test/model/algorithms_test.dart, test/model/unreads_checks.dart, test/model/unreads_test.dart
Contains my current revision of #299.
This is still in progress, but thought I'd check in with what I have so far, and see if it's going in the right direction. 🙂
=> model: Add Unreads model, for tracking unread-message counts

lib/model/narrow.dart
The list of these constructors has been growing. This tweaks a couple of aspects that I happened to notice when rereading these as part of merging #304 just now.
---
narrow [nfc]: Factor out DmNarrow.withOtherUsers; doc constructors more
---
narrow [nfc]: Strength-reduce implementation of DmNarrow.withUser
No need to allocate a `Set` for this, as it's always either
just one or two elements.  This version should be a bit more
efficient if we find ourselves constructing many of these.
=> narrow [nfc]: Small tweaks to DmNarrow constructors

ios/Podfile.lock, lib/api/route/notifications.dart, lib/firebase_options.dart, lib/main.dart, lib/model/binding.dart, lib/model/store.dart, lib/notifications.dart, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Podfile.lock, pubspec.lock, pubspec.yaml, test/api/route/notifications_test.dart, test/example_data.dart, test/model/binding.dart, test/model/store_test.dart, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
~~This PR is stacked atop #319.~~ → Rebased now that #319 is merged.
This implements part of #320.
To make an end-to-end demo, we also listen for notification messages, and just print them to the debug log.
=> notif: Get token on Android, and send to server

lib/api/notifications.dart, lib/api/notifications.g.dart, lib/notifications.dart, test/api/notifications_test.dart
This PR is stacked atop #325, and makes the next step toward #320/#122.
=> notif: Parse notification messages, on Android

lib/widgets/recent_dm_conversations.dart
=> RecentDmConversationsPage: Fix RTL layout problem

android/app/build.gradle
This is the same minimum we have on the zulip-mobile RN app.
We've had it at the Flutter default of 19, aka Android 4.4 KitKat. But we're now beginning to bump into the need for "multidex" support:
https://docs.flutter.dev/deployment/android#enabling-multidex-support
at least in debug builds.  The simplest way to do that is to have minSdkVersion at 21 or higher; which is a good prompt for us to bump it to the version we were going to want to bump it to anyway.
=> android: Bump minSdkVersion to 24, aka Android 7 Nougat

lib/model/message_list.dart, lib/widgets/message_list.dart, test/flutter_checks.dart, test/widgets/message_list_test.dart
This PR introduces unread markers with animations whenever the read state changes for a message. Bundled into this PR is also:
- Associated integration tests and docs on obtaining performance metrics from a physical device that I used to confirm the performance of the animation being used
- A fix for animation state being lost when the number of items in the message list changes. This involved adding a unique key to every message as well as providing a `findChildIndexCallback` to `StickyHeaderListView.builder`.
Discussion related to design of this on CZO: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20unread.20marker
Fixes: #79
=> Unread markers

lib/model/binding.dart, lib/notifications.dart, test/model/binding.dart, test/notifications_test.dart
This completes the core functionality of showing notifications on
Android, #320.
Sadly this does not work very well if the app isn't running at all:
e.g., if you terminate the app by swiping it away in the app switcher.
In that case the notification can be quite a bit delayed.
But fixing that seems likely to require some deeper debugging, and
getting our hands into Java or Kotlin code for I think the first time
in zulip-flutter.  So we'll deal with that as a followup issue, #342.
Details there.
Fixes: #320
=> notif: Handle when app in background, too (on Android)

docs/integration_tests.md, integration_test/perf_driver.dart, integration_test/unreadmarker_test.dart, pubspec.lock, pubspec.yaml
This PR was split off from #317 and is based on that branch. Also adds documentation on how to gather performance metrics on physical devices.
=> Add integration test of _UnreadMarker animation

lib/api/model/model.dart, lib/api/model/narrow.dart, lib/api/route/messages.dart, lib/api/route/messages.g.dart, test/api/route/messages_test.dart
This PR adds all the api routes related to marking messages as read.
The complexities around the response of https://zulip.com/api/mark-all-as-read are ignored as it is deprecated (it is also ignored in zulip-mobile). On an examination of `lib/api/core.dart` it doesn't look like we check the value of the `result` field (where the status code is 200) so if the server returns `partially_completed` for the affected FLs it doesn't raise any errors (although we would treat the operation as completed).
Fixes part of #130
=> api: Mark messages as read (updateMessageFlags and updateMessageFlagsForNarrow)

lib/notifications.dart, lib/widgets/app.dart, pubspec.lock, pubspec.yaml, test/example_data.dart, test/model/binding.dart, test/notifications_test.dart, test/widgets/store_checks.dart
Still only on Android; iOS support for notifications in general is coming next.
Fixes: #123
=> Navigate to conversation on tapping notification

lib/api/route/messages.dart, test/api/route/messages_test.dart
This pr was split off from #361.
Also fixes part of #130
=> api: Mark messages as read (markAllAsRead, markStreamAsRead, markTopicAsRead)

test/api/route/messages_test.dart
Noticed this pattern here:
https://github.com/zulip/zulip-flutter/pull/363#discussion_r1382298180
This fixes all the existing cases of it.
=> test [nfc]: Cut redundant isNotNull checks before isA

lib/widgets/content.dart, pubspec.lock, pubspec.yaml, test/widgets/content_test.dart, test/widgets/profile_test.dart
`url_launcher` plugin now supports the desired behavior, which is using Android Custom Tabs, so we don't need the workaround of opening the links in external browser anymore, thus removed them.
Upstream PR:
https://github.com/flutter/packages/pull/4739
Fixes #279
=> content: Open links in-app on Android

assets/l10n/app_en.arb, lib/api/model/narrow.dart, lib/model/internal_link.dart, lib/model/unreads.dart, lib/widgets/message_list.dart, test/model/unreads_test.dart, test/widgets/message_list_test.dart
This is proceeded by #361 and #363, which both provide api routes necessary for functionality here. This implements the manual "Mark as Read" button that allows the user to explicitly mark messages in their current narrow as read.
This series of PRs fixes: #130
---
Design made to match figma spec at https://www.figma.com/file/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?type=design&node-id=132-9684&mode=design&t=jJwHzloKJ0TMOG4M-0
=> Mark as read

lib/widgets/recent_dm_conversations.dart, lib/widgets/unread_count_badge.dart, pubspec.lock, pubspec.yaml, test/widgets/unread_count_badge_checks.dart, test/widgets/unread_count_badge_test.dart
With an experiment in golden tests. As Greg pointed out in today's weekly mobile-team call, golden tests might not provide much extra value. But anyway, here's an experiment with them, in case it's helpful now or for our future testing needs. 🙂
cc @sirpengi, who might like to use this for #187
=> widgets: Pull out reusable UnreadCountBadge widget; grow support for stream colors

lib/widgets/message_list.dart
This takes advantage of some of StickyHeaderListView's default behavior (inherited from ListView). From the doc on ListView:
https://api.flutter.dev/flutter/widgets/ListView-class.html
> By default, ListView will automatically pad the list's scrollable
> extremities to avoid partial obstructions indicated by
> MediaQuery's padding. To avoid this behavior, override with a zero
> padding property.
The code changes here are just to arrange for that default behavior to help us out: we let the real height of the bottom inset propagate down to the StickyHeaderListView, with the MediaQuery mechanism.
Fixes: #263
=> msglist: Have content pad bottom inset when the compose box isn't shown

lib/widgets/app.dart, lib/widgets/content.dart, lib/widgets/lightbox.dart, lib/widgets/login.dart, lib/widgets/recent_dm_conversations.dart, test/widgets/content_test.dart
Doing our planned M3 migration (#225) gives us a convenient pattern that I'm hoping will make it easier to follow the Figma spec in a certain way. Details in the last commit.
| --- | --- |
| ![image](https://github.com/zulip/zulip-flutter/assets/22248748/52f2efcc-4f5b-4350-b619-0636760acc99) | ![image](https://github.com/zulip/zulip-flutter/assets/22248748/9f9fb532-1d8a-4c6c-a9c1-8653c84ed27a) |
Fixes: #225
=> ui: Fix some design deviations in the recent DMs page; migrate to Material Design 3

lib/widgets/message_list.dart
Thanks @chrisbobbe for the report: https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20Mark-as-read/near/1679769
* Adjusted border radius to 7
* Restyled text per recommendations, specifying line height, and adjusting button height to be explicit (used 48px in this case, to match button target recommendations)
New screenshot:
=> Adjust MarkAsReadWidget text to be bolder, use Source Sans 3

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/store.dart, test/api/model/events_checks.dart, test/api/model/events_test.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/example_data.dart, test/model/store_test.dart
Clean up `Subscription` and `ZulipStream`: make `Subscription` extend `ZulipStream` and move fields around so only `Subscription` specific fields are in the class definition. Also handles the events `subscription/op:add`, `subscription/op:remove`, and `subscription/op:update`.
Fixes part of #187
=> Subscription api events

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
Screenshots coming soon. (Both sets of screenshots were made with #399 in the branch, for no particular reason except to avoid showing an unrelated bug that might be distracting.)
Fixes: #400
Fixes: #401
=> msglist: Add end-of-feed whitespace; use background color from Figma

lib/widgets/app.dart, lib/widgets/icons.dart, lib/widgets/inbox.dart, lib/widgets/message_list.dart, lib/widgets/subscription_list.dart, test/widgets/subscription_list_test.dart
Adds a Subscriptions page showing the user's subscribed streams. Out of scope are collapsible topics and the ability to browse to all streams. There was no design spec for the situation where the user has no subscriptions so implemented a simple text notice here.
Thanks @chrisbobbe for the color helpers. I've found a lot that could be shared between this and the inbox code in #381 -- besides the collapsible bit, the design is exactly the same save the `fontSize` here is 18 instead of 17 in the inbox. I think we have a lot of space to consolidate design in the future.
Figma design: https://www.figma.com/file/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?type=design&node-id=171-12359&mode=design&t=4d0vykoYQ0KGpFuu-0
Fixes #187
=> Subscriptions page

ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist, ios/Runner/Runner.entitlements, lib/firebase_options.dart, lib/model/binding.dart, lib/model/store.dart, lib/notifications.dart, test/model/binding.dart, test/model/store_test.dart, test/notifications_test.dart
Fixes #321.
---
There's one notable limitation in the functionality here, which I've filed as:
* #408 
Also the permissions prompt comes annoyingly early:
* #324 
We can fix those in the Beta 2 period.
---
I've manually tested this with my own Zulip dev server (running main), and it works. Testing notifications with a dev version of the client is kind of a pain, unfortunately (even after the simplifications I made to it this month):
https://github.com/zulip/zulip-mobile/blob/main/docs/howto/push-notifications.md#ios
so for review, given the impending Beta 1, I think it's best to skip that for now — for manual testing we can just rely on what I've done already, and on the next alpha release.
---
Screenshot of the notifications in Notification Center:
(There were also messages with content …
=> notif: Support iOS!

lib/widgets/inbox.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart
This fixes all the safe-area bugs I noticed in a sweep through the UI, all in the style of option 2 described here: https://github.com/zulip/zulip-flutter/issues/339#issuecomment-1781640628
Fixes: #339
=> ui: Sweep through and fix safe-area bugs

ios/Podfile.lock, macos/Podfile.lock, pubspec.lock, pubspec.yaml
deps: Upgrade Flutter to latest main, 3.17.0-16.0.pre.23
---
deps: Upgrade packages within constraints (flutter pub upgrade)
Also update the CocoaPods lockfiles.  This required some fiddling;
ultimately the commands were:
( cd ios && pod update sqlite3 Firebase/CoreOnly )
( cd macos && pod update sqlite3 Firebase/CoreOnly )
flutter build ios --config-only
flutter build macos --config-only
Without the `pod update` commands, there were various misleading
error messages, some of them claiming the problem was that one
pod required a higher minimum deployment target than another.
---
deps: Upgrade packages to latest, namely package_info_plus
This is the result of `flutter pub upgrade --major-versions`.
(Plus `flutter build ios --config-only`
and `flutter build macos --config-only`, but those …
=> Upgrade Flutter and packages

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
=> Unconditionally add ApiNarrowIsUnread to markNarrowAsRead

test/example_data.dart, test/notifications_test.dart
Like we did for message IDs in 13e54f60b.
This time there aren't any (or anyway I didn't find any) call sites where we could simply remove a `userId` argument and the test would still work. I've made the one simplification to a test that seemed very easy and minimal.
=> test: Generate random, increasing user IDs for example data by default

assets/l10n/app_en.arb, lib/widgets/message_list.dart, test/widgets/message_list_test.dart
This is built on top of #416.
This PR updates the DM recipient headers to the new style. Text style and spacing was taken from the same sources as #416:
- https://www.figma.com/file/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=538%3A20849&mode=dev
- https://github.com/zulip/zulip-mobile/issues/5511
But given there were no mockups that included a DM recipient header the style used here also looked to how web renders these headers (in particular the color to use for the background, and icon to use for display).
Here showing behavior when the system requests a larger font:
=> Redesigned DM recipient headers

lib/model/content.dart, lib/widgets/action_sheet.dart, lib/widgets/emoji_reaction.dart, lib/widgets/message_list.dart, test/example_data.dart, test/widgets/action_sheet_test.dart, test/widgets/emoji_reaction_test.dart
Fixes #121.
Fixes #125.
| Without [plain-text-emojis setting](https://zulip.com/help/emoji-and-emoticons#change-your-emoji-set) | With plain-text-emojis setting |
| --- | --- |
| <img width="552" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/23e470c8-6b76-4e8b-9af0-c066bc3fd53d"> | <img width="552" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/3f900753-e29c-4185-9be6-b6dbe1d74786"> |
=> msglist: Show message reactions; support reacting (with 👍, or to join in others' reactions)

lib/widgets/content.dart
Fixes #430.
| --- | --- |
| ![9BCFC81E-C98D-4759-BF6D-50E08DA70075](https://github.com/zulip/zulip-flutter/assets/22248748/a721dfb1-cba5-4404-9472-e231ab7cbef9) | ![F7119704-62FC-4A27-B25F-36563BFD0448](https://github.com/zulip/zulip-flutter/assets/22248748/a12c85dc-3b59-4864-ac00-419bc772b3d9) |
=> content: Stop accidentally dropping paragraph text style in user mentions

assets/l10n/app_en.arb, lib/widgets/message_list.dart, test/widgets/message_list_test.dart
This PR is built on top of #426 
Fixes #411
=> Recipient header date format

assets/Noto_Color_Emoji/LICENSE, lib/widgets/emoji_reaction.dart, pubspec.yaml
- Bundle Noto Color Emoji, with a TODO to not bundle it on iOS (I'll file an issue for that TODO)
- I'll say this fixes #404.
- The "Licenses" page works again; this fixes #435
- Use Noto Color Emoji on Android (but not iOS) for reaction chips
- I'll file an issue to use it for text elsewhere (on Android). But using it for reaction chips is easier and more urgent.
Screenshots from the office Android device (Samsung Galaxy S9 running Android 9):
(ignore/pardon the battery-life popup in the "After" screenshot)
| --- | --- |
| ![image](https://github.com/zulip/zulip-flutter/assets/22248748/737861fe-56d5-4b9d-b2a9-c88fef2182b2) | ![image](https://github.com/zulip/zulip-flutter/assets/22248748/b396eedb-f589-40f3-b6de-a0c1f1cdab91) |
Fixes: #404
Fixes: #435
=> Add Noto Color Emoji back again; use it in message-list reaction chips on Android

lib/widgets/message_list.dart, lib/widgets/text.dart, lib/widgets/unread_count_badge.dart, pubspec.lock, pubspec.yaml, test/flutter_checks.dart, test/widgets/text_test.dart
Upstream Flutter (in flutter/flutter@c6741614041 ) changed `flutter/material.dart` to additionally export many types from `dart:ui`. This caused a lot of our imports to trigger an analysis warning of `unnecessary_import`.
Please make sure you update your Flutter SDK after pulling in these changes!
=> Remove unnecessary imports of dart:ui

lib/api/route/messages.dart, lib/model/store.dart, lib/widgets/compose_box.dart, test/api/route/messages_test.dart, test/model/store_test.dart
PR is built on top of #447 in order for tests to pass.
Adds a new flag introduced in https://github.com/zulip/zulip/pull/28204 .
Fixes: #440
=> New `read_for_sender` flag when sending a new message

assets/l10n/app_en.arb, lib/api/core.dart, lib/api/exception.dart, test/api/core_test.dart, test/api/exception_checks.dart
If the server's response is malformed, as with the server issue that led to #383, the existing logging is unhelpful for working out what the problem is, even in debug: we learn what request failed, but not where in the response the misparse was.
When that issue happened, I debugged it with a cruder version of this change, just augmenting this `catch` block to print the exception and its stack trace.  But we can do better, using the magic of Error.throwWithStackTrace.
=> api: On parse failure, include details in exception

lib/widgets/sticky_header.dart, test/flutter_test_config.dart, test/widgets/sticky_header_test.dart
Fixes: #327
Also enable a bit of test config that I ended up not relying on, but that should be enabled in any case.
=> sticky_header: Fix hit-testing of header

lib/model/store.dart, lib/widgets/message_list.dart, lib/widgets/store.dart, test/example_data.dart, test/model/store_test.dart, test/model/test_store.dart
=> store: Replace event queue on expiry

pubspec.lock, pubspec.yaml, test/widgets/content_test.dart
By saying `tester.tapAt(find.text('hello'))`, we had been aiming at the center of the Text widgets, and expecting that to hit the recognizer we've put on the span, even though the widget is much wider than the span and the latter doesn't reach the former's center. Effectively we were relying on the presence of issue #214.
But with an upstream change yesterday:
* https://github.com/flutter/flutter/pull/140621
* https://github.com/flutter/flutter/issues/43400
such a tap no longer hits the span.  That broke these tests.
To fix them, aim the taps near the start of the widget instead.
---
Also bump the Flutter version to require that upstream change, fixing #214.
Fixes: #475
Fixes: #214
=> content test: Aim taps on links more precisely at the text

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/xml/network_security_config.xml
This is copied from the corresponding config in zulip-mobile, which was added in the following commit:
https://github.com/zulip/zulip-mobile/commit/85c3a716a7bbf00c936beaf34bc84a0e6bf5c885
Unlike in zulip-mobile, though, we don't need any adjustments in debug (or profile) builds, because we don't use the `android:usesCleartextTraffic` attribute which this would clobber.
(React Native debug builds reach out to the development host over cleartext HTTP in order to support hot updates; but the Flutter development tools have the host contact the app instead, using the Dart VM protocol.  It's also not clear that any Dart libraries respect the `android:usesCleartextTraffic` flag anyway.)
Fixes: #461
=> android: Trust user-supplied CAs, except on known servers

lib/model/message_list.dart, lib/widgets/message_list.dart, test/model/message_list_test.dart
Fixes: #173
This is a draft because it needs tests and also some cleanups in the code. But from a user perspective it already works great — so I'm sharing this in order to get feedback on the visual design. As mentioned at https://github.com/zulip/zulip-flutter/issues/173#issuecomment-1871744164 , I don't see an existing design for this in Figma, so for a first draft I've taken what's in web and adapted it.
* In web the dates have color `hsl(0deg 0% 15% / 75%)`, which is the same as the dates in the recipient headers. Here, our dates in recipient headers are lighter than that: they're black with 40% alpha. So I used that color for these, though it makes the dates lighter than in web. @terpimost do you think this is the color we want?
* In web the dates are slightly smaller in the date …
=> Add date separators

lib/model/content.dart, lib/widgets/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
Fixes: #359
See discussion on visual design: https://chat.zulip.org/#narrow/stream/48-mobile/topic/TeX.20in.20Flutter.20app/near/1710839
Screenshots (of [these messages](https://chat.zulip.org/#narrow/stream/7-test-here/topic/math/near/1712027)):
| This PR | Zulip web |
| --- | --- |
| ![image](https://github.com/zulip/zulip-flutter/assets/28173/413b6652-1e7c-4d6c-bf50-4e23fdb4dea8) | ![image](https://github.com/zulip/zulip-flutter/assets/28173/08a7f7c8-20bf-499f-a30e-3915a774d983) |
=> content: Handle KaTeX math, with a rough preview

lib/model/message_list.dart, test/model/message_list_test.dart
Fixes: #479
Also update some tests that probably should have been updated in #469.
---
Before:
After:
=>     msglist: Let recipient header overlap date, just like a message

ios/Podfile.lock, macos/Podfile.lock, pubspec.lock
I ran `flutter pub upgrade`, then updated the CocoaPods lockfiles. This required some fiddling; ultimately the commands were:
( cd ios && pod update sqlite3 )
( cd macos && pod update sqlite3 )
flutter build ios --config-only
flutter build macos --config-only
Without the `pod update` commands, there was a misleading error message claiming the problem was that one pod required a higher minimum deployment target than another. Much like in 0dbc0c06d.
I also ran `flutter pub upgrade --major-versions`, but it didn't make any changes.
=> deps: Upgrade packages (`flutter pub upgrade`)

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
~~Rebased on top of #447 as that impacted tests passing.~~
As a foundation for my work on #170, I needed to update the layout of messages so that the star icon could be positioned in the appropriate place. This also enables the placement of future decorations to messages (like markers for moved/edited) and moves us closer to #157 
Screenshot of the new message layout:
Because the new layout is more compact, this caused the `basic` test of the `fetch older messages on scroll` group to fail as a second request for new messages is triggered. This is due to the first batch of new messages not being tall enough to be beyond the threshold (see `kFetchMessagesBufferPixels` in `lib/widgets/message_list.dart`) for loading another batch. A proper fix to this would be to tweak the threshold …
=> msglist: Update layout in messages

pubspec.lock, pubspec.yaml
I also ran the usual two followup commands:
$ flutter build ios --config-only
$ flutter build macos --config-only
and nothing changed.
=> deps: Update Flutter to latest main, 3.19.0-9.0.pre.169

lib/widgets/message_list.dart, lib/widgets/sticky_header.dart, test/widgets/message_list_test.dart, test/widgets/sticky_header_test.dart
This is the first of several PRs leading us to #80 and #82, opening the message list at an anchor other than the latest message in history.
For this PR, the main work is to lift one of the simplifying assumptions I originally made for an MVP of the `sticky_header` library, allowing the SliverStickyHeaderList to be a sliver that counts backward in the enclosing ScrollView rather than forward.
We also rearrange some things in how MessageList builds the list, in order to exercise that new flexibility and to get closer to how we'll want things when implementing #80 and #82.
sticky_header: Handle GrowthDirection.reverse
This resolves the last of the "TODO dir" comments in this library.
We had originally written this library to rely on the assumption
that `constraints.growthDirection` was …
=> anchors 1/n: Handle GrowthDirection.reverse in sticky_header

lib/model/content.dart, lib/widgets/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
Fixes: #192
An unresolved issue in this PR is that headers at the beginning of a message should not have a top margin. See from
https://github.com/zulip/zulip/blob/main/web/styles/rendered_markdown.css :
```css
/* Headings: Ensure that messages that start with a heading don't have
a weirdly blank area at the very start of the message. */
& h1:first-child,
h2:first-child,
h3:first-child,
h4:first-child,
h5:first-child,
h6:first-child {
margin-top: 0;
}
```
We have an open issue #162 to handle content layout where this should be addressed in the future.
Screenshot from android:
=> Implement h1-h5

lib/widgets/app.dart, lib/widgets/content.dart, lib/widgets/emoji_reaction.dart, lib/widgets/inbox.dart, lib/widgets/message_list.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, lib/widgets/text.dart, lib/widgets/unread_count_badge.dart, test/flutter_checks.dart, test/widgets/text_test.dart
(As usual please pardon the battery-life indicator in some of these screenshots. Ugh.)
In the second set of screenshots, note that the 🤯 emoji is made to look the same in the message list and the reaction chip. (This is taken on the office Android device.)
| --- | --- |
| ![image](https://github.com/zulip/zulip-flutter/assets/22248748/aab7290e-c7c0-4ce4-8ad5-28ae1c7f2af7) | ![image](https://github.com/zulip/zulip-flutter/assets/22248748/a66318aa-e1fb-42ac-80d4-cbe171c730df) |
| ![image](https://github.com/zulip/zulip-flutter/assets/22248748/63221a9b-1e66-4319-8f9e-e823b5072a75) | ![image](https://github.com/zulip/zulip-flutter/assets/22248748/e0e76e4a-a275-4578-8eec-39326d982be3) |
Fixes: #294
Fixes: #438
=> text: Apply "Source Sans 3" and (on Android) "Noto Color Emoji" widely across the app

lib/widgets/content.dart, lib/widgets/text.dart
Also format `**bold text**` using weightVariableTextStyle, fixing #499, and update a comment to point to #500.
| --- | --- |
| ![image](https://github.com/zulip/zulip-flutter/assets/22248748/a0b927a5-eef5-4eb5-9544-a46315bd083f) | ![image](https://github.com/zulip/zulip-flutter/assets/22248748/52ec3e12-bbf5-44f9-9bb7-2086310c3e3a) |
Fixes: #498
Fixes: #499
=> content: Fix **`bold code`** rendering with regular weight

lib/api/core.dart, lib/api/route/messages.dart, lib/widgets/content.dart, test/api/core_test.dart, test/api/route/messages_test.dart, test/widgets/content_test.dart
Revises: #450
Fixes: #406
Fixes: #460
=> api: Send simple User-Agent header

lib/model/code_block.dart, lib/model/content.dart, test/model/content_test.dart
Fixes: #497
The first two commits here are by @chrisbobbe, taken from #503. The later commits go in the same direction for checking a class list is empty, and then handle the remaining couple of places that are a bit trickier, applying regexps to `className` to cover the different possibilities.
=> Cut inefficient CssClassSet out of content parsing

test/widgets/message_list_test.dart
These already exist as late variables at the top of `main`, and at each of these lines they've already been set by the setupMessageListPage helper to exactly the same values found here.
=> msglist test [nfc]: Cut some redundant per-case store and connection locals

lib/widgets/emoji_reaction.dart
If we don't like the refactor in the second commit, we can drop it and #441 will still be fixed. 🙂
| --- | --- |
| <img width="449" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/59cd3f00-e2e0-4867-ade7-a361854cb11d"> | <img width="449" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/45948e16-87f9-451c-8cea-07ed49a575c5"> |
Fixes: #441
=> reactions: (Actually) make text-emoji chip's height consistent with others

lib/model/content.dart, lib/widgets/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
Rebased on top of #511 for new style of content tests.
Fixes: #193 
```
[4-64ecbf0935ea5.png](/user_uploads/57965/lBu8Ccyg4Ex0wo07RZdYnpKg/4-64ecbf0935ea5.png)
[5-64ecbc38c4267.png](/user_uploads/57965/MBk-n_Ok52kDQ_vZzrKJm4oQ/5-64ecbc38c4267.png)
[6-64ecbf34264c2.png](/user_uploads/57965/PWZuqtSLFvyQDQkJBXEJmuDY/6-64ecbf34264c2.png)
[7-64ecb1c909b78.png](/user_uploads/57965/bLx4viPDcyoingbDSiNvg3V5/7-64ecb1c909b78.png)
```
| Flutter |  Web  |
| ------ | ------ |
| <img src="https://github.com/zulip/zulip-flutter/assets/98299/f33f2d7d-8bb8-4439-9038-d6fd65bab038" width=300 /> | <img src="https://github.com/zulip/zulip-flutter/assets/98299/7990d4a0-1f3b-4889-847b-41de1c3eddf8" width=300 /> |
```
[4-64ecbf0935ea5.png](/user_uploads/57965/pHPfjDy_9FBEVSu5rnx4yBVJ/4-64ecbf0935ea5.png) …
```
=> Multiple Images

lib/notifications.dart, test/notifications_test.dart
This is necessary (on Android 13+) in order to be able to actually show a notification in the UI.
Fixes: #520
=> notif android: Request permission at startup

README.md, ios/Podfile.lock, macos/Podfile.lock, pubspec.lock, pubspec.yaml, tools/lib/cli.sh, tools/lib/git.sh, tools/upgrade
The main commit is:
---
tools/upgrade: Add script to upgrade our dependencies
This leaves open one significant gap, which is upgrades to
our Flutter version.  I'm leaving that for another time
because it involves making changes in another repository
(the user/developer's Flutter checkout), and so requires care
to avoid clobbering any local changes they have there.
For updating the CocoaPods lockfiles after an upgrade to our
Dart dependencies in pubspec.lock, we'd previously been making
an actual build, or using `flutter build ios --config-only`
(and ditto for macOS) to strip that process down somewhat; but
then we've sometimes also had to run `pod update POD...` to
unwedge CocoaPods on certain pods, as in 105727e15 and several
later commits like 0dbc0c06d and most recently 1b0061e42.
That …
=> deps: Upgrade Flutter, pods, and packages; automate upgrades more

lib/api/route/account.dart, lib/api/route/realm.dart, lib/model/store.dart, lib/widgets/login.dart, test/api/fake_api.dart, test/example_data.dart, test/model/store_checks.dart, test/model/store_test.dart, test/model/test_store.dart, test/widgets/login_test.dart
Unlike almost everywhere else in our code, this was invoking the `ApiConnection.live` constructor directly and therefore wasn't possible to write tests for. Prompted by https://github.com/zulip/zulip-flutter/pull/519#pullrequestreview-1881464375 , fix that, and write a first test.
It'd be good to use this new capability in order to write more tests for the login UI, and I've left some TODO comments pointing at those; but this is as much as I had time to get to today, and it's enough to unblock writing tests for new functionality in this area such as #519.
=> Make login flow testable, and start testing it

lib/model/compose.dart, lib/model/database.dart, lib/model/database.g.dart, lib/model/internal_link.dart, lib/model/store.dart, lib/widgets/action_sheet.dart, lib/widgets/app.dart, lib/widgets/content.dart, lib/widgets/emoji_reaction.dart, lib/widgets/inbox.dart, lib/widgets/message_list.dart, lib/widgets/profile.dart, lib/widgets/recent_dm_conversations.dart, test/example_data.dart, test/model/compose_test.dart, test/model/content_test.dart, test/model/internal_link_test.dart, test/model/store_test.dart, test/model/test_store.dart, test/widgets/content_test.dart, test/widgets/message_list_test.dart, test/widgets/store_test.dart
Currently we insert `Account` records into the database on login, and never update them. We'll need to update them in order to do:
* #458
* #322
and other things.
This branch doesn't yet make any new changes in the database, but it does some refactoring on PerAccountStore and friends which we'll need in order to do so. It also takes care of various things that became noticeable along the way:
* adding some handy getters like `store.selfUserId` and `self.realmUrl`;
* fixing where we'd been crashing if the server somehow sent us an invalid URL (one `Uri.parse` rejects) in the HTML or as a user's avatar;
* adding more content-widget tests, to test that latter change, and using the facilities recently added in #511.
The main commit is this one near the beginning:
---
store [nfc]: Keep just …
=> Prepare for updating accounts in database

lib/notifications.dart
This fixes part of #528, following the suggestion @n-92 made here:
https://github.com/zulip/zulip-flutter/issues/342#issuecomment-1874716442
Even with this change, notifications still don't yet work on Android in release builds.  But after this change, when the app wasn't in the foreground, they get farther than before.  Specifically they get just as far as they get, with or without this change, when the app was in the foreground.  Details here:
https://github.com/zulip/zulip-flutter/issues/528#issuecomment-1960646800
=> notif: Add `vm:entry-point` pragma to _onBackgroundMessage

assets/l10n/app_en.arb, lib/model/content.dart, lib/widgets/content.dart, test/flutter_checks.dart, test/model/content_test.dart, test/widgets/content_test.dart
TODO tests, but here's my code so far.
Fixes: #358
=> content: Support spoilers!

lib/widgets/content.dart, test/widgets/content_test.dart
This is an alternative to #540 that doesn't fix #538. Screenshots coming soon.
Fixes: #512
=> content: Use 17 for base font size (and height 22), like in Figma

lib/widgets/message_list.dart
This is the "easy hack" Greg mentions in the description of #513.
Fixes: #513
=> msglist: Cut excess spacing between sender and paragraph

lib/widgets/text.dart, test/flutter_checks.dart, test/widgets/text_test.dart
After this, there's still more to do for #548:
- letter spacing of 1% (i.e., 0.01 times `fontSize`) in buttons
- perhaps audit for UI code that's meant to follow Figma already,
but where we failed to set a non-zero letter spacing that was
specified in Figma
Fixes: #545
Fixes-partly: #548
=> text: Set 0 letter spacing throughout zulipTypography

lib/widgets/lightbox.dart
Fixes: #550
| --- | --- |
| <img width="561" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/0bacfae5-137e-406a-a7d5-38a31b8dc14e"> | <img width="561" alt="image" src="https://github.com/zulip/zulip-flutter/assets/22248748/70decba9-7011-4deb-8fac-457821dc01f1"> |
=> lightbox: Remove accidental bottom border on AppBar

android/app/build.gradle, android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, android/app/src/profile/AndroidManifest.xml, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle, tools/gradle
There are currently some warnings that `flutter run` prints for Android targets. After the Android notifications work I did a couple of weeks ago, I sat down to resolve those:
* migrating how we invoke Flutter's Gradle code
* upgrading the Kotlin version we use
and then went on to upgrade our versions of Gradle and the Android Gradle Plugin too. Most of this PR comes from that time; then I came back and finished up the last AGP upgrade, which involved a couple of extra wrinkles.
Other than clearing warnings, some of these changes are supposed to reduce the build time, which is nice. I haven't measured the effect, though — it's possible our project isn't large enough to really see the difference.
I validated things by building and running the app and checking that
* it seems to work on a …
=> Upgrade Gradle, AGP, other Android build deps and metadata

lib/model/store.dart, test/api/model/model_checks.dart, test/model/store_test.dart
Fixes #556.
In addition to the test this adds, I wanted to manually test it
end-to-end, to help be sure this covered the scenario where this
retry is known to be needed in the wild:
* The app is offline for a while, perhaps because the device
is asleep.
* The app comes online, tries polling, and finds the event queue
has expired, so it attempts a re-register.
* Before that completes (which after all takes several seconds
if the realm is a large one), the app goes offline again.
* That request's response therefore never reaches the app,
and so when it eventually comes back online it needs to retry.
Step 1 is annoying to carry out literally, because it means
waiting 10 minutes for the event queue to expire.  To work around
that, I sabotaged the getEvents binding function to use a wrong …
=> store: Retry registerQueue on failure; start testing UpdateMachine.load

assets/l10n/app_en.arb, lib/model/database.dart, lib/model/store.dart, lib/widgets/login.dart, pubspec.lock, pubspec.yaml, test/api/core_test.dart, test/model/database_test.dart, test/model/test_store.dart, test/widgets/login_test.dart
Handles #108 , though doesn't address other kinds of SQL errors, I set up some scaffold code to start handling errors that come from the store.
(This is my first PR (in Dart/Flutter/Zulip), so bear with me.)
My initial instinct was to use the Snackbar to signal this issue. (Screenshot in below comment)
However, I saw after that there's a showErrorDialog, so I'm updating it to use it in a separate commit.
The Snackbar is likely a better UX for this scenario since there's little the user can do in a dialog, and there's no input needed from the user. We can also add a action in the snackbar to navigate to the logged in account.
Happy to squash changes once I hear back on some feedback.
Screenshot (using macOS build to debug, blurred out credentials):
Fixes: #108
=> login: display message when account already logged in

lib/widgets/content.dart, test/widgets/content_test.dart
On iOS we prefer LaunchMode.externalApplication because LaunchMode.platformDefault uses SFSafariViewController which provides a weird UX for reasons mentioned in [this]( https://chat.zulip.org/#narrow/stream/48-mobile/topic/in-app.20browser/near/1169118) discussion.
| - | - |
| ![before](https://github.com/zulip/zulip-flutter/assets/36819268/c3cef395-185c-42eb-8313-efc0c5b5899d) |  ![after](https://github.com/zulip/zulip-flutter/assets/36819268/6aaaf077-6136-40e0-87ae-2c4be93aac3b) |
Fixes: #280
=> content: Open links externally on iOS

lib/widgets/compose_box.dart, pubspec.lock, pubspec.yaml
No potentially breaking changes identified in the changelog:
https://github.com/dart-lang/i18n/blob/main/pkgs/intl/CHANGELOG.md#0190
This addresses the following error:
Note: intl is pinned to version 0.19.0 by flutter_localizations
from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.
Because zulip depends on flutter_localizations from sdk which
depends on intl 0.19.0, intl 0.19.0 is required.
So, because zulip depends on intl ^0.18.0, version solving failed.
You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.19.0
Fixes: #575
=> deps: Upgrade `intl` constraint, from ^0.18.0 to ^0.19.0

lib/widgets/inbox.dart, test/example_data.dart, test/widgets/inbox_test.dart
Collapsing a stream/all-DMs section through a sticky header behaves as expected without shifting other sections off the screen.
Fixes: zulip#391.
=> inbox: Fix collapsing a section from its sticky header

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
This pull request addresses the issue of the message list shifting downwards when the "mark as read" button is pressed. The previous implementation would return an empty widget when the button was pressed and cause the message list to shift down. Now it takes a widget with a definite height, which is equal to the size of the button, and won't cause the message list to shift down.
Fixes: #562
| --- | --- |
|  https://github.com/zulip/zulip-flutter/assets/61546411/e13f6a05-0226-4a14-9654-8312271281d3 | https://github.com/zulip/zulip-flutter/assets/61546411/b8a66ad3-394f-499f-9079-51591e4d0766 |
=> msglist: Leave blank space for "mark as read" button so using it doesn't cause messages to shift

lib/model/autocomplete.dart, lib/widgets/autocomplete.dart, test/widgets/autocomplete_test.dart, test/widgets/content_test.dart
When mentioning users, their avatars are shown beside their names in the autocomplete popup.
Fixes: #227
=> autocomplete: Add user avatars to user-mention autocompletes

lib/model/autocomplete.dart, test/example_data.dart, test/model/autocomplete_test.dart, test/model/compose_test.dart
Deactivated users can not be mentioned, so this ensures that deactivated users are excluded from the list that gets rendered in autocomplete popup.
While autocomplete does not include deactivated users, there still is a possibility that same-name users with one or more of them deactivated gets mentioned, which will make the mentioned user ambiguous without the id, this is explained in #451.
Fixes #451
=> autocomplete: Exclude deactivated users from @-mention autocomplete popup

lib/widgets/app.dart, test/flutter_checks.dart, test/widgets/app_test.dart
Before this fix, the list of accounts did not scroll when they were more than a screenful and would show an overflow error on the screen.
After this fix, the list of accounts scrolls properly with no overflow error and without shifting other content offscreen.
<table>
<tr>
<td><b>Before</b></td>
<td><b>After</b></td>
</tr>
<tr>
<td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/36ebfeb9-76b3-485f-a59e-1054bab8448a" width="300"/></td>
<td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/c8ddbe32-96e1-477d-b4ed-58e0e903f912" width="300"/></td>
</tr>
</table>
Fixes: #100
=> accounts-ui: Make accounts list scrollable

lib/model/content.dart, lib/widgets/content.dart, test/model/content_test.dart
This handles the `<del>` element. This means "strikethrough" formatting; it's what you get with Markdown syntax like `~~this~~`, enclosing a span in`~~`.
Handling these means:
- Parsing into `DeletedNode`
- Styling nodes that are of type `DeletedNode` with a line-through
Fixes #357
Final Result:
=> content: Handle strikethrough, the <del> element

lib/widgets/subscription_list.dart, test/widgets/subscription_list_test.dart
Stream names should be sorted regardless of the case and this applies for pinned and unpinned subscriptions:
**A comes before b and B comes after a**
So this adds simple toLowerCase transformation before sorting
Fixes #568
=> subscriptions: Fix stream name sorting case insensitively

assets/l10n/app_en.arb, lib/notifications/display.dart, test/notifications/display_test.dart
handle number properly
This commit addresses the issue of handling plural and singular forms of the string when a group DM notification message is received. The previous implementation used a hard-coded string. Now it uses an internationalized string.
I have also added a test so that both the singular and plural forms of the string are tested.
Fixes: #573
=> notif: Internationalize group DM notification message and

android/app/src/main/AndroidManifest.xml, assets/l10n/app_en.arb, ios/Runner/Info.plist, lib/api/model/web_auth.dart, lib/model/binding.dart, lib/widgets/app.dart, lib/widgets/login.dart, test/api/model/web_auth_test.dart, test/example_data.dart, test/model/binding.dart, test/test_images.dart, test/widgets/autocomplete_test.dart, test/widgets/content_test.dart, test/widgets/login_test.dart
https://github.com/zulip/zulip-flutter/assets/22248748/a97f0696-404b-4063-8958-6fd5b225f636
Fixes: #36
=> login: Support web-based auth methods

lib/widgets/app.dart
| --- | --- |
| ![76E88B36-C44D-4737-AAB7-F0F2C84FBBB0](https://github.com/zulip/zulip-flutter/assets/22248748/c153ca4f-adf4-4261-9662-4a56b1e6ce4d) | ![A90C589F-09E5-48B8-9B5A-A86757D5EA17](https://github.com/zulip/zulip-flutter/assets/22248748/eddee67a-353f-4312-bea3-5702968f21c2) |
| ![1A282E68-F6FF-4FBA-89F8-A1D5CF0C9504](https://github.com/zulip/zulip-flutter/assets/22248748/d4273e87-3420-4329-a5cf-b227629f6721) | ![9EE2200B-5463-4332-9CD7-00D0EA0B4143](https://github.com/zulip/zulip-flutter/assets/22248748/3a6694c4-d820-4acc-8349-091d48e6e4f9) |
Fixes: #606
=> choose-account: Put 8px top padding on scrollable content, not its viewport

lib/model/content.dart, lib/widgets/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
=> content: Handle <hr> horizontal lines

lib/widgets/message_list.dart, test/example_data.dart, test/widgets/message_list_test.dart
A bot icon is shown with the name of the bot users.
<table>
<tr>
<td><b>Before</b></td>
<td><b>After</b></td>
</tr>
<tr>
<td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/cdaad5f4-e1dc-4b7d-bb31-33e83f603241" width="300"/></td>
<td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/2444131d-dd0e-4c23-a26d-20d567025c7a" width="300"/></td>
</tr>
</table>
Fixes: #156
=> msglist: Distinguish `isBot: true` message senders with a bot marker

lib/model/content.dart, test/model/content_test.dart
|before|after|
|-----|----|
|![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-30 at 02 18 02](https://github.com/zulip/zulip-flutter/assets/63330019/0f4b12b6-f51d-4ac3-8767-0a5b458215ec)|![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-30 at 02 18 45](https://github.com/zulip/zulip-flutter/assets/63330019/bfbcda89-a487-4d12-a4e3-ba91895962db)|
Fixes: #355
=> content: Handle blank text nodes after code blocks.

lib/model/unreads.dart
In #423 "Implement stream and topic muting", the Unreads class did start doing some filtering based in stream/topic muting, specifically in these methods:
- countInStream
- countInAllMessagesNarrow
So, update the dartdoc so it doesn't claim that this filtering is an entirely separate concern.
=> unreads [nfc]: Update dartdoc following stream/topic-muting logic

lib/widgets/app.dart, lib/widgets/message_list.dart, lib/widgets/subscription_list.dart, lib/widgets/text.dart, test/widgets/emoji_reaction_test.dart, test/widgets/text_test.dart
This could be helpful for #548, but I'm sending it now so we can see if we like the logic and want to reuse it for that. It does make a small adjustment to some letter spacing, to better follow the user's device-level text size setting, so I'll post some screenshots.
=> text: Add and use proportionalLetterSpacing

lib/notifications/display.dart, lib/widgets/app.dart, lib/widgets/emoji_reaction.dart, lib/widgets/message_list.dart, lib/widgets/text.dart, lib/widgets/theme.dart, test/flutter_checks.dart, test/notifications/display_test.dart, test/widgets/text_test.dart, test/widgets/theme_test.dart
Stacked atop #629. Screenshots coming soon.
Fixes: #548
=> ui: Set letter spacing to 1% in buttons

android/app/src/main/AndroidManifest.xml
This addresses #620 by making it so the whole app state isn't reset when coming back from Firefox in the web-auth flow. Discussion:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/Flutter.20app.20.2B.20SAML.20auth/near/1776828
Later in that discussion, Greg found that this mode is the most appropriate for our app, and that setting taskAffinity="" is probably a good idea as a security-hardening measure.
Fixes: #620
=> android: Set launchMode="singleTask" instead of "singleTop"

lib/widgets/content.dart, test/flutter_checks.dart, test/model/content_test.dart, test/widgets/content_test.dart
Also, use `weightVariableTextStyle` in one place we forgot to.
Fixes: #538
=> content: Show code, mentions, and times properly even in headings etc.

.gitignore, .idea/modules.xml, .idea/zulip.iml, android/app/src/main/AndroidManifest.xml
This has some useful `excludeFolder` items that should help Android Studio see that certain files are not part of our project and should be excluded in searches that are supposed to be limited to "project files".
=> ide: Include .idea/zulip.iml

lib/api/model/model.dart, test/api/model/model_test.dart
Done as an alternative to #642.
Related: #95
=> model: Implement StreamColorSwatch.lerp, copying ColorSwatch.lerp

lib/api/model/model.dart, lib/widgets/unread_count_badge.dart, test/api/model/model_test.dart, test/widgets/unread_count_badge_test.dart
Stacked atop ~~#642~~ #654.
-----
We added the light-mode color computations in #381.
We're not ready to use these yet, but the color computations are
unlikely to change before that time comes, and finding the right
ones is a chore that's good to get done.
Related: #95
=> model: Implement dark-mode stream color swatches

lib/widgets/content.dart, lib/widgets/message_list.dart, test/widgets/content_test.dart
It will be helpful to consult the web app when we define the dark-theme styles of our content elements. This PR prepares for that. I went through all the content elements as we've implemented them, and for all the things that should differ between light and dark theme, ensured that our light-theme style matches the web app.
I also brought the default content text color in line with the web app. (I mention this separately because this color is an attribute of the message list, not content itself, I guess; at least that's how it seems in the code.)
| --- | --- |
| <img width="542" alt="Screenshot 2024-05-10 at 3 16 07 PM" src="https://github.com/zulip/zulip-flutter/assets/22248748/77816ff1-10c0-4700-aa93-e394908832a8"> | <img width="542" alt="Screenshot 2024-05-10 at 3 16 …
=> content/msglist: Update some elements closer to new, 2023+ design, to prepare for light/dark

android/app/src/main/AndroidManifest.xml
The previous attempt at this (cffb112fd, #474) set the configuration used by the HTTP implementation from the Android SDK, and by some third-party HTTP implementations.  But in the bulk of the app's code, we use the HTTP implementation from the Dart standard library, and by default that does not consult the Android configuration.
Happily, Flutter has an opt-in feature to apply the same configuration to the Dart standard library:
https://chat.zulip.org/#narrow/stream/48-mobile/topic/flutter.3A.20user-added.20certs/near/1716845
So use that.
Fixes: #461
=> android: Trust user-supplied CAs, take 2

assets/l10n/app_en.arb, lib/widgets/app.dart, lib/widgets/message_list.dart
This closes: #634.
This is my first try to contribute here, so wanted to ask making this change didn't required any corresponding test changes?
Are we not testing like these buttons should be shown on home screen or something?
Screenshot:
=> ui: Rename "All messages" to "Combined feed".

macos/Runner/AppDelegate.swift
This change was made automatically by `flutter run`, along with the following warning:
```
macos/Runner/AppDelegate.swift uses the deprecated @NSApplicationMain attribute, updating.
```
This change is the macOS counterpart of a previous commit for iOS: https://github.com/zulip/zulip-flutter/commit/5f111cbaf1b92d4cfc315bfc0dd60aef2ef5fe0f
=> macos: Take automatic migration away from `@NSApplicationMain`

lib/widgets/emoji_reaction.dart
This follows zulip/zulip@793020992, which landed after we implemented reaction chips here. (That commit makes some padding adjustments, which we don't need because changing a chip's border width doesn't affect the chip's size.)
| --- | --- |
| <img width="449" alt="Screenshot 2024-05-15 at 2 46 13 PM" src="https://github.com/zulip/zulip-flutter/assets/22248748/f38fbb26-07e9-4475-9151-186736810a9f"> | <img width="449" alt="Screenshot 2024-05-15 at 2 46 37 PM" src="https://github.com/zulip/zulip-flutter/assets/22248748/00657370-e6ae-4b4a-bc94-98cb9899ef00"> |
=> reactions: Increase prominence of own reactions, following web

test/widgets/content_test.dart
This PR makes it so all our tests of Zulip content widgets go through `prepareContentBare`, which has grown some explicit params that let callers opt in to extra dependencies, such as a `PerAccountStoreWidget` ancestor. With this, I have two benefits in mind:
1. As Zulip content widgets gain natural dependencies (such as a ThemeExtension for custom light- and dark-theme colors), we can provide them easily, by just adding to this one function.
2. It will be more obvious when a content widget has "extra" dependencies that will become problematic with #488.
Related: #95
Related: #488
=> content test: Deduplicate ad hoc content-preparing code

lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/text.dart, test/widgets/text_test.dart
Screenshots show the app with the system bold text setting on.
Fixes: #690
| --- | --- |
| ![728B9036-3F4C-4E00-AAA5-4ED34CDD88CE](https://github.com/zulip/zulip-flutter/assets/22248748/4ac26fe7-69e3-4bc3-b1cf-ea259e824902) | ![B6815335-22C0-4B2F-9A21-D2190A67018B](https://github.com/zulip/zulip-flutter/assets/22248748/3a56a3fb-d6c2-4420-affb-a2885dcdf518) |
=> content: Handle bold-text setting in code blocks and error-unimplementeds

lib/widgets/message_list.dart, test/flutter_checks.dart, test/widgets/message_list_test.dart
Like #657, but this is for the message list only (not content), and it completes my sweep through the message list. Screenshots coming soon.
=> msglist: Update more elements closer to new, 2023+ design, to prepare for light/dark

lib/widgets/code_block.dart, lib/widgets/inbox.dart, lib/widgets/login.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, lib/widgets/unread_count_badge.dart
This PR marks several places where we don't yet have enough direction to make a v1 of dark-theme support. In these places, I was unable to find an appropriate dark-theme color by looking at the web app and the Figma (as it is now).
Once we fill these in, it hopefully won't be too long until we have that v1 of dark theme. 🙂
Then some time after that, we'll hopefully have an updated Figma with a dark-theme variant of all the UI pieces. We'll examine that closely and fix places that aren't following it, including places that were wrong because we were following web. (As Vlad [says](https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/design.3A.20colors/near/1801938) on CZO, "Colors in web might be different from mobile.")
=> ui [nfc]: Comment with TODO(#95) where we need dark-theme colors

lib/widgets/theme.dart
(This replaces #682.)
From discussion:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/design.3A.20colors/near/1801938
and the Figma linked there:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=2074%3A26325&t=rjuqcQaHMiGBUReF-1
Now, the app-bar bottom border is colored by the new Figma's `border-bar`, and the main background color is `bg-main`. The app bar background is unchanged because it already matches `bg-top-bar`.
And all these color variables have dark-theme variants! (See discussion for what those are.) That'll help when we implement dark theme, #95.
=> ui: Adjust app bar bg and scaffold bg colors toward new Figma design

pubspec.yaml
Unpinning `package:intl` is required for adding our tests to Flutter's "customer tests", #239:
https://github.com/flutter/tests/commit/a047b7a5e6184969d943f88887bbe32658ed99c1
See comment added in the last commit here for background.
Also cut some unnecessary (or no-longer-necessary) verbose comments that we've had in this file, mostly left by the `flutter create` template.
=> deps: Unpin intl, to follow Flutter's pinning; trim comments

test/model/content_test.dart
This fails there, or at least does in the `flutter/tests` CI environment, with an error like:
::group::❌ C:/Users/RUNNER~1/AppData/Local/Temp/flutter_customer_testing.zulip.4a7c3de6/tests/test/model/content_test.dart: all content examples are tested (failed)
FileSystemException: Cannot open file, path = '/C:/Users/RUNNER~1/AppData/Local/Temp/flutter_customer_testing.zulip.4a7c3de6/tests/test/model/content_test.dart' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
dart:io                               _File.readAsStringSync
test\model\content_test.dart 1082:39  main.<fn>
::endgroup::
I'm not sure what's wrong, but don't really feel like finding out (or working out how to fix it) -- and, conveniently, there's really no need to do so.  See …
=> content test: Skip source-file-reading test on Windows

integration_test/unreadmarker_test.dart, lib/model/store.dart, test/model/autocomplete_test.dart, test/model/compose_test.dart, test/model/internal_link_test.dart, test/model/message_list_test.dart, test/model/stream_test.dart, test/model/test_store.dart, test/model/unreads_test.dart, test/widgets/action_sheet_test.dart, test/widgets/autocomplete_test.dart, test/widgets/content_test.dart, test/widgets/emoji_reaction_test.dart, test/widgets/inbox_test.dart, test/widgets/message_list_test.dart, test/widgets/profile_test.dart, test/widgets/recent_dm_conversations_test.dart
With #458, we'll want this method to write changes to the database
on certain events, to update the metadata we keep about the user's
Zulip servers.
When it does that, we'll want it to wait for that write to finish
before it moves on to make other changes, and for its caller
[UpdateMachine.poll] to similarly wait.  That saves us from having
to worry about potential races if some later event also wants to
make database changes while the first changes haven't finished yet.
It also gives us a good foundation for generally not showing the
user a confirmation that some change has been made until we've
actually saved the change.
So to do that, we'll need the method to be async, and to return a
Future which its call sites should wait for.
This PR does that, after a series of commits donig the …
=> Make handleEvent an async method

lib/model/database.dart, lib/model/store.dart, test/api/core_checks.dart, test/example_data.dart, test/model/store_checks.dart, test/model/store_test.dart, test/model/test_store.dart
=> store: Update account record from initial snapshot

lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/profile.dart, lib/widgets/text.dart, lib/widgets/theme.dart, test/widgets/action_sheet_test.dart, test/widgets/autocomplete_test.dart, test/widgets/content_test.dart, test/widgets/message_list_test.dart, test/widgets/profile_test.dart
I have four main goals for this PR:
- Stop applying the Zulip-message text color to things that aren't Zulip-message text (and refactor to make these errors easy to avoid)
- Don't regress on performance in the message list (for example by making a `DefaultTextStyle` for every message)
- Define and use a consolidated "base message text style" for content widgets to inherit from (which I do by lumping together the text color and the `Paragraph` styles)
- Add a `ThemeExtension` to our app's `ThemeData`, as a home for certain content styles (that we don't want to recompute for each message, or that differ between light and dark theme and will need to be `lerp`ed for the fade animation)
Along the way, I make some small changes/fixes:
- Message sender name was `hsl(0deg 0% 15%)`; it now matches …
=> content: Consolidate message-content base style and apply it more accurately

integration_test/unreadmarker_test.dart, lib/model/message_list.dart, lib/model/narrow.dart, lib/model/unreads.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart, test/api/route/messages_test.dart, test/model/autocomplete_test.dart, test/model/compose_test.dart, test/model/message_list_test.dart, test/model/unreads_test.dart, test/widgets/action_sheet_test.dart, test/widgets/message_list_test.dart
=> Rename "All messages" to "Combined feed" in the codebase.

lib/widgets/content.dart, lib/widgets/text.dart, test/flutter_checks.dart, test/widgets/content_test.dart, test/widgets/text_test.dart
This fixes #705 by making boldness context-dependent, much like we did for some font sizes in #544.
That user-facing change is nice but fairly subtle. I'm also hoping this will be helpful by adding content tests for boldness in the first place; we didn't have any before. And I've set a pattern in the `UserMention` tests that should help reduce confusion when we write boldness tests for #647. (Confusion mainly related to the fact that `UserMention` is in a `WidgetSpan`.)
The need for more helpers in lib/widgets/text.dart is another reminder that it'll be great to have https://github.com/flutter/flutter/issues/148026 fixed upstream. But (as with the existing helpers there) I'm hoping this handles things in a way that makes it straightforward to migrate once that's done.
Fixes: #705
| Before …
=> content: Make **bold** bolder even in spoiler headers and h1/h2/etc.

lib/model/autocomplete.dart, lib/model/recent_dm_conversations.dart, lib/model/store.dart, test/model/autocomplete_test.dart, test/model/recent_dm_conversations_checks.dart, test/model/recent_dm_conversations_test.dart
In @-mention autocomplete users with whom recent DMs are exchanged are given priority.
Other criteria will be added in separate PRs.
_**Note:** This is the first PR in the series of PRs #608 is divided into._
Fixes part of: #228
=> autocomplete: In user-mention autocomplete results give priority to users in DM conversations

lib/model/internal_link.dart, lib/model/internal_link.g.dart, test/model/internal_link_test.dart
=> internal_link: Recognize channel operator in narrow links

lib/model/internal_link.dart, lib/model/internal_link.g.dart, test/model/internal_link_test.dart
These links (`/with/NNNN`) are just accepted and ignored in this PR, they will be interpreted in #683.
Fixes: #684
=> internal_link: Parse topic permalinks

lib/widgets/app.dart, lib/widgets/content.dart, lib/widgets/profile.dart
(That is, the last uses except the ones in code-block styles, which are treated in #727.)
| --- | --- |
| ![6EEB5903-E8FC-46D4-84CE-083ACE1C1E59](https://github.com/zulip/zulip-flutter/assets/22248748/5e7d1d52-88b0-435d-92f9-a23b53082738) | ![2CF00F52-126B-4950-88A8-69E65A531044](https://github.com/zulip/zulip-flutter/assets/22248748/1c7449d2-3695-4752-99f6-ec14281f3f84) |
| ![2F7D6B2C-E328-4AE5-AC0A-2CE5AEB23A7A](https://github.com/zulip/zulip-flutter/assets/22248748/05845fb9-e790-4db6-992f-cd39eeaf5053) | ![C8BDEB92-A391-4316-AB36-6EED5586DCFE](https://github.com/zulip/zulip-flutter/assets/22248748/864e9903-3ebc-410a-81d5-44f1577a0774) |
| ![56A0F77C-578E-4D22-8A30-7D4AEFD26450](https://github.com/zulip/zulip-flutter/assets/22248748/d4a0c427-7e38-4264-ab72-d0d27e5a293a …
=> text: Convert the last uses of `FontWeight.bold` to `weightVariableTextStyle`

pubspec.lock, pubspec.yaml, tools/upgrade
This regexp didn't work on macOS, as discovered by Chris:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/.60tools.2Fupgrade.20flutter-local.60/near/1825388
Specifically it looks like the `\s` and `\S` patterns, which mean "whitespace character" and "not-whitespace character" respectively, don't work there.  If I write things like `[^ ]` instead, then this code works.
From `man 7 re_format` on a Mac, it seems the issue is that those features exist only in "enhanced extended REs", not in mere "extended REs".  (Bash relies for its regexps on the system regexp implementation, which is why its behavior can vary like this.)
On GNU/Linux there's no such distinction... but also the man pages (starting from `man 3 regex`) never actually say just what the regexp language is, so that's …
=> tools/upgrade: Avoid system regexps (via Bash); just use Perl

lib/widgets/lightbox.dart, test/widgets/lightbox_test.dart
Adds tests mentioned in https://github.com/zulip/zulip-flutter/pull/587#discussion_r1597195082
=>  lightbox test: Add video player regression tests 

lib/widgets/code_block.dart, lib/widgets/content.dart, test/widgets/content_test.dart
| --- | --- |
| ![34AB2CF1-E279-4702-A855-80722BE9056A](https://github.com/zulip/zulip-flutter/assets/22248748/88e7058a-3e4a-4749-96f2-6fc9f8b2b3ba) | ![17039B63-B706-4F85-9253-CC5DF863DFB3](https://github.com/zulip/zulip-flutter/assets/22248748/66700f1c-e227-4626-91dc-28d559083b35) |
Related: #95
=> content: Put code-block styles in `ContentTheme`; use weightVariableTextStyle for bold spans

lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/profile.dart, lib/widgets/text.dart, lib/widgets/theme.dart, test/widgets/text_test.dart
It seems helpful to have a central place to put the design variables we export from the Figma design, to help pave the way to implementing it. This PR adds such a place, as a `ThemeExtension`.
It also takes two more color variables from the Figma (`title` and `icon`), to add to the three we've already been using, and applies them to the app bar, since that's something we see marked "ready for dev": https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=2957-50895&m=dev
While we're at it, this also applies the Figma's specified font weight, size, and line height to the app-bar title. (Those aren't expressed as variables in the Figma.)
There's still more to do to align the app bar with what we see in the Figma, and I add TODOs about some of this.
| --- | …
=> theme: Add `ThemeExtension` for Figma design variables; add/use two more variables in `AppBar`

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
In the issue, Greg said:
https://github.com/zulip/zulip-flutter/issues/736#issuecomment-2169118690
> Wrapping in a `SliverSafeArea` would mean that the actual list stays out of the bottom inset area, right? That doesn't seem like the desired behavior — I think it's expected that the messages scroll visibly through that bottom area.
But that's not what I'm seeing. There is a visible change: the blank space that you can scroll into view, under the messages, is now taller by the height of the bottom inset. (Before, the height was just 36px hard-coded.) But you can still scroll this blank space out of view, and when you do, the messages scroll visibly through that bottom area.
| --- | --- |
| <img width="542" alt="image" …
=> content/msglist: Fix vertical position of horizontal scrollbar in codeblock

android/app/src/main/kotlin/com/zulip/flutter/Notifications.g.kt, android/app/src/main/kotlin/com/zulip/flutter/ZulipPlugin.kt, lib/host/android_notifications.g.dart, lib/notifications/display.dart, pigeon/notifications.dart, test/model/binding.dart, test/notifications/display_test.dart
https://github.com/zulip/zulip-flutter/assets/36819268/95429096-c9c4-46ee-907b-d5cc424ea0ea
Fixes: #572
Fixes: #569
Fixes: #571
=> notif: Create summary notification

lib/notifications/display.dart, test/notifications/display_test.dart
While trying out the release build from main on a relatively older (Android 11) device, I found that it results in lingering summary notif:
| Android 14 | Android 11 |
| - | - |
| <video src="https://github.com/zulip/zulip-flutter/assets/36819268/17c44e0e-0317-47b9-b379-68817bc32e4b" /> | <video src="https://github.com/zulip/zulip-flutter/assets/36819268/0a4a0850-7630-410a-8dc8-7b8ab774c52f" /> |
Specifying `autoCancel: true` fixes this behavior on the older device.
=> notif: Enable autoCancel flag for summary notification

analysis_options.yaml
I was just rereading a draft commit I'd written a little while ago, and realized it had the following code:
bool updated = false;
updated |= _handleUpdateMessageEventTimestamp(event);
updated |= _handleUpdateMessageEventContent(event);
updated != _handleUpdateMessageEventMove(event);
if (!updated) return;
Do you see the bug?
.
.
.
There's two different operators there after "updated".  They differ by about three or four pixels.  Only one of them makes any sense to use in this context, as the top-level expression of an expression statement.  When I first reread the diff, I thought I was seeing a speck of dust on my monitor breaking up the last `|`.
Fortunately there is a lint rule that would catch this.  I don't know why it's not in the recommended lists from the Dart or Flutter teams; but …
=> lint: Enable unnecessary_statements

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/model/message.dart, lib/model/message_list.dart, test/model/message_test.dart
This PR is stacked atop #751.
Main commit:
The way the Zulip server API expresses whether there was a move,
and if so what kind of move, is a bit quirky.  This change adds
logic to interpret that information into a more canonical form.
The logic here is translated from what we have in zulip-mobile:
https://github.com/zulip/zulip-mobile/blob/e352f563e/src/api/misc.js#L26
This doesn't yet do anything to actually update our data structures,
and it's an NFC change for release builds.  The only behavior change
is new asserts that fire when the event from the server is malformed.
---
This is based on part of my draft branch for handling moved messages, #150. This covers the portion of that branch that's involved in just interpreting what an `UpdateMessageEvent` is saying about a message move, …
=> Add skeleton of handling a move UpdateMessageEvent

lib/widgets/code_block.dart
This referred to the dark theme that web was using before it switched to Pygments Monokai, in zulip/zulip#26898. No particular need to explain the choice of background color, especially as we intend to replace these styles anyway; that's #754.
=> code_block [nfc]: Update outdated comment

assets/Pygments/AUTHORS.txt, assets/Pygments/LICENSE.txt, lib/licenses.dart, lib/widgets/code_block.dart, lib/widgets/content.dart, pubspec.yaml
For dark theme, web currently uses a mix of Pygments Monokai and Pygments Default. Mixing in Pygments Default seems accidental, so here we just use pure Pygments Monokai. [Discussion](https://chat.zulip.org/#narrow/stream/431-redesign-project/topic/code.20span.20colors/near/1832283).
I've included screenshots, below, of just Pygments Monokai, and of Pygments Monokai with web's adjustments. (Except for the adjustment of putting a border around `err` text; that's hard in Flutter.)
Compare with Pygments's own demonstration of Pygments Monokai here: https://pygments.org/styles/
(To make these screenshots, I plugged in dark-theme colors for the code-block background and message background. So just focus on the code blocks and disregard the jarring appearance of light-theme-styled elements …
=> content: Implement Pygments Monokai, for upcoming dark theme

lib/widgets/content.dart, lib/widgets/theme.dart, test/widgets/content_test.dart
Following #756 (dark-theme variant for code-block syntax highlighting), this completes the sweep through message-content colors for #95 dark theme. By the end of the branch, all colors are defined either in `ContentTheme` with light/dark variants, or still inline but with a comment explaining that they don't need light/dark variants.
A dev-only commit at the end makes it handy to see the results, but we shouldn't merge it because it just hard-codes dark theme in message content and nowhere else. 🙂 I recommend scrolling through "Combined feed" to see if anything stands out.
There's a tiny color change in light theme—
```
content: Adjust inline-code background color to match web
```
—as it seems either f452053dc was wrong or the web app changed since then. I can make screenshots if that …
=> content [nfc]: Finish writing down dark-theme color variants for all content

test/api/fake_api.dart, test/api/fake_api_test.dart
This allows simulating a request that takes some time to return and consequently races with something else. Useful for situations like at https://github.com/zulip/zulip-flutter/pull/713#discussion_r1657899344 .
This is NFC because `Future.delayed(Duration.zero, f)` is exactly equivalent to `Future(f)`.  (The docs aren't real clear on this; but reading the implementations confirms they boil down to the very same `Timer` constructor call, and then the docs do seem to be trying to say that when read in light of that information.)
=> fake_api [nfc]: Add `delay` option to connection.prepare

test/model/message_list_test.dart
Stemmed from https://github.com/zulip/zulip-flutter/pull/766#discussion_r1657648710.
We already always check the invariants through a listener on the MessageListView instance. Now we do it more consistently when not notified.
=> msglist test: Call checkInvariants on checkNotNotified.

pubspec.lock, pubspec.yaml
After the Flutter upstream commit: https://github.com/flutter/flutter/commit/f23dbc50f05c56ef5be871203bb4f167f07df845 a build error related to `flutter_local_notifications` plugin occurs when trying to run the app on Android. The upgrade to `flutter_local_notifications ^7.2.0` version in this PR resolves the issue.
More about the issue: https://github.com/MaikuB/flutter_local_notifications/issues/2329
Fixes: #771
=> deps: Upgrade `flutter_local_notifications` and `Flutter` to the latest

lib/model/message.dart, lib/model/message_list.dart, test/example_data.dart, test/model/message_list_test.dart, test/model/message_test.dart
When handling a message deletion event, we just simply remove the messages from the per account store and wipe them from the message list view if they are present.
Because message deletion can affect what items are to be seen (date separator, recipient header, etc.), if the view has any message deleted, a `_reprocessAll` call is triggered. It would be ideal to just removed the affected items for better performance.
=> message: Handle message deletion event.

assets/l10n/app_en.arb, lib/widgets/action_sheet.dart, test/widgets/action_sheet_test.dart
A new option is added to the long press action sheet of a message to copy the message link to the clipboard.
Here's an illustration:
<table>
<tr>
<td><b>Photo</b></td>
<td><b>Video</b></td>
</tr>
<tr>
<td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/9c4a0df9-5ced-45f9-bfc4-7f37ce229f7a" width="300" /></td>
<td><img src="https://github.com/zulip/zulip-flutter/assets/59946442/39cdaa20-1144-4984-8b35-b0b173e7ef57" width="300" /></td>
</tr>
</table>
Fixes: #673
Fixes: #732
=> msglist: Add "Copy message link" button to action sheet

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/json.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/store.dart, test/api/model/events_checks.dart, test/api/model/events_test.dart, test/api/model/json_test.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/example_data.dart, test/model/store_test.dart
This introduces `JsonNullable` to handle cases where the Zulip API expresses a distinction by having some property be null vs. absent entirely. It's based on the draft I wrote in a chat conversation last year:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.3A.20omitted.20vs.2E.20null.20in.20JSON/near/1551714
Then we use that for RealmUserUpdateEvent.deliveryEmail; which causes the former User.deliveryEmailStaleDoNotUse to no longer be stale, and we can call it simply `User.deliveryEmail`. That will be helpful for #291 (fyi @sm-sayedi).
=> api: JsonNullable; handle absent-vs-null RealmUserUpdateEvent.deliveryEmail

.vscode/settings.json, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/message.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/example_data.dart, test/model/message_test.dart
=> msglist: Support data model for edited/moved marker

lib/model/message.dart, lib/model/message_list.dart
I'm about to send all my draft changes toward #150 as a draft PR, so that @PIG208 can build on that without duplicating the work I did on that a couple of months ago.
This PR pulls out from that draft work a couple of small prep commits that are self-contained and ready to go, so that we can merge them (to reduce future merge conflicts) without blocking on the larger work.
=> Small NFC tweaks to message-move-related code

.github/workflows/ci.yml, android/app/build.gradle, tools/check
Fixes #772.
(Started as a draft PR, because I wasn't sure if more setup was needed in ci.yml in order for this build to work. Indeed some was.)
=> Do Android build in CI

assets/l10n/app_en.arb, assets/l10n/app_ja.arb, docs/translation.md, lib/widgets/app.dart, lib/widgets/compose_box.dart
This is the first one of a series of PRs that target #631.
Fixes parts of #631
=> Intl: Rename stream to channel in translation labels

lib/widgets/login.dart
`keyboardType: TextInputType.visiblePassword` contradicts with `obscureText: true`, resulting in Gboard not obscuring the clipboard preview.
| `obscureText: true` | `obscureText: false` |
|-|-|
| <img width="412" alt="Screenshot 2024-07-08 at 04 09 14" src="https://github.com/zulip/zulip-flutter/assets/36819268/a9396b67-4210-4852-ac8c-907af021ce71"> | <img width="412" alt="Screenshot 2024-07-08 at 04 08 46" src="https://github.com/zulip/zulip-flutter/assets/36819268/4aa0f51f-900c-4b7d-a693-d355bf3c8bb0"> |
Fixes: #743
(This PR was result of pair-programming session with @sm-sayedi)
=> login: Show `visiblePassword` type keyboard only when password is unobscured

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/model/narrow.dart, lib/model/store.dart, lib/model/typing_status.dart, lib/model/unreads.dart, test/api/model/events_checks.dart, test/api/model/events_test.dart, test/example_data.dart, test/model/typing_status_test.dart, test/model/unreads_test.dart
Still mostly a work in progress.
This should partially address #665
=> model: Add data models for typing events.

lib/api/core.dart, lib/main.dart, lib/model/binding.dart, lib/widgets/about_zulip.dart, lib/widgets/clipboard.dart, test/api/core_test.dart, test/api/fake_api.dart, test/api/route/messages_test.dart, test/model/binding.dart, test/widgets/action_sheet_test.dart, test/widgets/clipboard_test.dart
=> api: Embed platform and app info in user-agent

lib/widgets/subscription_list.dart, test/example_data.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/model/stream_test.dart, test/widgets/message_list_test.dart, test/widgets/subscription_list_test.dart
Fixes: #424
| After | Before|
| -------- | ------- |
| ![image](https://github.com/zulip/zulip-flutter/assets/63330019/12b3f8b3-8bda-4558-ae36-1d5624a3df9a) | ![image](https://github.com/zulip/zulip-flutter/assets/63330019/c226785a-cedf-4462-92c1-02ccd34d40f5) |
=> subscription_list: Show muted streams as faded in streams list

android/app/src/main/kotlin/com/zulip/flutter/Notifications.g.kt, android/app/src/main/kotlin/com/zulip/flutter/ZulipPlugin.kt, assets/l10n/app_en.arb, lib/host/android_notifications.g.dart, lib/notifications/display.dart, pigeon/notifications.dart, test/model/binding.dart, test/notifications/display_test.dart
https://github.com/zulip/zulip-flutter/assets/36819268/ddcaecd1-b489-4564-bf96-1888e71acd4c
Fixes: #128
=> notif: Support messaging-style notifications

lib/widgets/action_sheet.dart, lib/widgets/message_list.dart, test/widgets/message_list_test.dart
This is a draft only because I haven't yet written tests for it, and I'm going AFK in a couple of minutes but want to provide this now for #779 to build on per https://github.com/zulip/zulip-flutter/pull/779#discussion_r1676798111 .
=> msglist: Provide narrow to MessageListPage descendants

lib/widgets/compose_box.dart, test/widgets/compose_box_test.dart
=> compose box: On failed message send, show error dialog

lib/model/content.dart, lib/widgets/content.dart, lib/widgets/lightbox.dart, test/model/content_test.dart, test/widgets/content_test.dart
| Thumbnails | Placeholders |
| - | - |
| <video src="https://github.com/user-attachments/assets/19413ccd-cc06-42c0-8894-a1058b6c8bac"> | <video src="https://github.com/user-attachments/assets/3c7d1f77-65b3-4851-a9f1-630e497dfbe3"> |
Fixes: #799
=> content: Handle thumbnails

lib/widgets/actions.dart, lib/widgets/message_list.dart, test/widgets/actions_test.dart, test/widgets/message_list_test.dart
This is a refactoring we'll want for #131 / #779, as discussed at https://github.com/zulip/zulip-flutter/pull/779#issuecomment-2237737547 .
This doesn't cover actually refactoring `markNarrowAsRead` to be reusable for marking as unread — @Khader-1 that'll be for you to do as part of #779. But this sets up the framework for doing that refactor.
The two main commits' messages:
---
actions [nfc]: Move markNarrowAsRead to new file
This function isn't quite part of the UI -- it's mostly a driver
around some API requests.  But it doesn't belong in the API code
either, because it interacts with UI widgets in order to give
progress and failure feedback to the user.
Because there's nontrivial logic in here and it isn't really specific
to this particular piece of UI, we'd like to reuse much of this …
=> Move markNarrowAsRead to new "actions" file; port most of its tests

lib/api/route/messages.dart, lib/model/content.dart, lib/model/store.dart, lib/widgets/compose_box.dart, lib/widgets/content.dart
The first commit preps for later changes to add more narrows (#807). Using `switch` gives us the benefit of exhaustive match checks.
narrow is refactored to become private because otherwise `switch` is not able to promote the type of it.
https://dart.dev/tools/non-promotion-reasons#private
The remaining commits are follow-ups to sweep the remaining TODO(dart-3) items throughout the code base.
=> dart [nfc]: Replace else-if's with switch.

lib/model/channel.dart, lib/model/internal_link.dart, lib/model/store.dart, lib/model/unreads.dart, test/model/channel_test.dart, test/model/store_test.dart, test/model/unreads_test.dart
=> channel: Rename `StreamStore` to `ChannelStore`

lib/model/message_list.dart, lib/model/recent_senders.dart, lib/model/store.dart, test/model/autocomplete_test.dart, test/model/message_list_test.dart, test/model/recent_senders_test.dart
This is the second PR in the series of PRs #608 is divided into. This solely focuses on bringing the data structures for the upcoming "recent senders" criterion of @-mention autocomplete. #828 is the next PR in the series.
Fixes part of: #228
=> model: Introduce data structures for "recent senders criterion" of user-mention autocomplete

test/widgets/lightbox_test.dart
This includes several TODO comments for further aspects of the lightbox that this doesn't yet test.
/cc @rajveermalviya, for https://github.com/zulip/zulip-flutter/pull/833#discussion_r1688762292
=> lightbox test: Add basic tests for image lightbox

lib/api/core.dart, lib/api/route/messages.dart, lib/model/binding.dart, lib/widgets/compose_box.dart, pubspec.lock, pubspec.yaml, test/api/core_test.dart, test/api/route/messages_test.dart, test/model/binding.dart, test/stdlib_checks.dart, test/widgets/compose_box_test.dart
While working on this I realized we didn't have any widget tests for the image-upload flows! So I added some. There's still more to test there, and there might be some helpful deduplication in the tests.
But anyway, manual testing on my iPhone showed that the user-visible symptom of #829 on CZO is resolved:
> The symptom is that images don't get displayed in the message at all.
Fixes: #829
=> compose: Include content-type in image-upload requests

lib/model/autocomplete.dart, test/model/autocomplete_test.dart
Besides recent activity in DMs, activity in the current topic/stream is also considered (as the first criterion) when suggesting users in @-mention autocomplete.
_**Note**: This is the third PR in the series of PRs #608 is divided into, coming after #692_.
Fixes part of: #228
=>  autocomplete: Add "recent senders criterion" to user-mention autocomplete

lib/model/content.dart, lib/widgets/content.dart, lib/widgets/lightbox.dart, test/model/content_test.dart, test/widgets/lightbox_test.dart
https://github.com/user-attachments/assets/0a007765-0879-4124-9f1b-2cf597518dac
(Initial image opens are older messages missing `data-original-dimensions` attribute)
Fixes #830
=>  lightbox: Display thumbnail with original image sizing 

lib/api/notifications.dart, lib/api/notifications.g.dart, lib/notifications/display.dart, test/api/notifications_test.dart
=>  api/notif: Rename FcmMessageStreamRecipient to FcmMessageChannelRecipient

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/model/channel.dart, lib/model/store.dart, test/model/test_store.dart, test/widgets/message_list_test.dart
=> api: Rename stream to channel in events

android/app/src/main/kotlin/com/zulip/flutter/Notifications.g.kt, android/app/src/main/kotlin/com/zulip/flutter/ZulipPlugin.kt, lib/host/android_notifications.dart, lib/host/android_notifications.g.dart, lib/notifications/display.dart, pigeon/notifications.dart, test/model/binding.dart, test/notifications/display_test.dart
=> notif: Replace flutter_local_notification `createNotificationChannel` with pigeon

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
Fixes: #613
Final Result:
https://github.com/user-attachments/assets/95912caf-2b7d-4676-b07e-a74c551aace0
=> ui: Use faster animation for mark as read

lib/widgets/edit_state_marker.dart, lib/widgets/message_list.dart, lib/widgets/theme.dart, test/widgets/message_list_test.dart
=> msglist: Implement MessageListTheme, with dark-theme colors

lib/main.dart, lib/widgets/edit_state_marker.dart, lib/widgets/input.dart, lib/widgets/stream_colors.dart, lib/widgets/unread_count_badge.dart, test/model/autocomplete_test.dart, test/notifications/display_test.dart, test/notifications/receive_test.dart, test/widgets/code_block_test.dart, test/widgets/stream_colors_test.dart
I noticed this in lib/main.dart, which is short and clearly doesn't
have anything that should require the Material library.  Then just
did a sweep with the command:
$ perl -i -0pe 's,package:flutter/\Kmaterial,widgets,' \
-- $(git grep -l package:flutter/material)
followed by `git checkout @` on all the files where the analyzer
complained.
Then similarly for flutter/cupertino.
=> widgets [nfc]: Strength-reduce flutter/material and flutter/cupertino imports

lib/notifications/display.dart, test/notifications/display_test.dart
Add more tests for Android messaging style notif implementation, listed here: https://github.com/zulip/zulip-flutter/pull/718#pullrequestreview-2170569390
=> notif: Add more tests for messaging style notif and fix for fetchBitmap

assets/l10n/app_en.arb, lib/api/model/events.dart, lib/api/route/events.dart, lib/model/typing_status.dart, lib/widgets/message_list.dart, test/api/model/events_test.dart, test/model/typing_status_test.dart, test/widgets/message_list_test.dart
Display a typing indicator when there are people typing in a `SendableNarrow` such as `DmNarrow` and `TopicNarrow`, in a fashion similar to the web app.
This is stacked on top of #783 and fixes #665.
=> msglist: Display typing indicators on typing.

lib/widgets/theme.dart, lib/widgets/unread_count_badge.dart, test/widgets/unread_count_badge_test.dart
For the user-facing change in this commit:
```
unread_count_badge: Clear out a TODO by following Vlad's design
```
The difference (in the text color of the unread-count badges on the streams/topics) really is tiny. I used Mac's Digital Color Meter to see that there was in fact a difference, though.
| --- | --- |
| ![BDA772E1-FEA1-4AE7-80E0-4A26BB09866B](https://github.com/user-attachments/assets/099208fc-66a4-474a-80e8-1e9a9b303d63) | ![2DF3752E-B708-4676-848E-B2932EEB6119](https://github.com/user-attachments/assets/a7ca276c-176e-4e82-b1db-ec64fad2c133) |
=> unread_count_badge: Clear out all `TODO(#95)`s

assets/l10n/app_en.arb, lib/api/model/narrow.dart, lib/model/autocomplete.dart, lib/model/internal_link.dart, lib/model/internal_link.g.dart, lib/model/message_list.dart, lib/model/narrow.dart, lib/model/unreads.dart, lib/widgets/actions.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart, test/api/route/messages_test.dart, test/model/autocomplete_test.dart, test/model/compose_test.dart, test/model/internal_link_test.dart, test/model/message_list_test.dart, test/model/narrow_test.dart, test/model/unreads_test.dart, test/widgets/action_sheet_test.dart, test/widgets/actions_test.dart, test/widgets/message_list_test.dart
Early prototype to support @-mentions narrow.
TODO:
Fixes #250
=> msglist: Support @-mentions narrow

lib/widgets/inbox.dart, lib/widgets/theme.dart
Note that most of these colors are provisional because there isn't a source for them in web or the Figma designs we have so far. I've noted these with TODOs in the code, to double-check with Vlad.
Stacked atop #854, which makes a (barely discernible) user-facing color change in light theme; see screenshots there.
Otherwise, light theme is unchanged. Here's a side-by-side for light and dark themes at the tip of this PR.
| Light | Dark |
| --- | --- |
| ![DE4F3A9E-021D-4EA2-87B1-23E1D6543D0D](https://github.com/user-attachments/assets/197b59ae-bf3d-43cb-9084-680eeedb5757) | ![ED05469A-4402-4CC4-8A56-154AD0C4A954](https://github.com/user-attachments/assets/dc230b54-6ba4-4261-92a0-1e35fd2b4860) |
Related: #95
=> inbox: Implement workable dark theme

assets/l10n/app_en.arb, lib/api/model/events.dart, lib/api/model/events.g.dart, lib/model/store.dart, lib/widgets/compose_box.dart, lib/widgets/theme.dart, test/widgets/compose_box_test.dart
When DMs have one or multiple deactivated users, all parts of the compose box are replaced with a banner, saying: _You cannot send messages to deactivated users_.
<table>
<tr>
<td><b>DMs with active user</b></td>
<td><b>DMs with deactivated user</b></td>
<td><b>DMs with deactivated user - Dark</b></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/f0724c2d-2a06-498c-b752-188a42535b79" width="300"/></td>
<td><img src="https://github.com/user-attachments/assets/6096c014-9473-4f39-a4e0-fd0db6fc78b0" width="300"/></td>
<td><img src="https://github.com/user-attachments/assets/997577f5-1a7c-4377-b75c-8ae671e37f00" width="300"/></td>
</tr>
</table>
https://github.com/user-attachments/assets/f219ef6f-3f65-44d8-a5d8-93b7883eb348
**Note:** This work is the result of a …
=> compose_box: Replace compose box with a banner in DMs with deactivated users

lib/widgets/message_list.dart
Aha, well this did turn out to be pretty quick. 🙂
Fixes: #858
=> msglist [nfc]: Comment about typing-indicator color for light/dark

lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, lib/widgets/theme.dart
Along the way, this makes a non-NFC change in light mode on the "Channels" screen. The channel names are now somewhat darker (`#222222`, replacing `#262626`):
| --- | --- |
| ![944D113F-3BBA-4104-A314-3910B906549D](https://github.com/user-attachments/assets/6c74b761-357f-4e3e-9e71-cee2e1f8b100) | ![D2D5B77B-CF03-41FB-9438-D26D21807A1F](https://github.com/user-attachments/assets/ebdcac9e-cdcf-46ca-a23e-1de5e18b5444) |
=> Implement workable dark theme for "Channels" and "Direct messages" screens, pending design

lib/api/model/model.dart, lib/api/model/model.g.dart, test/api/model/model_test.dart, test/example_data.dart
Fixes parts of #631.
This focuses on two models:
- `ChannelDestination`
- `ChannelPostPolicy`
=> api: Rename to ChannelDestination and ChannelPostPolicy from "stream"

pubspec.lock, pubspec.yaml
We haven't had a Flutter upgrade for over a month now; specifically, there is the [`spacing` property](https://github.com/flutter/flutter/pull/152472) available to `Column` and `Row` now, which is [helpful](https://github.com/zulip/zulip-flutter/pull/853/files#r1710247901) in #853. So I think it's a good time to have an upgrade!
=> deps: Upgrade Flutter to 3.24.0-1.0.pre.518

lib/model/autocomplete.dart, test/model/autocomplete_test.dart
In @-mention autocomplete, users are suggested based on:
1. Recent activity in the current topic/stream.
2. Recent DM conversations.
3. **Human vs. Bot users (human users come first).**
4. **Alphabetical order.**
_**Note**: This is the fourth (last) PR in the series of PRs #608 is divided into, coming after #828._
Fixes: #228
=> autocomplete: Add "human vs. bot user" and "Alphabetical order" criteria

lib/widgets/subscription_list.dart, lib/widgets/unread_count_badge.dart, test/widgets/subscription_list_test.dart
=> subscription_list: Show a dot for unreads if channel is muted

lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/model/store.dart, lib/widgets/profile.dart, test/example_data.dart, test/widgets/profile_test.dart
<table>
<tr>
<td><image src="https://github.com/user-attachments/assets/58580678-4b63-4820-b4c4-f76371b66a9a" width="300"/></td>
<td><image src="https://github.com/user-attachments/assets/3b6bf959-b1e3-4769-9ec8-59b433125b32" width="300"/></td>      
</tr>
</table>
Fixes: #291
=> profile: Display user email

integration_test/unreadmarker_test.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/message.dart, lib/model/message_list.dart, lib/notifications/display.dart, lib/widgets/message_list.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/example_data.dart, test/flutter_checks.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/notifications/display_test.dart, test/widgets/action_sheet_test.dart, test/widgets/autocomplete_test.dart, test/widgets/content_test.dart, test/widgets/message_list_checks.dart, test/widgets/message_list_test.dart, test/widgets/profile_test.dart, test/widgets/recent_dm_conversations_test.dart
Fixes most of #150. (After this lands we should do a quick scan to identify anything else that needs updating on message moves — there are several new data structures in the store that we've merged in recent weeks.)
A couple of months ago I spent a few hours writing part of an implementation of #150. It's mostly complete, apart from the lack of tests… and any bugs it has that will be found by writing those tests.
@PIG208 since you're picking up #150 shortly, I spent a small amount of time just now cleaning up that draft branch and rebasing atop the changes from #750, and writing down what remains to be done to finish it. So please start from this, which will let you avoid duplicating that work.
I believe there are three remaining things this needs:
* Tests. As usual, these should go in …
=> Handle moved messages in MessageStore and message lists

lib/widgets/theme.dart, test/widgets/emoji_reaction_test.dart, test/widgets/message_list_test.dart, test/widgets/theme_test.dart
We now have dark-theme variants in all the styles that differ between light and dark, in all of the app we've implemented so far. It's time to let users benefit from that work!
We don't yet let the user choose between dark/light/system in the app -- that's #97 "Store some client settings" -- but the "system" behavior should be the default anyway, and this commit provides that.
The dark-theme colors come from various sources. For each color, I believe the source is clear either in the code or the Git history. Those sources are:
- Flutter's library of Material Design widgets, for UI that's been using those (like the compose box)
- the "ready for dev" parts of the new Figma, like this: https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=2940-48987&m=dev
- the web app (in …
=> theme: Follow system setting for light/dark theme!

lib/model/store.dart, lib/widgets/app.dart, lib/widgets/app_bar.dart, lib/widgets/inbox.dart, lib/widgets/lightbox.dart, lib/widgets/message_list.dart, lib/widgets/profile.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, test/model/store_checks.dart, test/model/store_test.dart, test/widgets/app_bar_test.dart
<details>
<summary>Preview</summary>
| isLoading=false | isLoading=true |
| - | - |
| ![image](https://github.com/user-attachments/assets/bdc9d3b8-9a11-42c5-aa71-2155f28f11a3) | ![image](https://github.com/user-attachments/assets/99bef853-3389-46d9-bc14-8c4064092aa1) |
| ![image](https://github.com/user-attachments/assets/67bbf0a6-5ca8-45c7-bc53-8c67c36fecb9) | ![image](https://github.com/user-attachments/assets/cea6e501-4466-4454-aa4d-5496720475ee) |
</details>
Fixes #465.
=> Add a loading indicator for PerAccountStore

lib/model/store.dart
This fixes #554, and supersedes #564.
=> Reset backoff duration after successful connection.

test/widgets/action_sheet_test.dart, test/widgets/actions_test.dart, test/widgets/autocomplete_test.dart, test/widgets/clipboard_test.dart, test/widgets/content_test.dart, test/widgets/message_list_test.dart, test/widgets/profile_test.dart, test/widgets/recent_dm_conversations_test.dart, test/widgets/store_test.dart, test/widgets/text_test.dart, test/widgets/theme_test.dart, test/widgets/unread_count_badge_test.dart
This consists of handpicked output from running the dart lint fix for code `avoid_types_on_closure_parameters`. We probably don't need to enable this linter rule because in many cases the type annotation improves readability. For the `(WidgetTester tester)` case, though, it is common and intuitive enough that the annotation shouldn't be necessary.
See also:
https://github.com/zulip/zulip-flutter/pull/762#discussion_r1678487007
=> test [nfc]: Remove WidgetTester type annotation from testWidgets tests.

test/example_data.dart, test/model/autocomplete_test.dart, test/widgets/app_test.dart, test/widgets/recent_dm_conversations_test.dart
Zulip user IDs, message IDs, and stream/channel IDs (and anything else that's an ID of a row in the server database) are positive integers. So are our account IDs. To help keep test data realistic, enforce those in the example-data functions.
This follows up on 739fa8491 (in #828; /cc @sm-sayedi), which made a similar fix for one test case.
=> test [nfc]: Ensure user IDs, message IDs, etc. are positive

assets/l10n/app_en.arb, lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/message_list.dart, test/widgets/action_sheet_test.dart, test/widgets/actions_test.dart
Fixes: #131
This adds a new button "**Mark as unread from here**" to the bottom sheet activated for read messages, when clicked all messages starting from selected one down are marked as unread.
| Before | After|
| --- | --- |
| ![image](https://github.com/user-attachments/assets/534c9d40-c5ac-46dd-8769-f24faaf25b4b)| ![image](https://github.com/user-attachments/assets/8cbce6d5-3596-40ae-80a9-e4fc2f805d47) |
https://github.com/zulip/zulip-flutter/assets/63330019/b800f93f-6b9d-47d6-a41d-07daf3da1773
=> action_sheet: Add "Mark as unread from here" button

lib/widgets/compose_box.dart
This is a followup to #816, as foreshadowed at https://github.com/zulip/zulip-flutter/pull/816#issuecomment-2266030983 .
This lets _ComposeBoxLayout stay focused on the complexity of how the text inputs, the editing buttons, and the send button relate to each other. In the case where an error banner is present, this also lets us skip in the build method some logic to compute things that won't end up getting used.
=> Refactor compose-box layout with error banner

lib/model/channel.dart, lib/model/message.dart, lib/model/message_list.dart, lib/model/store.dart, test/example_data.dart, test/model/channel_test.dart, test/model/message_list_test.dart, test/model/test_store.dart, test/model/unreads_test.dart, test/widgets/message_list_test.dart, test/widgets/subscription_list_test.dart
In particular this will allow us to start offering UI for muting
and unmuting topics, and have the message list the user is looking at
update appropriately when they do so.
Fixes: #421
---
The first two commits are taken from #787 (/cc @PIG208):
aef0ab1eb test [nfc]: Allow overriding original stream and add checks.
9c50ba57e message: Handle moved messages from UpdateMessageEvent.
So they can be ignored in reviewing this PR, and we'll plan to merge #787 before this one.
=> msglist: Handle UserTopicEvent, hiding/showing messages as needed

lib/api/route/channels.dart, lib/api/route/channels.g.dart, lib/model/autocomplete.dart, lib/widgets/autocomplete.dart, lib/widgets/compose_box.dart, test/example_data.dart, test/model/autocomplete_checks.dart, test/model/autocomplete_test.dart, test/widgets/action_sheet_test.dart, test/widgets/autocomplete_test.dart, test/widgets/compose_box_checks.dart, test/widgets/compose_box_test.dart
Fixes: #310
https://github.com/zulip/zulip-flutter/assets/63330019/d47b388d-f879-4ee5-b290-62c0342f61d3
=> autocomplete: Introduce topic input autocomplete

lib/api/model/narrow.dart, lib/api/model/narrow.g.dart, lib/model/internal_link.dart, lib/model/narrow.dart, lib/widgets/actions.dart, test/model/internal_link_test.dart, test/widgets/actions_test.dart, test/widgets/message_list_test.dart
=> Internal_link: Add ApiIsNarrow.

android/app/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties
=> deps android: Upgrade Android Gradle Plugin

test/widgets/compose_box_checks.dart
(A tiny cleanup I happened across this while writing another change.)
These types live in lib/model/autocomplete.dart, so the corresponding checks-extensions live in test/model/autocomplete_checks.dart (which indeed has them).
=> test [nfc]: Cut redundant checks-extensions from compose_box_checks

lib/model/autocomplete.dart
This gives AutocompleteView subclasses the flexibility to have an implementation that's more than a single loop through candidates.
That will be useful for #234 / #889, /cc @sm-sayedi.
To keep the tricky aspects of the main search loop encapsulated, we move them into a helper function `filterCandidates` which those `computeResults` implementations can call.
=> autocomplete [nfc]: Give subclasses control of computeResults

README.md, pubspec.lock, pubspec.yaml
Also removed a piece of documentation on upgrading Flutter on running `tools/checks`.
=> deps: Upgrade Flutter to 3.25.0-1.0.pre.41

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/channel.dart, test/example_data.dart, test/model/channel_test.dart
This was necessary for #674 to work properly (i.e., update UI based on changes in `ZulipStream.channelPostPolicy`).
Fixes: #182
=> api: Add stream/update event

assets/l10n/app_en.arb, lib/model/autocomplete.dart, lib/model/internal_link.dart, lib/model/message.dart, lib/model/message_list.dart, lib/model/narrow.dart, lib/model/unreads.dart, lib/widgets/actions.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart, test/api/route/messages_test.dart, test/model/autocomplete_test.dart, test/model/compose_test.dart, test/model/internal_link_test.dart, test/model/message_list_test.dart, test/model/narrow_test.dart, test/model/unreads_test.dart, test/widgets/action_sheet_test.dart, test/widgets/message_list_test.dart
Unreads can probably be handled in a separate PR, because it will probably grow in complexity.
This is stacked on top of #869
=> narrow: Add starred messages narrow

android/app/src/main/kotlin/com/zulip/flutter/Notifications.g.kt, android/app/src/main/kotlin/com/zulip/flutter/ZulipPlugin.kt, lib/host/android_notifications.g.dart, lib/notifications/display.dart, pigeon/notifications.dart, test/model/binding.dart, test/notifications/display_test.dart
=> notif: Handle remove notification message

tools/check
Sometimes `tools/check build_runner` would exit with just an error message about "signal 13":
Running build_runner...
xargs: git: terminated with signal 13; aborting
Running drift...
Signal 13 is SIGPIPE: it means that `git` command under `xargs` was trying to write to a pipe, presumably its own standard output, and the other end of the pipe had been closed, presumably by the next command having already exited.
The reason the other end had been closed is that `grep -q` has an optimization where it exits as soon as it knows its answer. Handy in general, but some programs (like `git grep -l`, apparently) are fragile like this to having their output pipe closed. So, undo that behavior here.
The overall effect of this bug was that the tools/check script would report success in this case, but …
=> check: Fix closed-pipe `git` error that could defeat build_runner suite

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/api/model/submessage.dart, lib/model/message.dart, lib/model/store.dart, test/api/model/model_checks.dart, test/api/model/submessage_checks.dart, test/api/model/submessage_test.dart, test/example_data.dart, test/model/message_test.dart
Stacked on top of #823.
Fixes: #165
=> Support polls (read-only)

lib/model/autocomplete.dart, lib/widgets/autocomplete.dart
This is a small followup to #896 — after making these type parameters no longer needed, I forgot to also go back and remove them.
(/cc @sm-sayedi as you'll want to rebase #889 atop this)
=> autocomplete [nfc]: Cut disused CandidateT type parameters

pubspec.lock, pubspec.yaml
This commit follows the request in
https://github.com/flutter/flutter/issues/154123
by pointing to a Flutter maintainer's fork of `flutter_color_model` and `color_model` while we wait for their PR from that fork to be settled.
To validate this change, I checked out the roll from engine-flutter-autoroll that failed on our tests:
https://github.com/flutter/flutter/pull/153985
and confirmed that our tests (the ones that run with `tools/check test --all`) failed with same-looking errors before this change and passed after this change.
I did run all of `tools/check --all`, not just the `test` suite. There was "info"-level output from the analyzer telling us about things we've been using that will be deprecated with the proposed Color API change (`Color.value` and `Color.withOpacity`). We'll …
=> deps: Add some overrides to unblock Flutter Color API changes for wide-gamut

.gitignore
This change has been getting applied by `flutter run`, and Greg identified this upstream commit as the cause:
https://github.com/flutter/flutter/commit/29f332c82
Discussion:
https://github.com/zulip/zulip-flutter/pull/873#issuecomment-2285235234
=> gitignore: Add a few lines following an upstream change

lib/widgets/message_list.dart
msglist: Fix mark-as-read button icon color in dark mode
After sweeping through the message-list screen to implement dark
theme (#843), in late July, the Flutter framework merged
flutter/flutter#143501, in early August. This made it so our
`foregroundColor` no longer controlled the icon color, as promised
in the dartdocs of `foregroundColor` and `iconColor`.
I opened an issue for Flutter about the inconsistency with the doc:
https://github.com/flutter/flutter/issues/154644
and sent a PR to resolve it, by updating the doc (which the author
of 143501 had said was the right fix):
https://github.com/flutter/flutter/pull/154646
Fixes: #926
=> msglist: Fix mark-as-read button icon color in dark mode

lib/model/channel.dart, lib/model/store.dart, test/model/channel_test.dart
These members didn't have docs. They have some nontrivial invariants, so can especially benefit from docs.
Then this arrangement of debugTopicVisibility
follows the pattern we generally use for other members of
ChannelStore and MessageStore, and lets us eliminate the getter
returning a ChannelStoreImpl.
This pattern -- exposing all the data as members directly on the
overall PerAccountStore, delegating to the underlying channel store
and message store as needed -- is convenient because it means that
code consuming the store doesn't have to worry about which sub-area
of the store we've organized a given piece of data into: it's all
just methods on the store.
Noticed this was here while reviewing a PR that included a new
similar deviation from this pattern (/cc @PIG208): …
=> channel [nfc]: Document methods on ChannelStore; expose debugTopicVisibility directly

test/example_data.dart
This avoids a test accidentally coming to depend on the particular topic name that `eg.streamMessage` happens to choose by default.
Discussed previously at:
https://github.com/zulip/zulip-flutter/pull/787#discussion_r1710743918
For convenience, we preserve the fact that successive calls to `eg.streamMessage` without a `topic` argument will get the same topic each time.  (This saves various test cases from having to specify the topic just to ensure all their messages have some common topic.)
=> test: Use random topic in eg.streamMessage

lib/model/content.dart, test/model/content_test.dart
For some very old messages (e.g.: [this](https://chat.zulip.org/#narrow/stream/2-general/topic/Error.20in.20dev.20server/near/18765)), a code block might contain no grandchildren, or equivalently, the `<pre></pre>` block within the `<div class="codehilite"></div>` element is empty.
While these messages might be present on CZO only due to some ancient server bugs, the client should not crash when it does encounter them.
```
Crashes:
- RangeError (length): Invalid value: Valid value range is empty: -1
Oldest message: 5020; newest message: 29855
```
=> Handle the case when a code block has no grandchildren

lib/model/message.dart, lib/model/store.dart, test/model/message_test.dart, test/model/store_test.dart
=> Handle disposal of message store correctly.

test/example_data.dart
This specifically fixes a test data realism issue of the test "find account among several" in
`test/notifications/display_test.dart` due to duplicate email addresses within a realm.  This also useful in general in cases when the email addresses do not matter and should be kept boring.
The generation uses an increasing sequence to make collision unlikely (still possible with caller specified values).
This is taken from #934 and similar to #932.
=> test: Use random email in eg.user

tools/check
The diffs generated from running `tools/check build_runner` were not detected.  See comment: https://github.com/zulip/zulip-flutter/pull/904#discussion_r1762083210
We normally exclude diffs from generated files through our `.gitattributes` configurations.  This happens to `git --quiet -- [<path>...]` too.  -a/--text allows us to include those files regardless.
=> check: Use --text when potentially diffing generated files

pubspec.lock, pubspec.yaml, test/widgets/channel_colors_test.dart, test/widgets/colors_checks.dart, test/widgets/compose_box_test.dart, test/widgets/content_test.dart, test/widgets/emoji_reaction_test.dart, test/widgets/inbox_test.dart, test/widgets/message_list_test.dart, test/widgets/subscription_list_test.dart, test/widgets/theme_test.dart, test/widgets/unread_count_badge_test.dart
Done to follow a draft migration guide:
https://github.com/flutter/website/blob/997c893ccec5fb15dd085a4d23fe8c43870c631b/src/content/release/breaking-changes/wide-gamut-framework.md
for the proposed breaking change that raised
https://github.com/flutter/flutter/issues/155113
Some other work was needed outside what's described in that draft;
see:
https://github.com/flutter/flutter/issues/155113#issuecomment-2347374468
https://github.com/flutter/flutter/issues/155113#issuecomment-2356356254
=> test: Use color checks that tolerate floating-point errors

macos/Runner/AppDelegate.swift
This change was made automatically by `flutter run`, along with the following warning:
```
macos/Runner/AppDelegate.swift does not override applicationSupportsSecureRestorableState. Updating.
```
See upstream commit that introduced this override: https://github.com/flutter/flutter/commit/68f375fe3871a28dd58017d145d24712e087f4e0
=> macos: Take in automatic override of `applicationSupportsSecureRestorableState`

pubspec.lock
Changelog:
https://pub.dev/packages/video_player_android/changelog
This update migrates the plugin to use newer API recommended
to support Impeller:
https://docs.flutter.dev/release/breaking-changes/android-surface-plugins
Without this migration, the videos do play but they look
pixelated, resulting in a bad UX.
| before | after |
| - | - |
| ![before](https://github.com/user-attachments/assets/7114920d-ee49-48e3-8cc8-f6d39a552ae8) | ![after](https://github.com/user-attachments/assets/23b65c79-4046-47c1-8894-3baf9d02b13e) |
Additionally, it updates the underlying Media3-ExoPlayer
library to version 1.4.1:
https://developer.android.com/jetpack/androidx/releases/media3#1.4.1
=> deps: Upgrade video_player_android to 2.7.3

lib/model/content.dart
To fix https://github.com/dart-lang/linter/issues/4870, the analyzer is now reporting if-statement bodies without curly braces when the if-statement condition spans multiple lines.
This change prepares zulip-flutter for this lint rule change.
=> Prepare for curly_braces lint rule change

ios/Flutter/Debug.xcconfig, ios/Flutter/Release.xcconfig, ios/Flutter/Zulip.xcconfig, ios/Runner.xcodeproj/project.pbxproj
Without this workaround iOS build currently fails with the following error:
```
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_messaging FLTFirebaseMessagingPlugin':
'/Users/rajveer/Projects/zulip-flutter/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/rajveer/.pub-cache/hosted/pub.dev/firebase_messaging-15.0.4/ios/Classes/FLTFirebaseMessagingPlugin.h:11:8
```
Upstream issue and the workaround comment:
https://github.com/firebase/flutterfire/issues/13323
https://github.com/firebase/flutterfire/issues/13323#issuecomment-2355013360
Docs: https://developer.apple.com/documentation/xcode/build-settings-reference#Allow-Non-modular-Includes-In-Framework-Modules
The documentation states that enabling this setting may result in issues …
=> ios: Add workaround for package:firebase_messaging when building with Xcode 16

lib/widgets/dialog.dart, lib/widgets/lightbox.dart
`showDialog` returns a `Future` that resolves when the dialog is dismissed.
This refactors `showErrorDialog` to stop overriding `onPressed` and `barrierIsDismissable`, and make the caller call Navigator.pop one more time once the dialog is closed.
Note that we check for `mounted` again because there has been an asynchronous gap.
See also:
https://github.com/zulip/zulip-flutter/pull/587#discussion_r1585845428
=> lightbox: Replace onDismiss with `await showErrorDialog`

pubspec.lock, pubspec.yaml
Fixes the CI failure: https://github.com/zulip/zulip-flutter/actions/runs/11063896720/job/30740794793#step:7:1899
=> deps: Upgrade Flutter SDK and `video_player_android`

lib/api/model/model.dart, lib/model/content.dart, lib/model/emoji.dart, lib/model/store.dart, lib/widgets/emoji_reaction.dart, test/example_data.dart, test/model/emoji_test.dart, test/widgets/emoji_reaction_test.dart
This is a refactoring that prepares us for #669, as well as for #388 and #670.
=> Introduce EmojiStore for some existing emoji logic

lib/widgets/content.dart, lib/widgets/message_list.dart
Fixes: #953
| --- | --- |
| <img width="675" alt="image" src="https://github.com/user-attachments/assets/13a3464f-5e87-44d2-806b-085860cc8655"> | <img width="675" alt="image" src="https://github.com/user-attachments/assets/bff27f14-d6c2-4ec3-aef3-50f159f8ac04"> |
=> msglist: Follow web's change making dark mode's --color-text-default opaque

assets/l10n/app_en.arb, lib/api/model/submessage.dart, lib/model/content.dart, lib/model/message.dart, lib/model/message_list.dart, lib/widgets/content.dart, lib/widgets/poll.dart, test/model/content_checks.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/widgets/poll_test.dart
The UI follows the webapp until we get a new design.
The dark theme colors were tentatively picked. The `TextStyle`s are the same for both light and dark theme. All the styling are based on values taken from the webapp.
References:
- light theme:
https://github.com/zulip/zulip/blob/2011e0df760cea52c31914e7b77d9b4e38e9ee74/web/styles/widgets.css#L138-L185 https://github.com/zulip/zulip/blob/2011e0df760cea52c31914e7b77d9b4e38e9ee74/web/styles/dark_theme.css#L358
- dark theme:
https://github.com/zulip/zulip/blob/2011e0df760cea52c31914e7b77d9b4e38e9ee74/web/styles/dark_theme.css#L966-L987
Fixes #165.
=> poll: Support read-only poll widget UI.

lib/api/core.dart
Before this change, the JSON response body was fully downloaded before decoding it into a Map using `jsonUtf8Decoder`. For larger response bodies, such as the `/register` endpoint on CZO (~14MB uncompressed) the CPU would often remain idle while waiting for the entire response to download before starting the decoding process.
With this change, the response byte stream is now piped directly into the `jsonUtf8Decoder` stream transformer. This allows for decoding to begin as soon as the byte stream starts emitting chunks of data (max length of 65536 bytes (64KiB) observed in my local testing).
Additionally, I ran some local benchmarks for which the code is available [here](https://gist.github.com/rajveermalviya/7b4d92f84c68f0976ed07f6d797ac164) where the response bodies of `/register` and …
=> api: Use streaming UTF-8 + JSON decoding for the response

lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/content.dart, lib/widgets/dialog.dart, lib/widgets/lightbox.dart, lib/widgets/login.dart
As a result, showErrorDialog no longer returns a Future that can be mistakenly awaited.  The wrapped return value offers clarity on how the Future is supposed to be used.
There is no user visible change because existing callers (other than lightbox's) that wait for its return value are all asynchronous handlers for UI elements like buttons, and waits unnecessarily.
See also discussion
https://github.com/zulip/zulip-flutter/pull/937#discussion_r1774377096.
=> dialog [nfc]: Wrap showErrorDialog's return value

pubspec.lock
Changelog:
https://pub.dev/packages/video_player_android/changelog
This update addresses a few bug fixes, including the removal of a flag that treats warnings as errors. Without this fix, Android builds fail in Android Studio 2024.2, which uses Java 21, with the following error:
```
…
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified
```
With this update the warnings still stay, but are ignored by build system resulting in a successful build.
=> deps: Upgrade video_player_android to 2.7.8

pubspec.lock, pubspec.yaml, test/api/core_test.dart, test/test_async.dart
This brings the file test/api/core_test.dart up to being clean against the `unawaited_futures` lint rule, toward #731.
It does so with a smaller diff, and simpler resulting code, than by adding `await` on each of the futures.  For comparison:
https://github.com/zulip/zulip-flutter/pull/934#discussion_r1788454470
=> test [nfc]: Introduce "finish" helper for async checks

android/app/src/main/kotlin/com/zulip/flutter/Notifications.g.kt, android/app/src/main/kotlin/com/zulip/flutter/ZulipPlugin.kt, lib/host/android_notifications.g.dart, lib/notifications/display.dart, pigeon/notifications.dart, test/model/binding.dart, test/notifications/display_test.dart
(Split from #717)
Needed for #340, when updating notification channels to use a custom notification sound.
=> notif: Support migration of Android notification channels

lib/api/backoff.dart, test/api/backoff_test.dart
This will let us have some backoff loops that back off more patiently than others, e.g. because their work is happening in the background and isn't expected to be something the user is already waiting for.
In particular I plan to use this for backing off the fetch of server emoji data, for #669.
=> backoff: Make duration bounds customizable

lib/api/core.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/route/realm.dart, lib/api/route/realm.g.dart, lib/model/emoji.dart, lib/model/store.dart, test/api/core_test.dart, test/api/route/realm_test.dart, test/example_data.dart, test/model/store_test.dart
Stacked atop #975.
This completes the data we'll need for use in #669.
=> Fetch server emoji data (about Unicode emoji)

lib/widgets/inset_shadow.dart, test/flutter_checks.dart, test/widgets/inset_shadow_test.dart
This casts a static shadow on top of a child widget from its top edge and bottom edge.
To review its effect, see #928. This is intended to prep for #853.
=> compose_box [nfc]: Add InsetShadowBox

pubspec.lock, pubspec.yaml
They are only used in tests.
I was reminded of this by https://github.com/zulip/zulip-flutter/pull/917#discussion_r1796280646
=> deps: Make flutter_checks and legacy_checks direct dev dependencies

test/widgets/actions_test.dart
This ensures that if one of these markNarrowAsRead calls were to change behavior so that it no longer completed within the test (and then possibly threw an error, or failed to ever complete at all), the test would catch that.
Prompted by this thread:
https://github.com/zulip/zulip-flutter/pull/934#discussion_r1796319431
=> actions test: Await all responses; cut pumpAndSettle

analysis_options.yaml, lib/model/autocomplete.dart, lib/model/store.dart, lib/notifications/display.dart, lib/widgets/action_sheet.dart, lib/widgets/content.dart, lib/widgets/login.dart, lib/widgets/message_list.dart, test/api/core_test.dart, test/api/fake_api_test.dart, test/model/channel_test.dart, test/model/store_test.dart, test/model/test_store.dart, test/notifications/display_test.dart, test/widgets/inbox_test.dart, test/widgets/lightbox_test.dart, test/widgets/login_test.dart
=> Enable unawaited_futures

lib/widgets/app.dart, lib/widgets/content.dart, lib/widgets/login.dart, lib/widgets/theme.dart, lib/widgets/unread_count_badge.dart
This addresses all the remaining items in the CZO thread at https://chat.zulip.org/#narrow/stream/48-mobile/topic/dark.20theme/near/1936853 .
=> ui: Make some dark-theme adjustments from Greg's feedback

lib/api/route/notifications.dart, lib/model/store.dart, lib/notifications/receive.dart, test/api/route/notifications_test.dart
When we originally wrote the bindings for these routes, they weren't
yet documented, so we invented our own names for them.  Now they are,
so the API docs give canonical names.  Switch to those,
and mark the `appid` parameter required as the docs say.
=> api [nfc]: Update notif-token routes based on API docs

.github/workflows/ci.yml
The `package:sqlite3` requires the system-installed sqlite3 shared library (`libsqlite3.so`) when running directly via Dart, on Linux. Whereas, when running under Flutter, it uses bundled libraries provided by `package:sqlite3_flutter_libs`.
Recently, the `ubuntu-latest` runner image has switched to defaulting to `ubuntu-24.04`:
https://github.com/actions/runner-images/issues/10636
Previously, it used `ubuntu-22.04`, which had the `libsqlite3-dev` package pre-installed:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#installed-apt-packages
However, the `ubuntu-24.04` image no longer includes this package by default:
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#installed-apt-packages
As a result, five unit tests …
=> check: Add step to install `libsqlite3-dev` system dependency

lib/model/binding.dart, lib/widgets/store.dart, test/model/binding.dart
This will be useful in the context of showing a notification, where there may not exist an element tree at all (because we may be in a background isolate), and even if there happens to be one (because we happen to be in the foreground) it doesn't otherwise relate to anything the code is doing.
Prompted by #856 (/cc @rajveermalviya).
=> store [nfc]: Offer singleton global store on binding

lib/model/store.dart, lib/widgets/store.dart, test/api/fake_api.dart, test/model/store_test.dart, test/model/test_store.dart, test/widgets/login_test.dart
This PR was split out of #948, following https://github.com/zulip/zulip-flutter/pull/948#pullrequestreview-2376668035 , toward getting things merged more efficiently.
Related: #948
=> store: Implement removeAccount

pubspec.lock, pubspec.yaml, tools/content/check-features, tools/content/fetch_messages.dart, tools/content/model.dart, tools/content/unimplemented_features_test.dart
Currently a WIP. The code needs a bit of cleanup.
=> Systematically survey message content for unimplemented features.

analysis_options.yaml, android/app/src/main/kotlin/com/zulip/flutter/Notifications.g.kt, lib/host/android_notifications.g.dart, pigeon/notifications.dart
We'd been suppressing the analyzer on Pigeon-generated code, because of an upstream issue. That issue has been fixed:
https://github.com/flutter/flutter/issues/145633
In fact it turns out it was fixed in pigeon 18.0.0, which we took in 8df306412 back in April; we just didn't notice at the time.
Meanwhile this file grew a different analyzer issue during the time it wasn't getting checked — and that one was an actual actionable one for us to fix, where a doc comment still referred to a deprecated bit of API, namely [Color.value].  So fix that too.  Glad to have the analyzer re-enabled here.
=> lint: Re-enable analyzer on Pigeon-generated code; fix one revealed issue

pubspec.lock, pubspec.yaml
Built successfully on my Android device; still need to confirm that it works on IOS.
This contains a major version bump to the dart SDK ([changelog](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#370)).
3.7.0 adds [Wildcard Variables](https://github.com/dart-lang/language/issues/3712), that we currently doesn't seem to use.
There is also changes to the Dart to Javascript Compiler (dart2js) and Dart Development Compiler (dartdevc), both are "switched to use an AOT snapshot instead of a JIT snapshot". Neither of them applies to us because we do not use the web builds.
=> deps: Upgrade Flutter to 3.27.0-1.0.pre.166

assets/l10n/app_en.arb, lib/model/store.dart, test/model/store_test.dart
Ready for review.
This fixes #555.
=> Show poll-failure details

assets/l10n/app_en.arb, lib/widgets/app.dart
This also removes the translated string as it becomes unused.
We keep the "Connected to:" line as an indicator for the current account.
Fixes: #614
=> home: Remove irrelevant information from early prototyping

lib/model/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
Fixes: #933
| Flutter | Web |
| - | - |
| <img width="751" alt="Screenshot 2024-10-23 at 20 35 38" src="https://github.com/user-attachments/assets/52a3500c-337e-4dbd-bd6b-7974cf32c018"> | <img width="751" alt="Screenshot 2024-10-23 at 20 35 54" src="https://github.com/user-attachments/assets/0b303228-2f4d-439b-abab-a4a19b74c84a"> |
=> content: Handle code block spans with multiple CSS classes

test/example_data.dart
This keeps eg.account and eg.initialSnapshot using recent versions by default.
=> test: Bump eg.recentZulipFeatureLevel and recentZulipVersion to 9.0

android/app/build.gradle, android/app/src/main/kotlin/com/zulip/flutter/Notifications.g.kt, android/app/src/main/kotlin/com/zulip/flutter/ZulipPlugin.kt, android/app/src/main/res/raw/keep.xml, assets/l10n/app_en.arb, ios/Podfile.lock, lib/api/notifications.dart, lib/api/notifications.g.dart, lib/host/android_notifications.dart, lib/host/android_notifications.g.dart, lib/model/binding.dart, lib/notifications/display.dart, lib/widgets/app.dart, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Podfile.lock, pigeon/notifications.dart, pubspec.lock, pubspec.yaml, test/api/notifications_test.dart, test/model/binding.dart, test/model/narrow_checks.dart, test/notifications/display_test.dart
=> Replace `flutter_local_notifications` with pigeon bindings

lib/api/model/events.g.dart, lib/api/model/submessage.dart, lib/api/model/submessage.g.dart, lib/api/route/submessage.dart, lib/widgets/content.dart, lib/widgets/poll.dart, test/api/route/submessage_test.dart, test/example_data.dart, test/model/message_test.dart, test/widgets/poll_test.dart
~~This is stacked on top of #912.~~
Fixes: #166
=> Support poll vote/unvote

test/example_data.dart
I noticed a bug where the value passed for the `emailAddressVisibility` in the `initialSnapshot` method in the `example_data.dart` file was not being passed down to the class but rather defaulted to `EmailAddressVisibility.everyone` even though a different value was passed. When I looked deeper into it, I noticed that they forgot to add the override. This PR adds a fix for that. There isn't an open issue for this yet, so I am unable to link to it.
Please review when available.
Thank you.
=> initial_snapshot: Add emailAddressVisibility override in InitialSnapshot method

lib/model/content.dart, test/model/content_test.dart
=> content: Handle message links

lib/model/binding.dart, lib/model/store.dart, lib/model/typing_status.dart, lib/widgets/compose_box.dart, test/model/binding.dart, test/model/typing_status_test.dart, test/widgets/action_sheet_test.dart, test/widgets/autocomplete_test.dart, test/widgets/compose_box_test.dart, test/widgets/message_list_test.dart
Follow-up to and stacked on top of #888
Fixes: #666
=> Support setting typing status

pubspec.lock
An upstream change breaks our build by adding a method to Color;
this takes the corresponding update to package:flutter_color_models
that implements the method and so fixes our build.
Details in #1052, and in a chat thread:
https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/tools.2Fcheck.20CI.20failure.20on.20main/near/1976890
and a Discord thread I started upstream:
https://discord.com/channels/608014603317936148/608021010377080866/1303869787365179422
Upgrade done with the following command:
$ flutter pub upgrade color_models flutter_color_models
Fixes: #1052
=> deps: Upgrade flutter_color_models to fix build

lib/widgets/action_sheet.dart, test/widgets/action_sheet_test.dart
This was prompted by my comment at https://github.com/zulip/zulip-flutter/pull/1041#discussion_r1828562960 (/cc @PIG208). But then as I got into this code I found some other small cleanups to make, and also spotted a couple of bugs to fix.
action_sheet [nfc]: Rename pageContext field on button widgets
Most of the ways we use this field (specifically, all the ways we
use it other than in findMessageListPage) aren't related to it
being the message list in particular.
When we add action sheets other than the message action sheet,
they'll still need a page context.  So prepare the way for those
by giving this a name that can generalize.
---
action_sheet [nfc]: Avoid passing footgun context to onPressed methods
The usual Flutter idiom, which we use across the rest of the app,
would call for …
=> Clarify action sheet's "page context"; fix small bugs

test/widgets/compose_box_test.dart
This gives more vertical space above the compose box.  This will provide enough space for the autocomplete to appear without overflowing when we add tests for it.
This should be useful for both #928 and #1033. It doesn't aim to reproduce the exact things we do with `MessageListPage`.
| before | after |
| - | - |
| ![image](https://github.com/user-attachments/assets/8be03a3e-6ada-4e1d-8630-f28599d9395f) | ![image](https://github.com/user-attachments/assets/313b4d8c-a410-4453-af9e-98f06d12af86) |
=> compose_box test: Use a layout similar to the message list page

assets/l10n/app_en.arb, lib/api/route/notifications.dart, lib/notifications/receive.dart, lib/widgets/actions.dart, lib/widgets/app.dart, lib/widgets/dialog.dart, lib/widgets/page.dart, lib/widgets/store.dart, test/api/route/notifications_test.dart, test/model/test_store.dart, test/widgets/actions_test.dart, test/widgets/app_test.dart, test/widgets/dialog_checks.dart
These are the three last commits from #948, following up on the just-merged #1007 to replace #948: https://github.com/zulip/zulip-flutter/pull/948#pullrequestreview-2376668035
The screenshots in #948's description still match this code. As I said on #948, there might be some improvements to make to the UI, perhaps as a followup: https://github.com/zulip/zulip-flutter/pull/948#issuecomment-2423253936
Fixes: #463
=> login: Support logging out of an account (take 2)

integration_test/unreadmarker_test.dart, test/example_data.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/widgets/action_sheet_test.dart, test/widgets/message_list_test.dart
Shared by a few tests, they fit better in example_data.
Inspired by https://github.com/zulip/zulip-flutter/pull/1044#discussion_r1831997129
=> example_data [nfc]: Move {newest,older}Result

docs/release.md, tools/bump-version
This is adapted from the tools/bump-version in zulip-mobile.
=> tools: Add bump-version, simplifying a release step

.gitattributes, docs/translation.md, l10n.yaml, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/model/localizations.dart, lib/notifications/display.dart, lib/widgets/about_zulip.dart, lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/content.dart, lib/widgets/dialog.dart, lib/widgets/lightbox.dart, lib/widgets/login.dart, lib/widgets/message_list.dart, lib/widgets/poll.dart, lib/widgets/profile.dart, lib/widgets/recent_dm_conversations.dart, pubspec.lock, pubspec.yaml, test/widgets/test_app.dart, tools/check
`flutter` tool deprecated the `package:flutter_gen` synthetic package:
https://flutter.dev/to/flutter-gen-deprecation
The generated localization source files are now included in the
repository and referenced directly.
Without this change, `flutter run` generates the following warning:
```
Synthetic package output (package:flutter_gen) is deprecated:
https://flutter.dev/to/flutter-gen-deprecation. In a future
release, synthetic-package will default to `false` and will
later be removed entirely.
```
=> intl: Migrate from `package:flutter_gen`; include generated files

assets/l10n/app_en.arb, lib/api/exception.dart, lib/api/model/events.dart, lib/api/model/events.g.dart, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/model/store.dart, test/example_data.dart, test/model/store_test.dart
This is a bit of a long branch, as I ended up going into a variety of related cleanups and other prep work.
Fixes: #563 
Selected commit messages:
---
store: On rate-limit error in poll, explicitly back off and retry
This covers a particular case of #946.
This commit is actually NFC as far as the interaction with the server
goes; its only change in behavior is that we treat the error as
"expected", and therefore skip reporting it to the user unless it
follows a string of other errors.
But then this also sets us up so that these rate-limit errors will
continue to be handled with backoff-retry when we change the handling
of unexpected errors, coming next.
---
store: Handle unexpected event-poll errors by reloading store, with backoff
This fixes #563.  We'll follow up with a few more commits …
=> Comprehensively retry event-poll failures

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/channel.dart, lib/model/store.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/example_data.dart
This field is becoming a group-setting value.  We haven't yet
implemented those (that's #814), so we can no longer handle this field
until we do that work.  Conveniently we weren't actually making any
use of this field, though -- so for now, just ignore it.
Fixes: #1082
=> api: Cut ZulipStream.canRemoveSubscribersGroup as it changes format

lib/model/autocomplete.dart, lib/model/emoji.dart, lib/model/store.dart, lib/widgets/autocomplete.dart, lib/widgets/emoji.dart, lib/widgets/emoji_reaction.dart, test/model/autocomplete_checks.dart, test/model/autocomplete_test.dart, test/model/emoji_test.dart, test/widgets/autocomplete_test.dart
This adds autocomplete for emoji in the compose box, so e.g. typing `:zu` offers an autocomplete option of `:zulip:`.
The first part of the branch makes some refactors to the autocomplete subsystem, in order to prepare to accommodate emoji autocomplete alongside @-mention autocomplete. The changes are all in basically the direction we had in mind when initially building the system; mostly we left some concepts collapsed that we knew we'd eventually need to separate, deferring the details of actually separating them until we had a concrete situation where they came apart.
Fixes: #669 
Fixes: #670
autocomplete [nfc]: Document how query, view-model, and results classes relate
---
autocomplete [nfc]: Separate ComposeAutocompleteQuery/Result from Mention-etc.
The two concepts have meant the …
=> Emoji autocomplete

lib/model/content.dart, lib/widgets/content.dart, test/flutter_checks.dart, test/model/content_test.dart, test/widgets/content_test.dart
Fixes: #360 
| Flutter | Web |
| - | - |
| <img width="763" alt="Screenshot 2024-10-29 at 01 50 02" src="https://github.com/user-attachments/assets/1e4422ff-954c-4f52-9428-6af9720731d6"> | <img width="929" alt="Screenshot 2024-10-29 at 01 37 36" src="https://github.com/user-attachments/assets/4326b345-08fc-4fa2-a580-89ce376535fb"> |
=> content: Handle `<table>` elements

lib/model/content.dart
This gives us more breathing room for making this handling more
complicated, as we'll need for the new "channel-wildcard-mention"
class (#1064) and for distinguishing different types of mentions (#646, #647).
Prompted by:
https://github.com/zulip/zulip-flutter/pull/1073#discussion_r1857421404
(/cc @sm-sayedi, @PIG208).
=> content [nfc]: Pull out parseUserMention, give regexp less to do

lib/widgets/action_sheet.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart, lib/widgets/theme.dart, test/widgets/action_sheet_test.dart, test/widgets/compose_box_test.dart
Prompted by reviewing Zixuan's #924, this is meant to make the compose-box code better prepared for that work than it is in `main`; details at https://github.com/zulip/zulip-flutter/pull/924#pullrequestreview-2450028109 and in the commits.
Please let me know as soon as anything doesn't look clear. I'm tired (it's almost bedtime 🙂) but I've spent a while on this and I wanted to get it in today if possible. Since this makes a UI change, screenshots coming soon.
Fixes: #1089
=> compose: Refactor some logic; implement redesigned error banner

lib/model/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
For channel wildcard mentions, the class in the corresponding HTML used to be the same as the user mentions (`class="user-mention"`), but now there's an additional class added. Now it looks like the following: `class="user-mention channel-wildcard-mention"`.
Fixes: #1064
=> content: Support the new class of channel wildcard mentions

lib/widgets/content.dart, lib/widgets/emoji.dart, lib/widgets/text.dart, test/widgets/content_test.dart, test/widgets/emoji_reaction_test.dart
One of the two main commits here I cherry-picked from @rajveermalviya's #1103, and then wrote a test for.
Fixes: #1104 
emoji: Use "Apple Color Emoji" font on iOS/macOS for UnicodeEmojiWidget
Some unicode characters, like U+2764 (❤) or U+00AE (®) can
have glyphs in non-Emoji fonts, resulting in incorrect
rendering of such characters, where we specifically want an
emoji to be displayed.
So, explicitly mention "Apple Color Emoji" to be the font used on
iOS/macOS for displaying the unicode emoji.
This resolves part of #1104, namely for reaction chips
and autocomplete results.
[greg: wrote test]
Fixes-partly: #1104
---
content: Use emoji font to show emoji nodes
For emoji like ❤ U+2764 HEAVY BLACK HEART, this causes us to show a
colorful, larger glyph like ❤️ from the emoji font, instead of a …
=> Use emoji font to show explicit emoji

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart
Some of these were a bit hard to parse.
Also make them somewhat more parallel to each other.
Prompted by: https://github.com/zulip/zulip-flutter/pull/1076#discussion_r1874151721
=> i18n [nfc]: Adjust "page title" string descriptions for clarity

tools/icons/build-icon-font.js
The custom icon entries in "ZulipIcons.dart" used to be generated/sorted based on the default OS order of the related ".svg" files in "assets\icons" directory. This default order behavior is different in different platforms (Windows vs. Linux or macOS) thus resulting in inconsistent output of "ZulipIcons.dart".
This PR adds an explicit sorting mechanism; so the output is consistent across different platforms.
Fixes: #1110
=> tools: Make `ZulipIcons` results explicitly sorted

lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/autocomplete.dart, lib/model/emoji.dart, lib/model/store.dart, test/example_data.dart, test/model/emoji_test.dart, test/model/store_checks.dart
Fixes #1113.
The first commit (toString on some emoji-related data classes) is shared with #1112.
When combining with #1112, the three new test cases will each need a tweak like this one:
```diff
check(store.allEmojiCandidates()).deepEquals([
+        ...arePopularCandidates,
```
just like #1112 itself does (in its last commit) for several existing test cases.
It's a bit of a trap for the unwary (... like me last month, in
ecd2cb5d4, causing #1113), because it includes deactivated realm emoji
as well as active ones.
This way the binding encapsulates an important fact about this
bit of the API -- namely that these values are the same as the
"emoji code" values seen elsewhere in the API -- so that we don't
have to re-verify it when working elsewhere in the codebase and
using this class. …
=> Exclude deactivated realm emoji from autocomplete

.github/workflows/ci.yml, ios/Podfile.lock, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/api/model/model.g.dart, lib/model/database.g.dart, lib/notifications/receive.dart, macos/Podfile.lock, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, pubspec.lock, pubspec.yaml, test/model/schemas/schema_v1.dart, test/model/schemas/schema_v2.dart, tools/check, tools/lib/git.sh, tools/upgrade
Fixes #1118.
Fixes #1119.
This upgrades Flutter and some of our other dependencies.
OTOH `firebase_core` and the other Firebase packages can't immediately be upgraded; I ran into #1116, which I just filed. So hold those back.
And at the start of the branch, I augment `tools/upgrade` a bit so that it records the actual commit ID in the Flutter tree in a comment in pubspec.yaml, and give `tools/check` a tiny new suite `flutter_version` that validates that information.
On several occasions I've wanted the ability to look back and see what Flutter commit was used in a given published (beta) release, in particular. I already make a practice of doing so with the exact minimum version recorded in `pubspec.yaml`, in order to make it reproducible; but it's somewhat annoying to identify that commit …
=> Upgrade Flutter and packages; hold back firebase_core; record Flutter commit IDs

lib/model/algorithms.dart, lib/model/autocomplete.dart, lib/model/emoji.dart, test/model/algorithms_test.dart, test/model/emoji_test.dart
Fixes #1068.
As is, this PR applies to the results of autocomplete in the compose box (when you type a colon `:`). In combination with #1103 adding an emoji picker, it applies to the results in the emoji picker too, because that PR reuses the same autocomplete machinery.
This mimics the ranking in the web client (from [shared/src/typeahead.ts](https://github.com/zulip/zulip/blob/83a121c7e4f365d8253db251b072d0a034b87d4d/web/shared/src/typeahead.ts)) with a handful of small discrepancies. Almost all are (minor) bugs in web:
```dart
// Behavior differences we might copy, TODO:
//  * Web ranks each name of a Unicode emoji separately.
//  * Web recognizes a word-aligned match starting after [ /-] as well as [_].
//
// Behavior differences that web should probably fix, TODO(web):
//  * Among …
```
=> Rank emoji results in autocomplete

lib/widgets/action_sheet.dart
Taken from #1041.
Other PRs that rely on this:
- #1103
- #1076
Requested by @gnprice [here](https://github.com/zulip/zulip-flutter/pull/1041#issuecomment-2530404897).
=> Series of prep commits for topic action sheet related changes

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_fr.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/widgets/action_sheet.dart, lib/widgets/app.dart, lib/widgets/app_bar.dart, lib/widgets/home.dart, lib/widgets/inbox.dart, lib/widgets/login.dart, lib/widgets/page.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, lib/widgets/theme.dart, test/flutter_checks.dart, test/model/test_store.dart, test/notifications/display_test.dart, test/widgets/action_sheet_test.dart, test/widgets/actions_test.dart, test/widgets/app_test.dart, test/widgets/home_test.dart, test/widgets/inbox_test.dart, test/widgets/login_test.dart, test/widgets/recent_dm_conversations_test.dart, test/widgets/subscription_list_test.dart
This is stacked on top of some commits cherry-picked from #1041:
* action_sheet [nfc]: Use a generalized name for the cancel button
* action_sheet [nfc]: Extract ActionSheetMenuItemButton
See also: [CZO discussion](https://chat.zulip.org/#narrow/channel/48-mobile/topic/Buttons.20on.20the.20bottom.20tabs.20and.20main.20menu)
<details>
<summary>Screenshots</summary>
| light | dark |
| - | - |
|  ![1000015700](https://github.com/user-attachments/assets/2025dbbb-b4b5-4069-b7c5-0881e853297e) | ![1000015702](https://github.com/user-attachments/assets/7fedf362-ec97-4e05-bcd6-93482a8e3b02) |
| ![1000015701](https://github.com/user-attachments/assets/e0473062-3e27-4058-b967-1713dd2e72cc) | ![1000015703](https://github.com/user-attachments/assets/c94976ba-9aff-4dc6-bf6a-e8d663ad59a6) |
</details> …
=> Implement bottom tabs and main menu

lib/api/backoff.dart, lib/model/message_list.dart, test/model/message_list_test.dart
This approach is different from how a BackoffMachine is typically used,
because the message list doesn't send and retry requests in a loop; its
caller retries rapidly on scroll changes, and we want to ignore the
excessive requests.
The test drops irrelevant requests with `connection.takeRequests`
without checking, as we are only interested in verifying that no request
was sent.
Fixes: #945
=> msglist: Throttle fetchOlder retries

lib/model/internal_link.dart, test/model/compose_test.dart, test/model/internal_link_test.dart
Meanwhile, reorganized some test groups with the same name.
Supersedes: #874
Fixes: #845
=> internal_link: Always include a "/" after hostname

.gitattributes
This way these don't produce giant diffs, by default, when comparing versions of the tree across a sync of translations from Weblate.
=> l10n [nfc]: Treat Weblate-derived data as generated in Git diffs

lib/model/database.dart
This has been addressed in Greg's upstream PR: https://github.com/simolus3/drift/pull/3022
=> db [nfc]: Remove handwritten copy of copyWithCompanion

.github/workflows/ci.yml
Fixes #1177.
Workaround for:
* https://github.com/flutter/flutter/issues/160558
=> Work around broken ref for Flutter upstream main

.github/workflows/ci.yml
Fixes #1177, take 2.
The original hacky workaround subsequently broke after the upstream change that fixed the "upstream" vs. "origin" part of the issue. We still need a version of this workaround, though, because we clone the repo with the branch `main`, which in the Flutter repo always points to the same commit as `master`.
=> ci: Update workaround for broken ref for Flutter upstream main

lib/model/store.dart
This is a follow-up to #1063 — it's very lightly revised from commits that were in my draft branch leading to that PR, and which I left out at the time because the PR was getting long and complex enough already.
In this PR, factoring this logic out of the [UpdateMachine.poll] method isn't for the sake of deduplicating anything: the methods the logic gets moved into are still private helpers tuned specifically for the needs of that method. But it allows that method to get quite a lot shorter, so its overall structure is more apparent. And it also allows each of the two phases of error-handling to be read in a bit more of a self-contained context, by having them in their own methods.
=> Factor error-handling out of poll method

android/.gitignore
Starting with our last Flutter update 273674f37 (#1184), a directory android/app/.cxx/ gets created whenever building or running the app for Android.  It has a lot of generated files in it.
See chat discussion:
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/Error.20in.20running.20the.20app/near/2017805
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/.2Ecxx.2F.20files.20created/near/2017819
There's an upstream issue for the need to add a gitignore line for these in the `flutter create` templates:
https://github.com/flutter/flutter/issues/160372
Even when that's done, it won't affect existing apps like ours; we need to make a similar update in our own tree.  That's this commit.
=> gitignore: Ignore CMake directory generated on Android build

lib/model/message_list.dart, test/model/message_list_test.dart
Topics in Zulip are case-insensitive. This change makes the message list's topic headers match that behavior, so messages whose topics differ only in case (like "missing string" and "Missing string") share a single header.  This brings the behavior in line with Zulip web.
The change modifies the topic comparison logic in `haveSameRecipient()` to use case-insensitive comparison when determining whether to show a new recipient header.
| Before                                                                                       | After                                                                                        |
|---------------------------------------------------------------------------------------------|---------------------------------------------------------------------------- …
=> Make topic headers case-insensitive

test/widgets/compose_box_test.dart
The `attach from camera` test fails on
Windows due to the the path separator
used in the split function of the XFile.name
getter in `cross_file` being `\` instead of `/`.
This results in the getter returning the
entire path on Windows instead of the
last word present after the last '/' in the path.
Read this excellent explanation by
@chrisbobbe for better understanding:
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/failing.20composebox.20test.20while.20running.20check.20script/near/2000301
=> compose: Skip failing test for windows.

lib/model/unreads.dart, test/model/unreads_test.dart
In manual testing for my work on resolve/unresolve #744, I noticed some surprising debug-log lines that turned out to be false positives, so this fixes those.
It also makes the debug check run in a helpful case where it wasn't running before.
=> unreads: Fix false positives in a debug check; log in another case when helpful

lib/widgets/lightbox.dart, test/widgets/lightbox_test.dart
In the lightbox, the RN app shows the message author's avatar along with their name in the app bar. This change implements the same behavior in the Flutter app, positioning the avatar beside the name/date text in the "start" direction (left in LTR layouts, right in RTL layouts).
The changes:
- Add Avatar widget in the lightbox app bar next to the author's name and date
- Ensure the avatar is positioned correctly based on the text direction (LTR/RTL)
- Maintain consistent sizing and spacing (35px size, 8px right padding)
- Handle overflow gracefully for both avatars and names
Screenshot-
Fixes #41
=> lightbox: Added user's avatar in the lightbox app bar

lib/widgets/theme.dart, test/widgets/home_test.dart, test/widgets/theme_test.dart
Nicer to compute each of these just once.
=> theme [nfc]: Make DesignVariables.{light,dark} final fields, not constructors

test/widgets/autocomplete_test.dart
The fixes to RawAutocomplete's options width in the flutter framework (https://github.com/flutter/flutter/pull/143249) introduces a frame delay, so this test requires an extra pump to account for that.
=> Fix failing tests for RawAutocomplete

lib/model/content.dart
This series of commits has a few small refactors of the content-parsing code, prompted by #1156.
@rajveermalviya feel free to rebase #1156 atop this if it seems helpful — the last two commits in particular might simplify that PR a bit. If the conflict resolution seems more annoying than the refactor is helpful, no need, and I can resolve it after either PR is merged.
content [nfc]: Split out _ZulipInlineContentParser class
This helps organize the parsing code a bit more cleanly -- not to
mention more statically, by making the dynamic _debugParserContext
assertions redundant.
---
content [nfc]: Encapsulate parsing math nodes a bit more
---
content [nfc]: Factor out consumeImageNodes in block-content parse loops
This hopefully makes the logic of these loops a bit more readable.
=> Split inline from block parser class, and other small refactors

lib/api/exception.dart, lib/model/store.dart
Like #1187, this is a follow-up to #1063. It's a thought I had while working on those changes, but didn't pursue then because the PR was long and complex enough already.
We're about to group the others together under a new sibling of
this class, so it'll be cleanest if this one doesn't appear in the
midst of the others.
This expresses more directly what we really mean here: if the
response had either the HTTP status code or the Zulip API error code
that mean a rate-limit error, treat it as a rate-limit error.
=> Unify httpStatus field on ApiRequestException subclasses

test/widgets/autocomplete_test.dart
=> autocomplete test: Add extra pump in new test for new RawAutocomplete delay

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/api/route/messages.dart, lib/api/route/messages.g.dart, lib/widgets/action_sheet.dart, lib/widgets/inbox.dart, lib/widgets/message_list.dart, test/api/model/model_test.dart, test/api/route/messages_test.dart
My local branch for #744 has gotten pretty long and I think it'll benefit from being split into multiple PRs. 🙂 Here's one.
=> Mark as resolved/unresolved prep 1

lib/widgets/emoji_reaction.dart, lib/widgets/message_list.dart, lib/widgets/theme.dart, test/widgets/emoji_reaction_test.dart, test/widgets/message_list_test.dart
Followup to https://github.com/zulip/zulip-flutter/pull/1236#issuecomment-2576750264:
> We should be able to apply this to MessageListTheme and etc., right?
We can, for `MessageListTheme` and `EmojiReactionTheme`, but not for `ContentTheme` because the light and dark variants need a `BuildContext`.
=> Make {MessageList,EmojiReaction}Theme.{light,dark} static final fields

lib/api/route/messages.dart, lib/widgets/compose_box.dart, test/widgets/app_test.dart, test/widgets/compose_box_test.dart, test/widgets/dialog_checks.dart
Fixes #1238.
Done by computing `String.runes` (the number of Unicode code points) unless we know that the result can't exceed the threshold number of code points. In particular, we don't compute it unless `String.length` (the number of UTF-16 code units) exceeds the threshold number of code points.
=> compose: Enforce max topic/content length by code points, following API

lib/widgets/subscription_list.dart, test/widgets/subscription_list_test.dart
Update the channel sorting logic to ensure streams with leading emojis in their names are listed above those without emojis. The updated sorting respects pinned, muted, and unmuted streams while handling emoji precedence and maintaining alphabetical order for ties.
Fixes: #1202
=> home: Sort leading emoji first in channel names

lib/widgets/app_bar.dart, lib/widgets/message_list.dart, test/widgets/actions_test.dart, test/widgets/app_bar_test.dart, test/widgets/test_app.dart
And make `TestZulipApp` more helpful, too, since I noticed an opportunity for that.
=> app_bar [nfc]: Centralize _getEffectiveCenterTitle in our wrapper

tools/customer-testing/setup.sh
Earlier I'd tried adding this "apt install" command directly in the test registry, as a "setup" line in the "zulip.test" file:
https://github.com/flutter/tests/pull/441
But the Flutter "customer testing" suite gets run in two different environments; and it turns out that not only does the LUCI environment not need this step (the Zulip tests there were working fine right up until they were disabled last week due to the failures in GitHub Actions), but it also doesn't permit it: there's no access to `sudo`:
https://discord.com/channels/608014603317936148/1290464157765865552/1331449169830871122
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20customer_testing/22301/overview
Error output (reformatted):
Processing ./../../bin/cache/pkg/tests/registry/zulip.test...
>> sudo apt install …
=> ci: Add setup script for running in Flutter "customer testing"

lib/widgets/home.dart, test/widgets/home_test.dart
We could pass realmUrl when initializing the `_LoadingPlaceholderPage`, but that will still require a check for the existence of the account.
The loading page will be blank when the account does not exist. The user can't easily reach this page because they can only logout from `ChooseAccountPage`, until we start invalidating API keys. Even then, they will only see the blank page briefly before getting navigated, so we should not show any text at all.
<details>
<summary>Screenshot</summary>
</details>
Fixes: #1219
=> home: Stop assuming account existence from loading page

.github/workflows/ci.yml, pubspec.lock, pubspec.yaml
=> deps: Upgrade Flutter to 3.29.0-1.0.pre.105 and reinstate `--depth=1000`

test/widgets/action_sheet_test.dart, test/widgets/inbox_test.dart, test/widgets/message_list_test.dart
Here are the commits from #1301 that are just about refactoring the action-sheet tests. I've revised them for Zixuan's review https://github.com/zulip/zulip-flutter/pull/1301#pullrequestreview-2573663606 ; in particular by just removing an `assert(() {}())` wrapper (which isn't needed because it's only running in tests).
=> Mark as resolved/unresolved prep 2

lib/widgets/message_list.dart, test/widgets/message_list_test.dart
**Summary**
This PR updates the behavior of recipient headers in the single-conversation view to make them non-tappable.
**Related Issue:** #1171 
**Changes:**
**Adjusted GestureDetector logic:**
Updated the logic to conditionally enable navigation only when relevant.
**Simplified ColoredBox structure:**
Streamlined the layout for non-tappable headers to ensure consistent behavior and appearance.
**Video Demonstration:**
https://github.com/user-attachments/assets/4cad0f37-ff48-4f3e-bb6b-30555addee30
=> msglist: In single-conversation view, make recipient headers not tappable.

lib/widgets/compose_box.dart, lib/widgets/theme.dart, test/widgets/compose_box_test.dart
This PR will update the top border and add shadow effect to the top of the compose box to make it more visible in dark mode
For reference, see the Figma design:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=5908-64038&t=alSmAmdRXFDwT4IT-1
Fixes: #1207
| Before                                    | After                                     |
|-------------------------------------------|-------------------------------------------|
|![WhatsApp Image 2024-12-29 at 2 28 00 PM](https://github.com/user-attachments/assets/8df21c34-da32-42fc-be08-e44a732655ac) | ![WhatsApp Image 2024-12-29 at 2 28 01 PM](https://github.com/user-attachments/assets/6d6b4942-0f60-4118-981e-51848524cd19) |
=> compose: Make compose-box border more prominent in dark mode

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/model/compose.dart, lib/notifications/display.dart, lib/widgets/action_sheet.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/content.dart, lib/widgets/emoji_reaction.dart, lib/widgets/inbox.dart, lib/widgets/lightbox.dart, lib/widgets/message_list.dart, lib/widgets/poll.dart, lib/widgets/profile.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, test/model/compose_test.dart, test/widgets/action_sheet_test.dart
=>  Sweep through UI strings to internationalize

android/gradle.properties
Fixes #1330.
Recently, we have been running out of memory for the CI builds. It's likely that we were close to reaching the upperbound for some time, and some upstream change pushes us past that limit. Allocate more memory so that the CI can pass again.
CZO discussion:
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/Execution.20failed.20for.20task.20'.3Aapp.3AcompileDebugKotlin'
=> android build: Allow gradle to use more memory

lib/notifications/display.dart, lib/widgets/content.dart, lib/widgets/lightbox.dart, lib/widgets/message_list.dart, lib/widgets/profile.dart
Toward #277.
Background: https://github.com/zulip/zulip-flutter/issues/277#issuecomment-2638297174
=> i18n: Add and update TODO markers after a sweep

android/gradle.properties
Will trigger the CI with this.
=> Attempt to fix JVM high memory usage in CI

lib/example/sticky_header.dart, lib/widgets/sticky_header.dart, test/widgets/sticky_header_test.dart
Fixes #1309.
Fixes #725. (which is the same underlying bug)
In addition to that live bug in the app (involving scrollOffsetCorrection, which we previously weren't handling), the last two commits in this branch fix a couple of bugs in the `sticky_header` library that were latent bugs in the app — they can only trigger once we start having two slivers share space in the list. That's a scenario we'll need as part of #80 / #82, as seen for example in #1169 (fyi @rajveermalviya).
Specifically, when both slivers are visible, the version in main
* will fail to show the sticky header for the top sliver;
* and will show a sticky header for the bottom sliver.
After this PR, there's one remaining bug I'm aware of that affects sticky headers in the presence of multiple slivers: ~~if the top sliver …
=> anchors 2/n: Fix three sticky-header bugs

assets/l10n/app_en.arb, assets/l10n/app_pl.arb, assets/l10n/app_ru.arb, assets/l10n/app_sk.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/licenses.dart, lib/widgets/about_zulip.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/login.dart
=> Wrap up translating all strings

lib/notifications/display.dart, lib/widgets/app.dart, lib/widgets/home.dart, lib/widgets/message_list.dart, lib/widgets/page.dart, lib/widgets/profile.dart, test/notifications/display_test.dart, test/widgets/page_checks.dart
Previously, when two accounts (Account-1 and Account-2) were logged in, the app always defaulted to showing the home page of Account-1 on launch. If the app was closed and the user opened a notification from Account-2, the navigation stack would be:
HomePage(Account-1) -> MessageListPage(Account-2)
This commit fixes that behaviour, now when a notification is opened while the app is closed, the home page will correspond to the account associated with the notification's conversation.
This addresses #1210 for background notifications.
=> notif: Use associated account as initial account; if opened from background

docs/setup.md
I ran into this recently when I tried running the Linux app.
(It looks like the reason I hadn't seen it before is that until recently I had this package installed; it was installed "automatically", i.e. only because it was a dependency of something else, and then I upgraded my machine, it was no longer such a dependency, and got autoremoved.  Now that I've installed it directly, it'll stay.)
=> doc: Add libdrm troubleshooting entry

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/widgets/message_list.dart
=> msglist: Update label to 'Messages with yourself' in DM header

lib/example/sticky_header.dart, lib/widgets/sticky_header.dart, test/widgets/sticky_header_test.dart
This is the next round after #1312 (and is stacked atop #1312), fixing another cluster of latent bugs in the sticky_header library to prepare for having two slivers share space back to back in the list.
After #1312, the headers paint correctly in that case. But when the sliver boundary is scrolled to within the header, the hit-testing behavior isn't yet right: trying to tap on the bottom part of the header, where it's overflowing over the bottom sliver, ends up hitting the bottom sliver instead of the header. This PR fixes that.
… Well, it does if the viewport gives the slivers the right paint order (and hit-test order). Making that happen with back-to-back slivers, like the message list needs, requires some more code; and this PR is long enough already. So we'll save that for the next …
=> anchors 3/n: Fix hit-testing when header overflows sliver

lib/model/content.dart, test/model/content_test.dart
=> content: Handle multiple math blocks in `<p>`

lib/widgets/message_list.dart
Fixes: #1247
| Before                                    | After                                     |
|-------------------------------------------|-------------------------------------------|
| ![WhatsApp Image 2025-01-03 at 9 21 11 AM](https://github.com/user-attachments/assets/accb34c1-d7b1-4497-aa50-fd8842549eec) | ![WhatsApp Image 2025-01-03 at 9 21 11 AM(1)](https://github.com/user-attachments/assets/a9fc4ec8-804b-4208-81db-34f948e10b12) |
=> msglist: Move star icon 2px away from the edge of the screen

lib/api/exception.dart, test/example_data.dart, test/model/actions_test.dart
The second commit adds the example-data helper I mentioned in the review comment https://github.com/zulip/zulip-flutter/pull/1183#discussion_r1955516825 (/cc @PIG208). The first commit is a small prep cleanup which the second change caused me to notice.
These three keys appear in the server's JSON for error responses, but
get pulled out into their own dedicated fields in ZulipApiException.
(See the field's doc, and the constructor's one non-test call site.)
The assertion is useful for tests, for keeping test data realistic.
Fix the two test cases that had missed this nuance.
Prompted by seeing we'll need more copies of this soon:
https://github.com/zulip/zulip-flutter/pull/1183#discussion_r1955516825
=> Support example API exceptions a bit better

test/api/core_test.dart, test/api/fake_api.dart, test/api/fake_api_test.dart, test/api/route/messages_test.dart, test/example_data.dart, test/model/actions_test.dart, test/model/message_list_test.dart, test/model/store_test.dart, test/stdlib_checks.dart, test/widgets/action_sheet_test.dart, test/widgets/actions_test.dart, test/widgets/compose_box_test.dart, test/widgets/emoji_reaction_test.dart, test/widgets/message_list_test.dart
Stacked atop #1355. Prompted by this review thread (thanks @chrisbobbe for the observation):
https://github.com/zulip/zulip-flutter/pull/1355#discussion_r1956718605
And leave a couple of TODO comments in the one test file that was
accidentally preparing exceptions here that won't turn out in the
intended way.  The next commit will provide a clean way for these
tests to do what they intend instead.
This changes the message string in a few of the call sites, where
the string was already an arbitrary one rather than a realistic
specific string.  That's still NFC because the tests weren't
depending on the specific string.
=> fake_api: Prepare API exceptions conveniently, distinct from HTTP exceptions

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/log.dart, lib/model/store.dart, lib/widgets/app.dart, lib/widgets/login.dart, test/example_data.dart, test/model/store_test.dart, test/model/test_store.dart, test/stdlib_checks.dart, test/widgets/app_test.dart, test/widgets/message_list_test.dart, test/widgets/store_test.dart
~~This is near term fix for a user-reported issue:
https://chat.zulip.org/#narrow/channel/48-mobile/topic/0.2E0.2E19.20Flutter.20.3A.20Cant.20connect.20to.20self.20hosted.20instance/near/2004042~~
~~It is not intended to be the full fix.  With a better UX, we would bring the user back to the choose-account page without them manually doing so.  That's covered by #737 but out-of-scope for this commit.~~
This cherry-picks https://github.com/zulip/zulip-flutter/pull/1235, and partially addresses #890, by handling `INVALID_API_KEY` errors from the `PerAccountStoreWidget`.
Fixes: #737
=> store: Handle invalid API key on register-queue

lib/widgets/home.dart
Resolves [#1246](https://github.com/zulip/zulip-flutter/issues/1246).
=> home: Center align the "try another account" message in loading placeholder

lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/message_list.dart, test/widgets/actions_test.dart
This makes it explicit at each call site that the method being called
is an action, not (for example) an API endpoint binding.  The
difference is important in particular because it affects how --
really, whether -- the caller should handle errors.
See discussion from when the similarity in appearance to API endpoint
bindings caused confusion:
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/.23F1317.20showErrorDialog/near/2080570
Also document the two methods here (other than the private helper) that didn't already have docs.
=> actions [nfc]: Namespace actions as statics on a ZulipAction class, and document

lib/widgets/compose_box.dart
Ever since 5827512af made the text input's controller start memoizing `textNormalized` as part of its own state, there's nothing to gain by keeping a copy of it on the widget state too.
=> compose [nfc]: Simplify content-input state, deduplicating topic text

lib/api/model/narrow.dart, lib/api/route/messages.dart, lib/model/internal_link.dart, lib/model/message_list.dart, lib/model/narrow.dart, lib/widgets/message_list.dart, test/api/model/narrow_test.dart, test/api/route/messages_test.dart, test/example_data.dart, test/model/internal_link_test.dart, test/model/message_list_test.dart, test/model/narrow_checks.dart, test/widgets/message_list_test.dart
=> msglist: Follow /with/ links through message moves

assets/l10n/app_en.arb, assets/l10n/app_pl.arb, assets/l10n/app_ru.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/widgets/compose_box.dart, test/widgets/compose_box_test.dart
Prepares for:
- #1297
| mandatory topics | non-mandatory topics |
| - | - |
| ![pre-334, mandatory](https://github.com/user-attachments/assets/6ab6c74d-e797-4b05-b696-12d40fe59cde) | ![Screenshot_20250211_143906](https://github.com/user-attachments/assets/9f82087f-50b4-46ad-8006-9203e71b8329) |
=> Get compose box hint texts ready for general chat

lib/model/autocomplete.dart, lib/model/compose.dart, lib/model/internal_link.dart, lib/model/store.dart, lib/model/user.dart, lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/autocomplete.dart, lib/widgets/compose_box.dart, lib/widgets/content.dart, lib/widgets/emoji_reaction.dart, lib/widgets/inbox.dart, lib/widgets/lightbox.dart, lib/widgets/message_list.dart, lib/widgets/poll.dart, lib/widgets/profile.dart, lib/widgets/recent_dm_conversations.dart, test/model/autocomplete_test.dart, test/model/compose_test.dart, test/model/emoji_test.dart, test/model/store_checks.dart, test/model/store_test.dart, test/model/user_test.dart, test/widgets/autocomplete_test.dart, test/widgets/message_list_test.dart, test/widgets/recent_dm_conversations_test.dart
I've been saying for a while that I plan to make a UserStore type akin to ChannelStore and MessageStore. Today merging #1148 and in particular 76425ed6a1d0426b97421dc0b703ad83199199ea gave me a fresh reminder that such a thing would be useful. And I decided some nice refactoring would be a relaxing task, so I sat down and did it. :slightly_smiling_face: 
The immediate motivating improvement is the new `userDisplayName` method, which simplifies a lot of spots that were otherwise falling back explicitly to the "(unknown user)" translation.
There's also a bunch of new dartdoc, particularly on the subject of unknown users (cf #716), which there effectively wasn't room for when it would have had to live in the middle of the PerAccountStore definition. And at the end of the branch, the actual …
=> Add UserStore; pull out getUser, userDisplayName, others

lib/model/content.dart, lib/widgets/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
Fixes: #1016
<details>
<summary> Screenshots </summary>
| Web | Flutter |
| - | - |
| <img width="577" alt="Screenshot 2025-02-24 at 12 27 55" src="https://github.com/user-attachments/assets/c214d2ee-f26e-43b6-8680-8939609d51ff" /> | <img width="577" alt="Screenshot 2025-02-24 at 12 26 56" src="https://github.com/user-attachments/assets/fd2a472e-c5d3-491c-b2e1-0c61c495eab5" /> |
| <img width="577" alt="Screenshot 2025-02-24 at 12 28 55" src="https://github.com/user-attachments/assets/3313cefe-4234-4414-8af7-b585bf5e99f8" /> | <img width="577" alt="Screenshot 2025-02-24 at 12 28 33" src="https://github.com/user-attachments/assets/91bbf789-3092-4fe3-8c39-6de90265b6a1" /> |
| Web (Small) | Flutter (Small) |
| - | - |
| <img width="427" alt="Screenshot 2025-02-24 at 12 37 54" …
=> content: Handle link previews

tools/check
Without this, there are failures when running `./tools/check` script with `--verbose` flag:
Test command: ./tools/check pigeon --all-files --fix --verbose
date: illegal option -- -
usage: date [-jnRu] [-I[date|hours|minutes|seconds]] [-f input_fmt]
[-r filename|seconds] [-v[+|-]val[y|m|w|d|H|M|S]]
[[[[mm]dd]HH]MM[[cc]yy][.SS] | new_date] [+output_fmt]
Time now:
zulip-flutter e0df0ed10 • 2025-02-26 05:01:14 +0000
=> check: Ensure GNU coreutils are used on macOS

.github/workflows/update-translations.yml
This replaces #1192, with the branch pushed to `zulip/zulip-flutter` so that it can possibly be tested before merging.
=> github: Fix weblate action's rights, and update generated code.

lib/model/content.dart, lib/widgets/content.dart, test/flutter_checks.dart, test/model/content_test.dart, test/widgets/content_test.dart
Fixes: #59
Fixes: #1356
| Before                                    | After                                     |
|-------------------------------------------|-------------------------------------------|
| ![WhatsApp Image 2025-02-05 at 8 46 10 PM](https://github.com/user-attachments/assets/798d23f8-9ead-4a65-ba2a-04f49b4f7e41) | ![WhatsApp Image 2025-02-14 at 11 32 54 PM](https://github.com/user-attachments/assets/be797e77-a8ff-48ff-9df3-77b1539e5742) |
=> content: Add start attribute support for ordered list

lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/theme.dart, test/widgets/message_list_test.dart
This PR updates the color variables in `DesignVariables` and `MessageListTheme` for a slightly higher contrast in dark theme according to the values in the figma file.
| -------------- | ----------------|
| <img src="https://github.com/user-attachments/assets/a538aa01-6791-404a-99d1-91f53700486f">  |  <img src = "https://github.com/user-attachments/assets/a15801b2-90f5-4df6-aa15-309b9b18eecf"> |
| <img src="https://github.com/user-attachments/assets/8ceb2faf-8832-4ae8-b05c-155fa1065884">  |  <img src = "https://github.com/user-attachments/assets/a7912379-93b1-44aa-8087-e054d63e4a81"> |
| <img src="https://github.com/user-attachments/assets/3d169e9c-fd8f-4a83-9c9d-cc98f11653dd">  |  <img src = "https://github.com/user-attachments/assets/a31be1a6-499d-4896-9801-7f3c3239db6 …
=> Tweak dark theme

lib/widgets/emoji_reaction.dart, test/flutter_checks.dart, test/widgets/emoji_reaction_test.dart
Previously, the body of the bottom sheet was wrapped in `SafeArea`. This pads the bottom unconditionally, shifting the bottom of the list view above the device bottom inset.
This is undesirable, because the area beneath the bottom inset is still visible, and the list view should extend to the bottom regardless of the bottom inset.
By just removing the `SafeArea`, the list view extends to the bottom. However, if the bottom inset is more than 8px, we can't scroll past the last item in the list view.  Essentially, we want the behavior of `SafeArea.minimum` with a `ListView` — the bottom of the list should always be padded by at least 8px, so that we can scroll past the shadow; and if the bottom inset is more than 8px, use that as the padding instead — which is achieved through the use …
=> emoji: Fix bottom padding of emoji picker

lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/model/autocomplete.dart, lib/model/store.dart, lib/widgets/autocomplete.dart, lib/widgets/compose_box.dart, lib/widgets/inbox.dart, lib/widgets/message_list.dart, test/example_data.dart, test/model/autocomplete_test.dart, test/widgets/autocomplete_test.dart, test/widgets/inbox_test.dart, test/widgets/message_list_test.dart
~~Stacked on top of #1342.~~
This addresses part of #1250.
This is the bare minimum needed for making `TopicName.displayName` nullable before we can work on the more intricate details on how parts like sending from compose box or live hint text updates work.
The last three commits enable support for empty topics for testing. When merging, we leave those three commits out because we haven't yet finished working other other parts mentioned above. This allows us to review and merge related changes without interrupting beta releases with user-visible changes.
See the [screenshots](https://github.com/zulip/zulip-flutter/pull/1297#issuecomment-2644408826) for what changes are included here.
=> general chat #1: add support at most places

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/inbox.dart, lib/widgets/message_list.dart, lib/widgets/subscription_list.dart, test/widgets/action_sheet_test.dart
Adds a channel action sheet with a "Mark channel as read" option, accessible via long-press from both the inbox and subscription list pages. The action sheet is triggered by long-pressing on a channel header.
- Closes #1226 
Currently the action sheet only appears in subscription list when the channel has unread messages, since the sheet doesn't have any default buttons.
=> action_sheet: Offer "Mark channel as read" in channel action sheet

.mailmap
This pr adds my (`tomlin7`) entry to the `.mailmap` file because my name appears as `billy` in the git log. This wasn't intended, and it is my bad that I didn't keep my local git config up-to-date.
=> mailmap: Add Tomlin7's mailmap entry

test/example_data.dart, test/model/store_test.dart, test/model/test_store.dart
This has a natural default, at least in tests, because most tests don't care about the specific value of the global settings.
(By contrast most tests that interact with the store at all will care what set of accounts exist, so there isn't as natural a default for `accounts`.)
Originally noticed this here:
https://github.com/zulip/zulip-flutter/pull/1386#discussion_r1990358363
=> test [nfc]: Make globalSettings optional on TestGlobalStore

lib/model/store.dart, test/api/fake_api.dart, test/example_data.dart, test/model/store_test.dart, test/model/test_store.dart
=> store: Have UpdateMachine.load check account still exists after async gaps

test/widgets/content_test.dart
Thanks Zixuan for noticing we haven't been covering this:
https://github.com/zulip/zulip-flutter/pull/1410#discussion_r1999450438
-----
Skipping maintainer review just because this is a tiny change; please let me know if this is wrong.
=> content test: Test tap-link behavior when invalid URL

test/widgets/emoji_reaction_test.dart
Flutter PR https://github.com/flutter/flutter/pull/159999 (fixes a bug where `MediaQuery` provides an incorrect `TextScaler`) breaks a test in `emoji_reaction_test.dart`.
Currently the `isSystemTextScaler` matcher from the `flutter_test` package can be used to match the system text scaler and is intended to be used for migration. Unfortunately it does not have a `checks` equivalent since flutter / flutter_tests is still using matchers and not importing `checks`.
=> [Flutter Migration] migrate emoji_reaction_test.dart

ios/Flutter/Zulip.xcconfig
This reverts commit a9b20167ccf13ebaf6bcd6a28060ca4438f8c8a8.
=> Revert ios build workaround for Firebase packages

lib/widgets/action_sheet.dart, lib/widgets/compose_box.dart, test/widgets/action_sheet_test.dart, test/widgets/compose_box_test.dart
Similar to #1297, this PR focuses on part of the general chat feature, with some final "do not merge" commits to make it testable.
This includes the following commits:
* 5ad98d9bb compose: Support sending to empty topic
* 1e31660a3 compose: Change content input hint text if topic is empty and mandatory
* 073042a69 compose [nfc]: Make isTopicVacuous private
* dd47653d3 compose [nfc]: Handle empty topics for fixed destination input hint text
* 73c46b5e3 compose test [nfc]: Extract ChannelNarrow variable
* 0f4e7948d action_sheet [nfc]: Hide resolve/unresolve button for empty topic
The remaining commits should be reviewed in #1297, but neither PR blocks each other, as they each focuses on a specific part of the feature.
<details>
<summary>Screenshots</summary>
| mandatory topics | non-empty …
=> general chat #2: support sending to empty topic from channel narrow, hide resolve/unresolve conditionally

lib/widgets/compose_box.dart
These commits help get the code ready to implement the blue "Edit message" banner, with the "Cancel" and "Save" buttons; see Figma:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=3988-38201&m=dev
The most interesting change is to extract a base class `_Banner` out of `_ErrorBanner`:
We'll make a new subclass with a name like `_EditMessageBanner` for #126; here's a rough sketch of what that'll look like:
```dart
class _EditMessageBanner extends _Banner {
const _EditMessageBanner();
@override
String getLabel(ZulipLocalizations zulipLocalizations) =>
zulipLocalizations.composeBoxBannerLabelEditMessage;
@override
Color getLabelColor(DesignVariables designVariables) =>
designVariables.bannerTextIntInfo;
@override
Color getBackgroundColor(DesignVariables …
```
=> Edit-message (1/n): Refactor compose-box banner logic

lib/widgets/action_sheet.dart, pubspec.lock, pubspec.yaml, test/widgets/theme_test.dart
This is to unblock PR: https://github.com/flutter/flutter/pull/165596 which has test failures in customer testing.
`MenuItemButton` and `SubmenuButton` widgets are wired up with `SemanticsRole.menuItem` and they require their parent to be either `SemanticsRole.menu` or `SemanticsRole.menuBar`.
=> MenuItemButton and SubmenuButton should be used in a menu or menu bar

ios/Podfile.lock, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, macos/Podfile.lock
I think the Podfile.lock changes are needed because #1426 didn't include the `pod` step of `tools/upgrade`.
I suspect the Xcode-file update is due to an Xcode upgrade.
Done by building for iOS, with Xcode 16.2 (16C5032a), then (when I remembered that macOS/Podfile.lock needs updating too) `tools/upgrade pod`.
-----
cc @rajveermalviya as the author of #1426.
=> ios build: Take auto updates to Podfile.lock and an Xcode file

lib/example/sticky_header.dart, lib/widgets/content.dart, lib/widgets/message_list.dart, lib/widgets/scrolling.dart, lib/widgets/sticky_header.dart, test/widgets/message_list_test.dart, test/widgets/scrolling_test.dart, test/widgets/sticky_header_test.dart
This is the next round after #1316, toward #82.
Since that PR, the sticky header has been properly laid out and painted even in cases where it needs to overflow on top of another sliver… so long as the sliver with the header gets painted after the sliver it needs to overflow upon. This PR subclasses CustomScrollView and related classes (most pertinently RenderViewport) so that it's always possible to arrange for that to happen.
One welcome consequence is to clear out all the skipped tests that #1316 left in `sticky_header_test.dart`.
I've also sent a PR upstream to add this same functionality to CustomScrollView (and RenderViewport etc.) itself:
https://github.com/flutter/flutter/pull/164818
Hopefully that will land and let us cut out a lot of this code. In the meantime this lets us move …
=> anchors 4/n: Control which sliver paints over which

lib/widgets/compose_box.dart
The edit-message compose box (#126) shouldn't send [typing notifications](https://zulip.com/help/typing-notifications) like the regular compose box does.
(There's actually [a different kind of typing notification](https://zulip.com/api/set-typing-status-for-message-edit) that we'll want to implement eventually; that's #1350. But that's not for us to do now.)
This PR implements `_ContentInput.noTypingNotifier`, as prep for implementing the edit-message compose box.
Related: #126
=> Edit-message (2/n): Implement variant of content input without a typing notifier

lib/model/message.dart, lib/model/store.dart, test/model/store_test.dart, test/widgets/message_list_test.dart
Related:
- Work toward #1441 
- Prep for #1453
=> local echo (2/n): Rearrange `queueId` and `sendMessage` within store

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/route/messages.dart, test/api/model/events_checks.dart, test/api/route/messages_test.dart, test/example_data.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/model/recent_dm_conversations_test.dart, test/model/test_store.dart, test/model/unreads_test.dart, test/widgets/home_test.dart, test/widgets/inbox_test.dart, test/widgets/message_list_test.dart, test/widgets/poll_test.dart, test/widgets/recent_dm_conversations_test.dart
Related:
- Work toward #1441 
- Prep for #1453
=> local echo (1/n): Add API support for local_id/local_message_id and queue_id

lib/model/message.dart, lib/model/store.dart
And demonstrate its use, with MessageStoreImpl.
This will be a convenient way to provide other common things to substores without needing boilerplate on each substore for each thing.
Co-authored-by: Greg Price <greg@zulip.com>
=> store [nfc]: Add PerAccountStoreBase to provide `connection` to substores

lib/model/emoji.dart, lib/model/recent_dm_conversations.dart, lib/model/store.dart, lib/model/typing_status.dart, lib/model/unreads.dart, lib/model/user.dart, test/model/recent_dm_conversations_test.dart, test/model/typing_status_test.dart, test/model/unreads_test.dart
This follows up on #1464 by moving several more members to PerAccountStoreBase so as to share them across our substores: the global store, account ID, self-user ID, getters for the realm URL and account, and the method for resolving a URL reference based on the realm URL.
@PIG208 it seems we were thinking on similar lines today :slightly_smiling_face: — I saw #1466 when this was partly written, and incorporated the parts of it for migrating the tests in the commit that starts using PerAccountStoreBase for selfUserId. (Some substore tests had been constructing the substores directly, and need to start getting them from a PerAccountStore.)
After this, there are a few small items that I think we'll also want to move: `queueId` (as in #1466), `zulipFeatureLevel`, `zulipVersion`, and that …
=> Move more data to PerAccountStoreBase

lib/model/store.dart
MessageStore will need to access `queueId` and `selfUserId` later for outbox message support.
=> local echo (4/n): Migrate more fields to PerAccountStoreBase

lib/model/actions.dart, lib/notifications/display.dart, test/model/actions_test.dart, test/notifications/display_test.dart
Fixes: #1264
- Ignores notifications received for accounts that were logged out while the app was offline
- Removes notifications (if there exist) of the user when the user logs out
=> notif: Ignore notifications for logged out accounts

lib/api/model/events.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/api/route/messages.dart, lib/api/route/messages.g.dart, lib/model/message.dart, lib/model/message_list.dart, lib/model/narrow.dart, lib/widgets/message_list.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/model/narrow_test.dart, test/model/unreads_test.dart, test/widgets/message_list_test.dart
Related:
- Work toward #1441 
- Prep for #1453
=> local echo (3/n): Pull out MessageBase

lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/model/message.dart, lib/model/store.dart, lib/widgets/app.dart, lib/widgets/compose_box.dart, lib/widgets/dialog.dart, lib/widgets/lightbox.dart, test/example_data.dart, test/widgets/dialog_test.dart
Here's a small batch of miscellaneous prep work for the edit-message feature, #126.
=> Edit-message (4/n): Misc. preparation for edit-message feature

test/widgets/scrolling_test.dart
These two tests on CustomPaintOrderScrollView compare its behavior to the default z-order / paint order behavior of CustomScrollView. They'd therefore be broken by my upstream PR that gives CustomScrollView the functionality of CustomPaintOrderScrollView and simplifies its default behavior:
https://github.com/flutter/flutter/pull/164818
So skip the tests.  Once that PR lands, we can update past it and then remove CustomPaintOrderScrollView and its tests entirely.
(The customer_tests failures currently seen on the upstream PR are different, because the Zulip pin in flutter/tests is currently at d302584e5.  The failures there are in the sticky_header tests, which want to exercise a variety of sliver configurations and need to control the z-order when they do so.  As of d302584e5, they did …
=> scrolling test: Skip tests against old default z-order of slivers

lib/widgets/message_list.dart, lib/widgets/scrolling.dart, test/widgets/scrolling_test.dart
This is the next round after #1435 ~~(and is stacked atop it)~~, toward #82.
In this PR, we take more control of how the scroll position works in the presence of back-to-back slivers. In particular the [ScrollView.anchor](https://main-api.flutter.dev/flutter/widgets/ScrollView/anchor.html) property doesn't really have enough flexibility to express the behavior we need, so we replace the logic that consumes it.
Once that's done, we're very close to being able to start splitting the real message list into back-to-back slivers. That will come in the next PR, #1468.
Some of the behavior we'd like to customize isn't currently cleanly
exposed to subclasses any more than it is to parent widgets passing
constructor arguments.  In particular, we'll want to change a few
bits of logic in …
=> anchors 5/n: Control scroll position

lib/model/content.dart, lib/model/katex.dart, lib/widgets/content.dart
This follows up on #1408 (KaTeX part 1) with some refactors that I felt were easiest to express by demonstration. I think it'd be good for the next PR in the series, #1452, to be rebased atop these.
This doesn't include the changes I've sketched for passing the font size down directly through the recursion in the parser and widgets. I'll want to look a bit more at how those would interact with the changes in #1452 (which introduce a number of additional length-valued properties) before I'm confident just what shape that part of the API should take.
This way there's nothing that needs to happen at the bottom of the
loop, if any of the cases matched.
Conveniently, the two redundant rules say the exact same thing
when they apply.  So the first one has no effect, and we can
ignore it.
Before …
=> Refactor parts of initial KaTeX handling

lib/widgets/compose_box.dart, test/widgets/compose_box_test.dart
And factor out a helper for the part that reads `widget.narrow` and sets a new controller accordingly; we'll use this helper for the edit-message UI, to reset the compose box at the end of an edit-message session.
Fixes: #1470
=> Edit-message (5/n): Fix bug where compose progress can be lost on new event queue

lib/api/model/model.dart, lib/model/channel.dart, test/model/channel_test.dart
When a subscription is removed, the data in streams and streamsByName are left as instances of `Subscription`.  This is inconsistent with the data store's assumption that unsubscribed channels should have plain `ZulipStream` instances.
This doesn't seem to have user-facing effects, though.  The assertion errors only affect debug builds.
CZO discussion:
https://chat.zulip.org/#narrow/channel/48-mobile/topic/Unsubscribe.20then.20resubscribe.20to.20channel/with/2160241
=> channel: Maintain maps consistently when removing subscriptions

lib/model/binding.dart, lib/notifications/receive.dart, test/api/core_test.dart, test/example_data.dart, test/model/binding.dart, test/model/store_test.dart
Fixes #407 
Changes made:
- Replaced the hardcoded app bundle ID with `packageInfo.packageName`.
- Added a new test that sets a specific appId via packageInfo and confirms it’s used in a notification request.
The first change caused the "token initially unknown" test in `store_test.dart` to fail due to the added asynchronous call to `ZulipBinding.instance.packageInfo`, which delayed the completion of `registerToken`.
To resolve this, a `flushMicrotasks` was added after `await startFuture` in the test to ensure `_registerNotificationToken` completes before the test checks for the request.
=> notif: Use live value for app ID on registering APNs token

ios/Flutter/AppFrameworkInfo.plist, ios/Podfile
The Flutter doc on deploying an iOS app says this number should match the deployment target we set in Xcode (which we also specify in ios/Podfile):
https://docs.flutter.dev/deployment/ios#updating-the-apps-deployment-version
; sure, go ahead and update it.
Prompted by noticing that `flutter run` started bumping it to 13.0 (in flutter/flutter@09d4dabd6; see discussion:
https://github.com/zulip/zulip-flutter/pull/1489#issuecomment-2843657156
) and realizing that 14.0 is actually what it should be for us.
=> ios: MinimumOSVersion 12.0 to 14.0 in ios/Flutter/AppFrameworkInfo.plist

lib/widgets/message_list.dart, lib/widgets/scrolling.dart, test/flutter_checks.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/widgets/message_list_test.dart, test/widgets/scrolling_test.dart
This is the next round after (and is stacked atop) #1486, toward #82.
(The initial draft of this PR said this PR would include the needed changes to the scroll-to-end button. Those ended up being a bigger job than I initially thought, so I've split them into their own PR as #1486.)
On my own device I've been running drafts of this PR merged with drafts of #1486 for a couple of weeks, off and on. Everything seems to behave smoothly from a user perspective.
In this PR:
* We start actually splitting the message list into back-to-back slivers, with the latest message in the bottom message list. Thanks to all the prep work up to this point, this change has only subtle effects in the UX.
* The last commit takes advantage of the back-to-back slivers to make one nice, though small, UX …
=> anchors 7/n: Start splitting slivers!

lib/widgets/content.dart, lib/widgets/lightbox.dart, test/widgets/lightbox_test.dart
Fixes #930.
Fixes #44.
https://github.com/user-attachments/assets/37a832c2-87d6-4223-a47e-f5549fccfead
https://github.com/user-attachments/assets/206af9a4-f487-49ad-adca-54faa70d5783
=> lightbox: Prevent hero animation between message lists

lib/model/message.dart, lib/model/store.dart, test/model/message_test.dart
This PR, toward the edit-message feature #126, implements three new methods on `MessageStore`:
`editMessage`, to be called when the user taps the "Edit message" button in the message action sheet:
`getEditMessageErrorStatus`, to be called when rendering the message list; showing a loading state when we haven't gotten the update-message event yet, and an error state for a failed edit request:
(The UI text isn't final; see updates on CZO: [#mobile-design > edit message @ 💬](https://chat.zulip.org/#narrow/channel/530-mobile-design/topic/edit.20message/near/1930073))
`takeFailedMessageEdit`, to be called when you tap the error message pictured above, so we can put you back in the edit box, starting with the text you'd tried to edit to. This part is from CZO discussion: [#mobile-design > edit …
=> Edit-message (7/n): Implement edit-message methods on MessageStore

lib/widgets/message_list.dart, lib/widgets/theme.dart, test/widgets/theme_test.dart
Looking into the design requirement a bit more, we initially fall back to this color because we didn't have the logic to generate channel colors:
https://chat.zulip.org/#narrow/channel/48-mobile/topic/All.20channels.20screen.20-.20.23F832/near/1904009
This replaces the ad-hoc colors with generated colors based on a fallback base color.
The base color we fall back to is still a placeholder.  Ideally, we should pick a color even for unsubscribed streams, as shown in the Figma design linked in #188.  That issue is out-of-scope for this, though.
For now, it's sufficient to just remove the ad-hoc color on MessageListTheme.  This way we don't have to reuse it in places where colors for unsubscribed streams are needed, namely the topic list (#1158).
| | before | after |
| - | - | - |
| light | …
=> Compute colorSwatchFor when subscription is null

lib/api/model/model.dart, lib/model/message_list.dart, lib/widgets/message_list.dart, test/model/message_list_test.dart
This is a prep PR for #1453, toward #1441.
=> local echo (6/n): Prepare message list for outbox message support

lib/api/model/model.dart, lib/api/route/messages.dart, lib/model/binding.dart, lib/model/store.dart, test/api/model/model_test.dart, test/example_data.dart, test/model/binding.dart
This prepares for #1472, toward #1441.
Requested by @chrisbobbe [here](https://github.com/zulip/zulip-flutter/pull/1472#pullrequestreview-2830021645).
=>  local echo (4.5/n): Prep for creating outbox messages on send

shell.nix
This PR updates the dependencies in the Nix environment file to fix build issues.
- Updated `epoxy` package name to `libepoxy`
- Upgraded `jdk11` to `jdk17` as required by Android Gradle
- Added `nodejs` dependency (required for the icon font generation script)
Tested and working on NixOS 24.11
=> Update shell.nix dependencies

android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties, ios/Podfile.lock, lib/widgets/action_sheet.dart, macos/Podfile.lock, pubspec.lock, pubspec.yaml
Most notable commits in Flutter:
- https://github.com/flutter/flutter/issues/161460#issuecomment-2831410786
- https://github.com/flutter/flutter/issues/161460#issuecomment-2848102198
- https://github.com/flutter/flutter/issues/161460#issuecomment-2867929747
=> Upgrade Flutter, packages and Android build dependencies

assets/l10n/app_en.arb, lib/api/model/submessage.dart, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/log.dart, lib/model/message.dart, lib/model/store.dart, lib/widgets/action_sheet.dart, lib/widgets/compose_box.dart, lib/widgets/dialog.dart, lib/widgets/message_list.dart, lib/widgets/theme.dart, test/api/fake_api.dart, test/example_data.dart, test/flutter_checks.dart, test/model/message_test.dart, test/widgets/action_sheet_test.dart, test/widgets/compose_box_checks.dart, test/widgets/compose_box_test.dart, test/widgets/message_list_test.dart
Edit-message! 🎉
Fixes: #126
| Light | Dark |
| --- | --- |
| <img width="559" alt="image" src="https://github.com/user-attachments/assets/9499b836-2ca2-4650-9c61-e280ee29ba50" /> | <img width="559" alt="image" src="https://github.com/user-attachments/assets/1ed17f4e-e7b1-4a01-936a-6694b5780a77" /> |
| <img width="559" alt="image" src="https://github.com/user-attachments/assets/6a620b78-efdc-4ea1-b9b3-be088e9f3b9a" /> | <img width="559" alt="image" src="https://github.com/user-attachments/assets/a9ee69dc-cebf-4bc7-bc13-4a2774f39615" /> |
| <img width="559" alt="image" src="https://github.com/user-attachments/assets/24a666ef-5325-4dab-8db5-b3c5a5d74a99" /> | <img width="559" alt="image" src="https://github.com/user-attachments/assets/bc30d842-22de-4f97-8246-8cd5e7eeb375" /> |
| <img …
=> Edit-message (8/n): Implement edit-message!

lib/model/message_list.dart, lib/widgets/message_list.dart, test/model/message_list_test.dart, test/widgets/message_list_test.dart
This is the next round after #1468.
After this PR, not only does the last message from the initial fetch go into the bottom sliver, but it remains there even while new messages arrive as events, and those new messages go into the bottom sliver below it.
The main motivation for this change is that it brings us closer to having a `fetchNewer` method, and therefore to being able to have the message list start out in the middle of history, #82. Along the way it also gives us the "90% solution" described in #83, so that new messages don't cause everything on the screen to jump up when you're already scrolled up in history.
Otherwise, if several different test cases in this file fail due to
checks failing inside checkInvariants, then only the first one gets
reported in detail with the …
=> anchors 8/n: Let new messages accumulate in bottom sliver

README.md, lib/api/core.dart
This goes rather farther than #1456, which is for bumping this number just to 5.0. This is OK; we recently bumped zulip-mobile to use 7.0, in the v27.235 release.
zulip-mobile shows a "nag banner" to nudge server admins to upgrade. As of v27.235 (PR zulip/zulip-mobile#5922), that banner appears on 7.x servers, the latest 7.x having recently aged out of our 18-month support window. So we should feel comfortable nudging this number in zulip-flutter to 8.0 once v27.235 has been out for a little while.
Fixes: #1456
=> api: Like zulip-mobile, don't allow connecting to Zulip Server <7.0

lib/model/emoji.dart, lib/model/store.dart, lib/widgets/action_sheet.dart, test/api/route/realm_test.dart, test/example_data.dart, test/model/emoji_test.dart, test/model/store_test.dart, test/widgets/action_sheet_test.dart, test/widgets/emoji_reaction_test.dart
The server change in zulip/zulip#34177, renaming `:smile:` to
`:slight_smile:`, broke the corresponding reaction button in the
message action sheet. We've been sending the add/remove-reaction
request with the old name 'smile', which modern servers reject.
To fix, take the popular emoji names from ServerEmojiData, so that
we'll use the correct name on servers before and after the change.
API-design discussion:
https://chat.zulip.org/#narrow/channel/378-api-design/topic/.23F1495.20smile.2Fslight_smile.20change.20broke.20reaction.20button/near/2170354
Fixes: #1495
=> emoji: Generate popular candidates using names from server data

android/app/build.gradle, android/app/lint-baseline.xml
android build: Disable lint AndroidGradlePluginVersion
We're successfully managing our Gradle and AGP upgrades without this
lint rule, and it's annoying that it fails our CI builds.
Discussion:
https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/CI.20fail.3A.20lint.20on.20Gradle.20version.3F/near/2179323
=> android build: Disable lint AndroidGradlePluginVersion

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/api/route/saved_snippets.dart, lib/api/route/saved_snippets.g.dart, lib/model/saved_snippet.dart, lib/model/store.dart, test/api/model/model_checks.dart, test/api/route/route_checks.dart, test/api/route/saved_snippets_test.dart, test/example_data.dart, test/model/saved_snippet_test.dart, test/model/store_checks.dart
This prepares the data model and API bindings for #1391 towards #863.
=> Add and handle live-updates to saved snippets data

assets/l10n/app_en.arb, assets/l10n/app_pl.arb, assets/l10n/app_ru.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_de.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/generated/l10n/zulip_localizations_zh.dart, lib/notifications/display.dart, test/notifications/display_test.dart
This will enable our translation contributors to start translating these ahead of the upcoming launch, even though the features that use them aren't yet merged to main.
Related issue: #276
=> Sync translatable strings from v0.0.30 release

lib/widgets/settings.dart, test/flutter_checks.dart
See #1546 for a PR that would resolve them, and why we're not doing that just now (it would require upgrading Flutter past a breaking change).
=> settings [nfc]: Suppress some new deprecation warnings

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_de.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/generated/l10n/zulip_localizations_zh.dart, lib/widgets/home.dart, lib/widgets/inbox.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, lib/widgets/theme.dart, test/widgets/inbox_test.dart, test/widgets/recent_dm_conversations_test.dart, test/widgets/subscription_list_test.dart
The "Direct messages" part of this was requested as part of #127 new-DM: it's item 0 in https://github.com/zulip/zulip-flutter/pull/1322#issuecomment-2917492437 . This should block on the rest of #127, because the empty "Direct messages" placeholder says "Why not start the conversation?", and there's no way to do that pre-#127.
cc @alya
-----
The Figma has some graphics on all of these, but we'll leave that for later: see issue #1551.
Fixes: #385
Fixes: #386
=> home: Add placeholder text for empty Inbox, Channels, and Direct messages

lib/model/message_list.dart, lib/widgets/message_list.dart, test/example_data.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/widgets/message_list_test.dart
This is the next round after #1507 (plus #1512), toward #82 and #80.
At the end of this branch, the view-model MessageListView has everything it needs for #82 and #80: the message list can start at an arbitrary anchor, including a numeric message-ID anchor or AnchorCode.firstUnread, and can fetch more history from there in both directions.
This doesn't yet actually use the new functionality outside of tests. As a result this branch is NFC as to the live app, given a well-behaved server (there are a couple of commits that are not NFC in how they act with a server that gives incoherent responses). I have a draft branch (as I mentioned at [#mobile-team > beta release management @ 💬](https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/beta.20release.20management/near/2174229)) that …
=> anchors 9/n: Add anchor, fetchNewer, haveNewest to msglist view-model

lib/model/internal_link.dart, lib/model/message_list.dart, lib/notifications/display.dart, lib/widgets/content.dart, lib/widgets/message_list.dart, test/model/internal_link_test.dart, test/model/message_list_test.dart, test/widgets/content_test.dart, test/widgets/message_list_test.dart
Fixes #82.
This is the next round after #1515 — and completes #82, as well as bringing us close to #80. (These changes were previously sent as part of #1517.)
This branch is a draft only because of a lack of tests. The changes it does have are ready for review.
This doesn't implement the other aspect of the behavior of /near/ links, i.e. to follow the message if it's been moved to another conversation. That's tracked as #683.
=> anchors 10/n: Open /near/ links at message

lib/model/message.dart, lib/model/message_list.dart, lib/widgets/message_list.dart, test/api/model/model_checks.dart, test/model/message_list_test.dart, test/model/message_test.dart, test/widgets/message_list_test.dart
Here's a revised version of a substantive commit from #1453:
9c0b95568 msglist: Add and manage outbox message objects in message list view
That just leaves one more substantive commit from that PR:
1fa9f24c8 msglist: Support retrieving failed outbox message content
=> local echo (6.75/7): Revised commit for local echo (sans retrieving failed outbox content)

assets/l10n/app_en.arb, assets/l10n/app_pl.arb, assets/l10n/app_ru.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_de.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/generated/l10n/zulip_localizations_zh.dart, lib/model/message.dart, lib/widgets/compose_box.dart, lib/widgets/message_list.dart, test/widgets/compose_box_test.dart, test/widgets/message_list_test.dart
Fixes #1441.
Stacked atop #1472.
(This branch can be used to preview the full implementation)
<details>
<summary> screenshots </summary>
| message sent | got message event |
| - | - |
| ![sending-success-before](https://github.com/user-attachments/assets/9682f14c-152c-44da-b571-cfa01e9a9849) | ![sending-success-after](https://github.com/user-attachments/assets/069cb811-d7aa-405a-97fb-9c0b173d0950) |
| message failed to send | message content tapped | recipient headers |
| - | - | - |
| ![send-failed](https://github.com/user-attachments/assets/cda06163-7ae5-42b6-b6ec-b7ef67a7b5a2) | ![sent-failed-interacted](https://github.com/user-attachments/assets/51840a33-57da-4322-8761-6ec785120eee) | ![recipient-headers](https://github.com/user-attachments/assets/987dc35a-4278-4ce6-9d34-d10510d1aacc) …
=> local echo (7/7): Support simplified version of local echo

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_de.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_it.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_sl.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/generated/l10n/zulip_localizations_zh.dart, lib/widgets/action_sheet.dart
Thanks Alya for pointing this out:
https://chat.zulip.org/#narrow/channel/48-mobile/topic/quote.20and.20reply.20-.3E.20quote.20message/near/2193484
=> msglist: Say "Quote message" for the quote-and-reply button, following web

android/app/build.gradle, docs/howto/push-notifications-ios-simulator.md, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/Info.plist, lib/model/store.dart, lib/notifications/display.dart, test/notifications/display_test.dart
=> Switch app ID to those of the main app

lib/model/legacy_app_data.dart
In particular, if the legacy app's account list contains multiple entries with the same realm and user ID (though different emails), we'll drop all but the most-recently-used one because this app's accounts table keeps (realmUrl, userId) unique. With this change, we still drop the duplicates, but we catch the exception and proceed smoothly to the next account in the list.
Ideally these changes would be tested. We'll leave that as part of the followup issue #1593, which covers this whole file.
=> More error tolerance in migrating legacy data

lib/model/presence.dart, lib/model/store.dart, lib/widgets/content.dart, lib/widgets/home.dart, lib/widgets/message_list.dart, lib/widgets/profile.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/theme.dart, test/model/store_test.dart
TODO tests, but here's a draft for presence!
Fixes: #196
Fixes: #1607
=> Store, report, and display presence!

lib/model/message_list.dart, test/model/message_list_test.dart
Fixes: #1637
| --- | --- |
| <img width="490" alt="image" src="https://github.com/user-attachments/assets/bb3f4dc8-af93-4bff-bf04-46d851bd6f64" /> | <img width="490" alt="image" src="https://github.com/user-attachments/assets/453246ec-8a4c-4fdc-94b8-dd4cfe0a33ef" /> |
| <img width="490" alt="image" src="https://github.com/user-attachments/assets/eb56b2f9-1704-44b3-93bf-950a3529f177" /> | <img width="490" alt="image" src="https://github.com/user-attachments/assets/ec69db19-d6de-47b3-82e2-105f5f410f53" /> |
cc @alya
=> msglist: Show recipient headers on all messages, in Mentions / Starred

lib/widgets/message_list.dart, test/widgets/message_list_checks.dart, test/widgets/message_list_test.dart
=> msglist: Tapping a message in Starred or Mentions opens anchored msglist

lib/model/katex.dart
=> KaTeX (4/n): Ignore classes that don't have CSS definition

lib/widgets/message_list.dart
This condition is a bit complex already, and will become more so soon (https://github.com/zulip/zulip-flutter/pull/1624#discussion_r2183802267).  So making it a method instead of an expression gives its logic a bit more room to breathe and spread out.
=> msglist [nfc]: Pull out a _showAsMuted method

lib/widgets/message_list.dart
This does two things:
- Shrinks a 36px gap to 12px (the gap below the mark-as-read button)
- Removes 11px bottom padding on the last message in the feed (but keeps it when followed by a recipient header; see https://github.com/zulip/zulip-flutter/pull/1453#discussion_r2106526985)
Proposed by Tim in chat:
[#mobile > space at end of thread @ 💬](https://chat.zulip.org/#narrow/channel/48-mobile/topic/space.20at.20end.20of.20thread/near/2203404)
> I bet those two tweaks might fully address this issue.
=> Decrease whitespace at end of message feed

lib/model/channel.dart, lib/model/recent_senders.dart, lib/model/unreads.dart, test/model/channel_test.dart, test/model/message_list_test.dart, test/model/recent_senders_test.dart, test/model/test_store.dart, test/model/unreads_test.dart, test/stdlib_checks.dart, test/widgets/inbox_test.dart, test/widgets/topic_list_test.dart
=> model: Treat topics case-insensitively in Unreads, topic-visibility, and recent-senders

assets/l10n/app_de.arb, assets/l10n/app_en.arb, assets/l10n/app_it.arb, assets/l10n/app_pl.arb, assets/l10n/app_ru.arb, assets/l10n/app_sl.arb, assets/l10n/app_uk.arb, assets/l10n/app_zh_Hans_CN.arb, assets/l10n/app_zh_Hant_TW.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_de.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_it.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_sl.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/generated/l10n/zulip_localizations_zh.dart, lib/widgets/message_list.dart, test/widgets/message_list_test.dart, test/widgets/topic_list_test.dart
Our initial implementation of https://github.com/zulip/zulip-flutter/issues/1158, in https://github.com/zulip/zulip-flutter/pull/1500, uses the word "TOPICS" for the app-bar action/button leading to the topic-list page, following the design in Figma.
We want to change it to use a "list" icon instead. This is in order to let it occupy less space, especially in languages where the translation of "TOPICS" might be long.
| light | dark |
|----|----|
| ![Simulator Screenshot - iPhone 16 Pro - 2025-06-25 at 17 01 07](https://github.com/user-attachments/assets/a275f2b1-dadd-4175-94b1-f28b02fb0ca8) | ![Simulator Screenshot - iPhone 16 Pro - 2025-06-25 at 17 01 53](https://github.com/user-attachments/assets/8d9b7df9-b96b-4938-9403-a2f9ec019703) |
| ![Simulator Screenshot - iPhone 16 Pro - …
=> msglist: Use icon for topic-list button in app bar

lib/widgets/inbox.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart
The responsibility for consuming the bottom inset is now external to all of these *PageBody widgets; it's handled by
Scaffold.bottomNavigationBar. So we don't need to forward a bottom-inset value down to descendants
(via `SafeArea.bottom: false`), and we don't need to add widgets to pad the bottom inset; the bottom-inset height in all these places is zero.
=> home [nfc]: Clean up some dead safe-area code from before bottom-tabs

.github/workflows/ci.yml
This infra issue in Flutter is currently causing our CI to fail:
https://github.com/zulip/zulip-flutter/pull/1688#issuecomment-3050661097
https://discord.com/channels/608014603317936148/608021351567065092/1392301750383415376
=> ci: Work around accidental desync of Flutter main branch

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/api/model/reaction.dart, lib/model/store.dart, lib/model/user.dart, lib/widgets/action_sheet.dart, lib/widgets/autocomplete.dart, lib/widgets/content.dart, lib/widgets/emoji.dart, lib/widgets/emoji_reaction.dart, test/api/model/model_checks.dart, test/api/model/model_test.dart, test/example_data.dart, test/model/test_store.dart, test/model/user_test.dart
Support for tracking the user status.
Message List:
<table>
<tr>
<td><b>Normal display name</b></td>
<td><b>Long display name</b></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/6b785d0a-22e0-4c10-811a-37ac547622a4"/></td>
<td><img src="https://github.com/user-attachments/assets/0b9139ce-19df-439e-8dd1-ef19878edf1a"/></td>
</tr>
</table>
Recent DMs Page:
<table>
<tr>
<td><b>Normal display name</b></td>
<td><b>Long display name</b></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/33bc8e4c-2795-469f-8f07-7c646a1487af"/></td>
<td><img src="https://github.com/user-attachments/assets/d1d94fb7-c7b6-4cb6-ad96-8d71036b44cd"/></td>
</tr>
</table>
New DM Sheet
<table>
<tr>
<td><b>Normal display name</b></td>
<td><b>Long display name</b></td>
</tr> …
=> Track user status

lib/model/store.dart, lib/widgets/app_bar.dart, test/model/store_checks.dart, test/model/store_test.dart, test/widgets/app_bar_test.dart
Fixes #979.
Discussion:
https://github.com/zulip/zulip-flutter/issues/979#issuecomment-2993296322
------
Tested manually, with and without this change:
1. Log out from CZO (too active; events coming in frequently); connect to a not-very-active org
2. Make an artificial network error in the `getEvents` binding:
```diff
diff --git lib/api/route/events.dart lib/api/route/events.dart
index bd14521c7..da7bf4fea 100644
--- lib/api/route/events.dart
+++ lib/api/route/events.dart
@@ -1,6 +1,7 @@
import 'package:json_annotation/json_annotation.dart';
import '../core.dart';
+import '../exception.dart';
import '../model/events.dart';
import '../model/initial_snapshot.dart';
@@ -27,6 +28,7 @@ Future<InitialSnapshot> registerQueue(ApiConnection connection) {
Future<GetEventsResult> …
```
=> store: Pass `dont_block` in first poll attempt after a failure

.github/workflows/ci.yml, .github/workflows/update-translations.yml
Fixes #1710.
This should work around the problem for a few more months.  If it doesn't get fixed upstream by then, we can figure something else out.
While we're here, also revert the temp hack we needed for a previous issue:
This reverts commits 9cc34cd7e and 37af86db6 (#1691, #1690).
The operational issue in the upstream repo which this worked around has been fixed.
=> ci: Fetch 3000 commits from upstream, rather than 1000

lib/model/content.dart, lib/model/katex.dart, lib/widgets/content.dart, test/model/content_test.dart, test/widgets/content_test.dart
Stacked on top of: #1452
| Web | Flutter |
| - | - |
| <img width="719" alt="Screenshot 2025-05-19 at 22 50 20" src="https://github.com/user-attachments/assets/fffa7c49-5b33-4831-8a32-7abe10b9afdd" /> | <img width="759" alt="Screenshot 2025-05-19 at 22 50 43" src="https://github.com/user-attachments/assets/14a308ac-d445-4b35-8d63-8cb1b3382dd1" /> |
Related: #46
=> KaTeX (2/n): Support for vertical offsets in spans

README.md
This adds back the definition for the
project board link that was dropped as
a part of d3d77215508cc0a281de8d2b84292e4bc3394339.
Discussion: https://chat.zulip.org/#narrow/channel/19-documentation/topic/Missing.20project.20board.20link.20in.20flutter.20readme
=> docs: Add missing project board link in README.

lib/model/settings.dart, test/model/content_test.dart, test/widgets/content_test.dart
Here's a version of the commit I've included in each release recently, atop (previous versions of) #1559, to enable our KaTeX support. Now that #1559 and its preceding PRs (#1698, and others before that) are merged to main, this is ready to go to main too.
This was a minimal version for the release, just flipping the flag's default to true. But in general we should remove experimental flags from the codebase as soon as they're no longer relevant, to keep complexity from building up. (See the doc on [GlobalSettingType.experimentalFeatureFlag].) @rajveermalviya would you write a follow-up commit that removes this flag entirely, and cleans up the logic elsewhere which that makes possible to clean up?
This is cherry-picked from commits we included in each of the last
several releases, …
=> Render KaTeX by default

lib/model/binding.dart, lib/model/katex.dart, lib/widgets/content.dart, tools/content/unimplemented_katex_test.dart
Now that the KaTeX support we've had in recent releases is merged into main (with #1559) (*), I've gone and made a number of the refactors that I'd been contemplating for this code but hadn't wanted to do before those were merged. In this branch:
* Parse each element's inline styles in a more direct way, letting the parsing logic for different types of elements apply their respective context of what styles are expected. This also means less building and copying of generic KatexSpanStyles objects.
* Simplify some of the vlist parsing code, notably around margins.
* Split the parsing of struts and vlists into their own respective methods.
* At the start of the branch, a few adjustments to make the output of `tools/content/check-features katex-check` more stable and easier to compare across …
=> Refactor KaTeX parsing of inline styles and vlists; normalize survey output a bit more

lib/model/store.dart
I happened to notice this message getting printed repeatedly in the debug logs (reformatted a bit):
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception:
NetworkException: HTTP request failed. Client is already closed.
(ClientException: HTTP request failed. Client is already closed.,
uri=https://chat.zulip.org/api/v1/users/me/presence)
#0      ApiConnection.send (package:zulip/api/core.dart:175)
<asynchronous suspension>
#1      Presence._maybePingAndRecordResponse (package:zulip/model/presence.dart:93)
<asynchronous suspension>
#2      Presence._poll (package:zulip/model/presence.dart:121)
<asynchronous suspension>
That'd be a symptom of an old Presence continuing to run its polling loop after the ApiConnection has been closed, which happens when the PerAccountStore is …
=> presence: Dispose Presence object when store disposed

lib/widgets/autocomplete.dart, lib/widgets/message_list.dart, lib/widgets/new_dm_sheet.dart, lib/widgets/profile.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/theme.dart, test/model/test_store.dart, test/widgets/autocomplete_test.dart, test/widgets/finders.dart, test/widgets/message_list_test.dart, test/widgets/new_dm_sheet_test.dart, test/widgets/profile_test.dart, test/widgets/recent_dm_conversations_test.dart
The remaining half of #1629. For related images, please see #1629 description.
Fixes: #197
=> Show user status in UI

lib/widgets/settings.dart, test/flutter_checks.dart, test/model/store_checks.dart, test/widgets/settings_test.dart
Fixes #1545.
Fixes part of:
- #1571
- #1583
=> settings: Migrate to new RadioGroup API; write widget tests for two just-added settings

lib/api/model/events.dart, lib/model/channel.dart
`flutter analyze` has started giving the following, which breaks CI:
info • Unnecessary comparison to a boolean literal • lib/api/model/events.dart:1177:10 •
no_literal_bool_comparisons
info • Unnecessary comparison to a boolean literal • lib/model/channel.dart:158:13 •
no_literal_bool_comparisons
Fixed.
=> analyze: Fix new lints on latest Flutter main

pubspec.lock, pubspec.yaml
With this upgrade, we can now use the route transition duration in tests to wait the minimum amount of time needed for the route animation to complete.
Related upstream PR: https://github.com/flutter/flutter/pull/171109
=> deps: Upgrade Flutter to 3.33.0-1.0.pre-1086

lib/api/model/events.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/api/route/settings.dart, lib/model/store.dart, lib/widgets/content.dart, lib/widgets/lightbox.dart, lib/widgets/message_list.dart, test/api/route/settings_test.dart, test/example_data.dart, test/model/store_test.dart, test/widgets/content_test.dart, test/widgets/lightbox_test.dart, test/widgets/message_list_test.dart
Fixes #1015.
cc @alya for screenshots below.
=> Follow user's time format setting (12 or 24 hour)

lib/model/katex.dart, lib/model/settings.dart, test/model/content_test.dart, test/model/katex_test.dart, test/widgets/content_test.dart, test/widgets/katex_test.dart, tools/content/unimplemented_katex_test.dart
This flag has been enabled since v0.0.29 (beta) release, and we don't plan to disable it. So remove the flag completely, simplifying related code.
Fixes: #1728
=> katex: Remove renderKaTex experimental flag

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_de.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_fr.dart, lib/generated/l10n/zulip_localizations_it.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_sl.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/generated/l10n/zulip_localizations_zh.dart, lib/widgets/action_sheet.dart, lib/widgets/message_list.dart, test/widgets/action_sheet_test.dart
| Topic action sheet | Copied link pasted |
| --- | --- |
| <img width="544" height="1036" alt="Copy link to topic" src="https://github.com/user-attachments/assets/04f20778-9c67-42b6-8c67-f9484003621c" /> | <img width="544" height="1036" alt="Topic link pasted" src="https://github.com/user-attachments/assets/48d13f05-6ecb-4d86-ab8c-e34330ec7173" />
https://github.com/user-attachments/assets/59d864bb-169e-497f-9722-46f7d7d52359
Fixes: #792
=> "Copy link to topic" in topic action sheet

lib/api/route/messages.dart, lib/api/route/messages.g.dart, lib/model/compose.dart, lib/widgets/compose_box.dart, test/api/route/messages_test.dart, test/model/compose_test.dart, test/widgets/compose_box_test.dart
Fixes #1709.
Like elsewhere in our codebase, use the standard term "URL":
https://github.com/zulip/zulip-mobile/blob/main/docs/style.md#url-not-uri
This way this function is a more faithful wrapper of constructing
the actual Markdown syntax.  The Markdown will have a URL string,
after all, so it's for the best to put this function's caller in
control of exactly what string that is.
Fixes #1709.
Round-tripping through `Uri.parse` and `.toString()` had the effect
of percent-encoding any non-ASCII characters in the given URL string.
The server expects, reasonably enough, that the client will refer to
the upload using the same URL string the server provided at upload
time; so do that.
Now that the caller is passing a string instead of a Uri object, the
caller that wants an empty string here …
=> For uploads, use verbatim URL string from server

lib/model/autocomplete.dart, lib/model/compose.dart, lib/widgets/autocomplete.dart, test/model/autocomplete_checks.dart, test/model/autocomplete_test.dart, test/model/compose_test.dart, test/model/test_store.dart
=> autocomplete: Support user-group mentions; match users by email; rank results by match quality

lib/widgets/theme.dart
This also fixes an assert in ZulipMenuItemButton when running desktop builds of the app.
In particular that assert prevents the buttons in an action sheet from appearing, so I ran into it while using a desktop build to test https://github.com/zulip/zulip-flutter/pull/1706#discussion_r2252435627 .
=> theme: Set visualDensity to standard, even on desktop

lib/widgets/action_sheet.dart, test/widgets/action_sheet_test.dart
As in the Figma:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=6812-34593&m=dev
-----
cc @alya 
| --- | --- |
| <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/cb824260-778e-414a-b3f9-288c31d36288" /> | <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/ef53221b-b48f-4dc2-9370-0bf6c2843d90" /> |
=> action_sheet: Put mark-channel-as-read button at top of action sheet

lib/model/server_support.dart, lib/model/store.dart, lib/widgets/login.dart, test/api/route/route_checks.dart, test/model/store_checks.dart, test/model/store_test.dart, test/widgets/checks.dart, test/widgets/dialog_test.dart, test/widgets/login_test.dart
Stacked atop #1782, which is an improvement to the tests that I found while working this (actually while pairing with @sm-sayedi 🙂) plus a fix for something we overlooked in #1017.
-----
There's a planned change to make zulipMergeBase required in
GetServerSettingsResult (see #904). When we do that, we'd otherwise
just treat a missing zulipMergeBase on an ancient server the same
way we treat any malformed response. Better to check if the server
is an ancient one we don't support, just like when the /register
response is malformed.
=> login: Reject earlier (at get-server-settings) when server is too old

lib/generated/l10n/zulip_localizations.dart
These were added yesterday in 7f7aa987b (#1790).  The descriptions changed in the last revision before the PR was merged; but the edit apparently didn't make it to the generated file, causing CI to fail.
=> l10n: Fix mismatch in descriptions of new strings

lib/widgets/compose_box.dart
In e4deccbdc ComposeBoxController started exposing uploadFiles method, which is now used by Share-to-Zulip implementation. So use that for _AttachUploadsButton too, using the same implementation between Share-to-Zulip and compose box upload buttons.
=> compose [nfc]: Use ComposeBoxController.uploadFiles in _AttachUploadsButton

lib/model/message.dart, lib/widgets/compose_box.dart, test/model/message_test.dart, test/widgets/action_sheet_test.dart, test/widgets/compose_box_test.dart, test/widgets/message_list_test.dart
With #188, the message-list UI for an unsubscribed channel will become more prominent, which calls for fixing at least the following glitch:
Since we don't get events when the self-user sends or edits a message in an unsubscribed channel, we'd like to refetch messages on success of those actions. Discussion: [#mobile > Message sending in unsubscribed channels @ 💬](https://chat.zulip.org/#narrow/channel/48-mobile/topic/Message.20sending.20in.20unsubscribed.20channels/near/2233492) So, on the path to that, make `store.editMessage` similar to `store.sendMessage` in returning `Future<void>` instead of `void`, where the returned Future resolves or rejects with the API request, irrespective of the event.
While we're at it, show an error dialog when the edit fails, as we've been meaning to do, …
=> edit-message: Show error dialog on edit-message request error

lib/api/model/narrow.dart, lib/model/internal_link.dart, lib/model/narrow.dart, test/api/route/messages_test.dart, test/model/compose_test.dart, test/model/internal_link_test.dart, test/model/message_list_test.dart, test/widgets/action_sheet_test.dart, test/widgets/actions_test.dart, test/widgets/message_list_test.dart
=> internal_link: Generate new narrow links with "channel", not "stream"

lib/widgets/emoji_reaction.dart, lib/widgets/set_status.dart
Fixes: #1769
Fixes: #1770
Fixes: #1771
<details>
<summary>Screenshots</summary>
| --- | --- |
| <img width="974" height="606" alt="Landscape - before" src="https://github.com/user-attachments/assets/811f325f-bf61-40d1-b09f-6cec7d9ad07d" /> | <img width="974" height="606" alt="Landscape - after" src="https://github.com/user-attachments/assets/55947bb7-0332-4f1c-9ebc-5290fab4aafa" /> |
| --- | --- |
| <img width="544" height="1036" alt="Consistent padding - before" src="https://github.com/user-attachments/assets/be67e4bd-1ea4-4e9a-9584-3307ca3489df" /> | <img width="544" height="1036" alt="Consistent padding - after" src="https://github.com/user-attachments/assets/4f4b91c6-9bca-40b3-8032-9d3b0675de98" /> |
| Before | After (no feedback) |
| --- | --- | …
=> Set status page adjustments

lib/model/store.dart, lib/widgets/action_sheet.dart, lib/widgets/app.dart, lib/widgets/autocomplete.dart, lib/widgets/emoji_reaction.dart, lib/widgets/inset_shadow.dart, lib/widgets/profile.dart, lib/widgets/read_receipts.dart, lib/widgets/set_status.dart, test/widgets/profile_test.dart
For manual testing, ideally use a real device, to see the fling and drag responses faithfully to what most users will experience :)
Selected commit messages:
-----
ead_receipts: Improve UX by making the sheet draggable-scrollable
The Figma asks that the sheet be expandable to fill the screen:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=11367-21131&m=dev
and that's implemented here.
Compare f8ddff2f3, where we removed an earlier implementation. I
hadn't tried to bring that back yet because I wanted to support
triggering resize from a drag handle at the top, and I couldn't
figure out how to do that. IIRC I could only get the drag handle to
respond to drag-down gestures (via `enableDrag: true`) by shifting
the sheet's position downward. …
=> Make read-receipts and view-reactions draggable-scrollable

lib/widgets/content.dart, lib/widgets/text.dart, test/model/content_test.dart, test/widgets/content_test.dart
Fixes #806.
Fixes #1812.
Fixes #1817.
Fixes #1818.
There are other issues with inline-span styles:
- #1813
- #1819
- (possibly more)
but I think those all involve `WidgetSpan`s in `InlineContent`'s span tree and can be addressed separately.
| --- | --- |
| <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/9ee6e311-a0d2-4bb2-bda3-c279f30f5c6a" /> | <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/cc57ebba-cf9d-4b20-b4fe-9419d7c731eb" /> |
| <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/ccd69f1e-042f-49b6-a340-02bb9467c71f" /> | <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/850a587e-3671-478a-a82f-78241 …
=> content: Fix bugs where `TextSpan` styles clobber each other with `InlineContent.style` attributes

lib/model/message_list.dart, test/model/message_list_test.dart
| - | - |
| <img width="952" height="2252" alt="image" src="https://github.com/user-attachments/assets/9681df0d-64b9-42fb-9b8a-32692a5845fa" /> | <img width="952" height="2252" alt="image" src="https://github.com/user-attachments/assets/8a720fda-7073-4bc4-a8c0-9596aa18049f" /> |
Fixes: #1773
=> msglist: Separate messages after 10-min gap, with a sender row

lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/api/model/model.g.dart, lib/model/channel.dart, lib/model/realm.dart, lib/model/store.dart, lib/model/user_group.dart, lib/widgets/action_sheet.dart, test/example_data.dart, test/model/realm_test.dart, test/model/user_group_test.dart
Fixes #1687.
Fixes #814.
Stacked atop #1814.
This adds all the generic infrastructure needed for implementing any given group-based permission. The last commit (or pair of commits) then adds the permission "has content access (to a channel)" (which we'll want for #188), to demonstrate end-to-end how to add individual permissions using the new infrastructure.
=> Group-based permissions

test/widgets/emoji_reaction_test.dart
I'm currently working on a PR to port the new Android 12 overscroll effect. During this process, I encountered a test that was failing when it should have passed.
The root cause of the failure is that the test asserts a widget's absolute position immediately after a scroll gesture, without waiting for the overscroll physics animation to complete. A single pump() is insufficient for the animation to settle.
The solution is to replace the `pump()` call with `pumpAndSettle()`. This ensures that all animations are finished before the test makes its assertions, making the test reliable.
For more technical context on this new overscroll animation, please refer to the PR at:
https://github.com/flutter/flutter/pull/173849
=> test: Use pumpAndSettle to await overscroll animation

lib/model/push_device.dart, lib/model/store.dart, lib/notifications/receive.dart, test/model/actions_test.dart, test/model/push_device_test.dart, test/model/store_test.dart, test/notifications/open_test.dart, test/notifications/receive_test.dart
This refactor helps prepare for #1764, the new E2EE notifications.
As a bonus, it also cleans up what had been a messy area of UpdateMachine.
=> push_device: Move registering push token off of UpdateMachine; fix ad-hoc Future used for tests

lib/model/database.dart
In an upcoming Dart SDK change
(https://dart-review.googlesource.com/c/sdk/+/450970), I intend to add logic to the analyzer for generating a warning if an API marked @experimental is used. This will allow experimental analyzer features to be developed without creating a risk of breaking changes downstream.
To avoid this change producing a failure in the customer_testing bot (https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20customer_testing), the `zulip-flutter` customer test needs to first be modified in order to ignore the upcoming warning.
=> Ignore upcoming experimental_member_use warning

assets/l10n/app_en.arb, lib/generated/l10n/zulip_localizations.dart, lib/generated/l10n/zulip_localizations_ar.dart, lib/generated/l10n/zulip_localizations_de.dart, lib/generated/l10n/zulip_localizations_en.dart, lib/generated/l10n/zulip_localizations_fr.dart, lib/generated/l10n/zulip_localizations_it.dart, lib/generated/l10n/zulip_localizations_ja.dart, lib/generated/l10n/zulip_localizations_nb.dart, lib/generated/l10n/zulip_localizations_pl.dart, lib/generated/l10n/zulip_localizations_ru.dart, lib/generated/l10n/zulip_localizations_sk.dart, lib/generated/l10n/zulip_localizations_sl.dart, lib/generated/l10n/zulip_localizations_uk.dart, lib/generated/l10n/zulip_localizations_zh.dart, lib/widgets/action_sheet.dart, test/model/test_store.dart, test/widgets/action_sheet_test.dart
Fixes #1786.
(Also fill in some test coverage for the change in cf83c9ec6 / #1822.)
=> action_sheet: Check can_subscribe_group for "Subscribe" confirmation dialog

lib/widgets/button.dart
The toggle design seems to have changed slightly since we implemented it:
https://www.figma.com/design/1JTNtYo9memgW7vV6d0ygq/Zulip-Mobile?node-id=6070-60763&m=dev
Looks like it was just this one detail.
=> button: Update Toggle thumb color following change in Figma

assets/l10n/app_en.arb, lib/widgets/action_sheet.dart, test/widgets/action_sheet_test.dart
See Alya's feedback on #1890:
https://github.com/zulip/zulip-flutter/pull/1890#issuecomment-3358327567
> In general, our pattern is to always show a privacy marker or (if
> not convenient) a `#` before a channel name. It can be a separate
> PR, but can we add that to these confirmation dialogs?
Doing this in code, rather than in the translators' source string, because we don't want it to vary by language.
=> action_sheet: Prefix channel name with "#" in a confirmation dialog title

assets/l10n/app_en.arb, lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/all_channels.dart, lib/widgets/dialog.dart, test/widgets/action_sheet_test.dart, test/widgets/all_channels_test.dart, test/widgets/dialog_checks.dart
Stacked atop #1887.
-----
Fixes #1827.
Fixes #1878.
=> Confirm before unsubscribing (always, if from action sheet; only sometimes, if from "All channels")

lib/api/core.dart, lib/api/model/events.dart, lib/api/model/events.g.dart, lib/api/model/initial_snapshot.dart, lib/api/model/initial_snapshot.g.dart, lib/api/model/model.dart, lib/model/channel.dart, lib/model/message_list.dart, lib/model/store.dart, lib/model/unreads.dart, lib/widgets/action_sheet.dart, lib/widgets/actions.dart, lib/widgets/emoji_reaction.dart, test/example_data.dart, test/model/channel_test.dart, test/model/message_list_test.dart, test/model/unreads_test.dart, test/widgets/action_sheet_test.dart
Fixes #1837.
This isn't our most urgent issue, but I was looking for some low-hanging fruit I could clear during yesterday's heat wave when it was really hot and uncomfortable at home. :)
=> Rely on Zulip Server 6 APIs

lib/widgets/inbox.dart, lib/widgets/recent_dm_conversations.dart, lib/widgets/subscription_list.dart, lib/widgets/unread_count_badge.dart, test/widgets/checks.dart, test/widgets/inbox_test.dart, test/widgets/subscription_list_test.dart, test/widgets/unread_count_badge_test.dart
| --- | --- |
| <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/f7f35e18-c6b1-4c3f-a802-7e99e7d2fed4" /> | <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/d3f4f0ee-bd15-45ad-a8f6-7e21939b2146" /> |
| <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/6cc39087-6ff3-4a5f-94c8-46b0450f3f4e" /> | <img width="559" height="1062" alt="image" src="https://github.com/user-attachments/assets/c2f33b1a-dc29-4fd9-a240-25efce483959" /> |
cc @alya
=> inbox: Fix bug where channel unread badge text color was slightly wrong
