- lib/widgets/message_list.dart
With several TODOs for follow-up improvements.
> msglist: Ellipsize over-long topic names

- README.md
- android/build.gradle
- pubspec.lock
- pubspec.yaml
This cleans up a couple of things that were either printing a warning or dirtying the tree. Also gets us the latest set of dependencies, for good measure.
> deps: Update Flutter and packages

- lib/widgets/login.dart
As with #87, there's plenty more to do here, but here's a first batch of work. 🙂
Fixes-partly: #35
> login: Be a bit more helpful in username/password UI

- lib/api/model/events.dart
I made these small cleanups en route to a more interesting refactor that I ended up deciding we probably don't want. (Will send that as a separate draft PR.) But these bits are good, so might as well keep them.
> api [nfc]: Small cleanups in event classes

- README.md
I was looking for a quick-start guide when I was setting up this repo, so figured I'd add one myself! 😄
> Update README with quick-start information

- test/widgets/action_sheet_test.dart
Like 38ed6c812, but for some tests that were still in PR-flight at the time and so didn't get that treatment.
> test: Fix new action-sheet tests

- test/example_data.dart
Small followup from here: https://github.com/zulip/zulip-flutter/pull/304#issuecomment-1776055163
> test [nfc]: Reorder example data and group a bit more finely

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
> deps: Upgrade Flutter to latest main, 3.16.0-23.0.pre.38

- pubspec.lock
- pubspec.yaml
> deps: Upgrade Flutter to latest main, 3.17.0-10.0.pre.45

- lib/widgets/app.dart
> ui: Center-align actual text (not just column children) on beta homescreen

- lib/widgets/emoji_reaction.dart
> reactions: For text emoji, remove extra space on the left

- lib/widgets/compose_box.dart
- test/flutter_checks.dart
- test/widgets/compose_box_test.dart
> Message compose box presents a sentence case keyboard

- lib/widgets/login.dart
> login: If web-auth error is PlatformException, show error.message to user

- lib/widgets/login.dart
- test/widgets/login_test.dart
> Fix Email Authentication Issue Caused by Trailing Spaces

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/AppDelegate.swift
- lib/widgets/action_sheet.dart
- macos/Podfile.lock
- macos/Runner.xcodeproj/project.pbxproj
- pubspec.lock
- pubspec.yaml
- test/test_share_plus.dart
I'm actually optimistic that this will deal with
- #612
; for details see this commit:
```
deps: Upgrade packages within constraints (tools/upgrade pub)
```
Fixes: #612
> Upgrade Flutter and all packages to latest

- pubspec.lock
- pubspec.yaml
> deps: Upgrade Flutter to latest main, 3.22.0-28.0.pre.10

- lib/widgets/compose_box.dart
I'm pretty sure this change is right, but I'm sending it as a PR instead of pushing directly, in case there's some subtlety I'm missing.
> compose_box [nfc]: Update some stale issue references

- lib/api/exception.dart
- lib/widgets/action_sheet.dart
- lib/widgets/message_list.dart
- test/api/core_test.dart
- test/api/exception_checks.dart
- test/api/exception_test.dart
- test/api/fake_api.dart
- test/api/fake_api_test.dart
- test/widgets/message_list_test.dart
I developed a draft of these changes some months ago, to help me debug something else I was working on. They were useful, but then I was doing other things and didn't come back to finish these. Here they are now.
> Better dev/test error messages on API errors

- pubspec.lock
- pubspec.yaml
> deps: Upgrade Flutter to 3.23.0-13.0.pre.363

- lib/model/autocomplete.dart
- lib/model/internal_link.dart
- lib/model/message_list.dart
- lib/model/narrow.dart
- lib/model/unreads.dart
- lib/widgets/actions.dart
- lib/widgets/app.dart
- lib/widgets/compose_box.dart
- lib/widgets/inbox.dart
- lib/widgets/message_list.dart
- lib/widgets/subscription_list.dart
- test/api/route/messages_test.dart
- test/model/autocomplete_test.dart
- test/model/compose_test.dart
- test/model/internal_link_test.dart
- test/model/message_list_test.dart
- test/model/unreads_test.dart
- test/widgets/action_sheet_test.dart
- test/widgets/actions_test.dart
- test/widgets/compose_box_test.dart
- test/widgets/content_test.dart
- test/widgets/message_list_test.dart
> narrow: Rename StreamNarrow to ChannelNarrow

- lib/api/model/initial_snapshot.dart
- lib/api/model/initial_snapshot.g.dart
- lib/model/unreads.dart
- test/api/model/initial_snapshot_test.dart
- test/example_data.dart
- test/model/unreads_test.dart
- test/widgets/message_list_test.dart
- test/widgets/subscription_list_test.dart
> api: Rename `UnreadStreamSnapshot` to `UnreadChannelSnapshot`

- lib/widgets/login.dart
- lib/widgets/theme.dart
| --- | --- |
| ![368256B2-7A5E-4627-BE5C-DBFF94637BFD](https://github.com/user-attachments/assets/cb6d7ae3-2989-4196-876c-759d4c393941) | ![9F67AF16-99F6-41E5-B9BE-5FFD04796C80](https://github.com/user-attachments/assets/abe51319-a504-4da4-8597-01143126e759) |
| ![BF273FD3-FBBC-432F-BC07-73A1FC19C8F4](https://github.com/user-attachments/assets/cda94dc4-9126-410a-bda3-12557c52bba0) | ![08B1369D-9340-4B61-AE3B-7B3BC07CEAAD](https://github.com/user-attachments/assets/8320f2e4-66c7-4eab-8612-866a544f6b80) |
> login: Prepare for dark theme

- lib/widgets/action_sheet.dart
This makes it a bit easier to scan the list.
Inspired by the thread at:
https://github.com/zulip/zulip-flutter/pull/853#discussion_r1721681638
(/cc @sm-sayedi)
> action_sheet [nfc]: Give more-uniform formatting to list of options

- lib/model/store.dart
This was completed in commit fa291285769b32221b948eee505039bf9bc4b3e1 (#871).
> store [nfc]: Remove completed TODO

- ios/Podfile.lock
- lib/model/binding.dart
- lib/widgets/lightbox.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- test/model/binding.dart
- test/widgets/lightbox_test.dart
>  lightbox: Toggle wakelock while video is playing

- README.md
- docs/setup.md
See the chat threads linked from the text:
https://chat.zulip.org/#narrow/stream/243-mobile-team/topic/flutter.20json_annotation.20unexpected.20behavior/near/1824410
https://chat.zulip.org/#narrow/stream/516-mobile-dev-help/topic/generated.20plugin.20files.20changed/near/1944826
> doc/setup: Say to set core.autocrlf on Windows; add troubleshooting

- test/example_data.dart
> test: Fix flake with identical consecutively autogenerated email addresses

- pubspec.yaml
CZO discussion:
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/tools.2Fcheck.20flutter_version.20failure.20in.20CI.3F/near/1999743
> deps [nfc]: Fix Flutter version/commit ID mismatch

- .github/workflows/ci.yml
- lib/widgets/home.dart
- test/widgets/home_test.dart
Fixes #1164.
Stacked atop #1176 to fix CI.
See [chat thread](https://chat.zulip.org/#narrow/channel/48-mobile/topic/combined.20feed/near/2009175) for UX discussion.
Screenshot:
> home: Add combined feed to bottom nav bar

- lib/widgets/store.dart
- test/widgets/store_test.dart
Prompted by:
https://chat.zulip.org/#narrow/channel/516-mobile-dev-help/topic/No.20PerAccountStoreWidget.20ancestor/near/2008484
> Add details to error on no PerAccountStoreWidget

- .mailmap
> mailmap: Add Akhil's mail map entry

- pubspec.yaml
- test/licenses_test.dart
> licenses: Add asset entry for KaTeX license

- assets/l10n/app_en.arb
- lib/generated/l10n/zulip_localizations.dart
- lib/generated/l10n/zulip_localizations_ar.dart
- lib/generated/l10n/zulip_localizations_en.dart
- lib/generated/l10n/zulip_localizations_ja.dart
- lib/generated/l10n/zulip_localizations_nb.dart
- lib/generated/l10n/zulip_localizations_sk.dart
- lib/generated/l10n/zulip_localizations_uk.dart
- lib/generated/l10n/zulip_localizations_zh.dart
Suggested by Alya:
https://chat.zulip.org/#narrow/channel/243-mobile-team/topic/last.20code.20changes.20for.20launch/near/2195900
> settings: Reword to "in conversation views" consistently

- lib/api/model/events.dart
- lib/api/model/events.g.dart
- lib/api/model/initial_snapshot.dart
- lib/api/model/initial_snapshot.g.dart
- lib/api/model/model.dart
- lib/api/model/model.g.dart
- lib/api/route/users.dart
- lib/api/route/users.g.dart
- lib/model/store.dart
- test/api/route/users_test.dart
- test/example_data.dart
This adds some realm/server settings to InitialSnapshot, and presences there, and adds the presence event and updatePresence binding.
Related: #196
> api: Prep for supporting presence

- .github/workflows/ci.yml
See https://github.com/zulip/zulip-flutter/pull/1688#issuecomment-3050713703 .
> ci: Further work around accidental desync of Flutter main branch

- lib/model/autocomplete.dart
- lib/model/emoji.dart
- lib/widgets/autocomplete.dart
- lib/widgets/new_dm_sheet.dart
- pubspec.lock
- pubspec.yaml
- test/model/autocomplete_test.dart
- test/model/emoji_test.dart
- test/widgets/new_dm_sheet_test.dart
> Match insensitively to diacritics (autocomplete and new-DMs)
